// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: checkout.checkouts
import { z } from "zod/v4";

export const Checkout = z.object({
  "id": z.string().uuid(),
  "user_id": z.string().uuid(),
  "direction": z.string(),
  "payment_method_id": z.string().uuid().nullable(),
  "payment_details_id": z.string().uuid().nullable(),
  "fulfillment_method_id": z.string().uuid().nullable(),
  "appointment_location_id": z.string().uuid().nullable(),
  "pickup_address_id": z.string().uuid().nullable(),
  "shipper_address_id": z.string().uuid().nullable(),
  "recipient_address_id": z.string().uuid().nullable(),
  "carrier_service_id": z.string().uuid().nullable(),
  "package_id": z.string().uuid().nullable(),
  "appointment_time": z.string().nullable(),
  "fulfillment_id": z.string().uuid().nullable(),
  "pickup_date": z.string().nullable(),
  "pickup_time": z.string().nullable(),
});
export type Checkout = z.infer<typeof Checkout>;
// generated:end
import { Direction } from "../orders/enums.js";
import { PaymentDetails } from "../payments/details.js";

// The columns a CUSTOMER may write on their own checkout row. Narrower than
// the table on purpose: fulfillment_id and the payout pointers are written by
// the services that also create what they point at, never by a request.
// package_weight and declared_value are GONE (ruling 58, migration 121): the
// server computes both from the checkout's own items and package.
//
// SPLIT IN TWO ON PURPOSE. `direction` names WHICH session is being written
// and is not a column of the patch, so the columns get their own schema: the
// controller parses the body strictly, then parses the columns out of it.
export const CheckoutPatch = Checkout.pick({
  payment_method_id: true,
  recipient_address_id: true,
  shipper_address_id: true,
  pickup_address_id: true,
  carrier_service_id: true,
  package_id: true,
  appointment_location_id: true,
  appointment_time: true,
  pickup_date: true,
  pickup_time: true,
}).partial();
export type CheckoutPatch = z.infer<typeof CheckoutPatch>;

export const CheckoutPatchBody = CheckoutPatch.extend({ direction: Direction }).strict();
export type CheckoutPatchBody = z.infer<typeof CheckoutPatchBody>;

// The stepper picks a carrier HANDOFF and never spells a fulfillment method;
// the server owns that vocabulary. Either names the step.
export const CheckoutFulfillmentBody = z.object({ direction: Direction })
  .extend({
    method_id: z.string().optional(),
    handoff_code: z.string().optional(),
  })
  .strict();
export type CheckoutFulfillmentBody = z.infer<typeof CheckoutFulfillmentBody>;

// The payout step's form (D210). THE TWO NUMBERS NEVER COME BACK: they are
// sealed at rest and the response carries only the last four digits.
export const CheckoutPayoutForm = PaymentDetails.pick({
  bank_name: true,
  account_type: true,
  routing_number: true,
  account_number: true,
})
  .partial()
  .extend({
    method: z.string(),
    account_holder_name: z.string(),
    payout_email: z.string().nullable().optional(),
  });
export type CheckoutPayoutForm = z.infer<typeof CheckoutPayoutForm>;

export const CheckoutPayoutBody = CheckoutPayoutForm.extend({ direction: Direction }).strict();
export type CheckoutPayoutBody = z.infer<typeof CheckoutPayoutBody>;

