// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: checkout.items
import { z } from "zod/v4";

export const CheckoutItem = z.object({
  "id": z.string().uuid(),
  "bullion_id": z.string().uuid().nullable(),
  "metal_id": z.string().uuid().nullable(),
  "checkout_id": z.string().uuid(),
  "pre_melt": z.number().nullable(),
  "post_melt": z.number().nullable(),
  "purity": z.number().nullable(),
  "premium": z.number().nullable(),
  "quantity": z.number().nullable(),
  "created_by": z.string().nullable(),
  "updated_by": z.string().nullable(),
  "created_at": z.string(),
  "updated_at": z.string(),
  "content": z.number().nullable(),
  "unit": z.string().nullable(),
});
export type CheckoutItem = z.infer<typeof CheckoutItem>;
// generated:end
// One basket line. Every column is optional - a create sends the same patch,
// and the table decides what it needs.
export const CheckoutItemPatch = CheckoutItem.pick({
  bullion_id: true,
  metal_id: true,
  pre_melt: true,
  post_melt: true,
  purity: true,
  unit: true,
  quantity: true,
}).partial().strict();
export type CheckoutItemPatch = z.infer<typeof CheckoutItemPatch>;

// The whole basket; the sync replaces rather than merges.
export const CheckoutItemsBody = z.object({ items: z.array(CheckoutItemPatch) }).strict();
export type CheckoutItemsBody = z.infer<typeof CheckoutItemsBody>;

