// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: checkout.items
import { z } from "zod/v4";

export const Row = z.object({
  "id": z.string().uuid(),
  "bullion_id": z.string().uuid().nullable(),
  "metal_id": z.string().uuid().nullable(),
  "checkout_id": z.string().uuid(),
  "pre_melt": z.number().nullable(),
  "post_melt": z.number().nullable(),
  "purity": z.number().nullable(),
  "premium": z.number().nullable(),
  "quantity": z.number().nullable(),
  "created_by": z.string().nullable(),
  "updated_by": z.string().nullable(),
  "created_at": z.string(),
  "updated_at": z.string(),
  "content": z.number().nullable(),
  "unit": z.string().nullable(),
});
export type Row = z.infer<typeof Row>;
// generated:end
// One basket line. The value columns are optional as well as nullable: a coin
// is a bullion_id and a quantity. `content` and `premium` are the server's.
export const New = Row.pick({
  bullion_id: true,
  metal_id: true,
  pre_melt: true,
  post_melt: true,
  purity: true,
  unit: true,
})
  .partial()
  .extend({ quantity: Row.shape.quantity.unwrap() })
  .strict();
export type New = z.infer<typeof New>;

// The whole basket; the sync replaces rather than merges.
export const SyncBody = z.object({ items: z.array(New) }).strict();
export type SyncBody = z.infer<typeof SyncBody>;

