// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: checkout.lots
import { z } from 'zod/v4'

export const CheckoutLot = z.object({
  'id': z.string().uuid(),
  'checkout_id': z.string().uuid(),
  'lot_id': z.string().uuid(),
  'created_at': z.string(),
  'updated_at': z.string(),
  'created_by_id': z.string().uuid().nullable(),
  'updated_by_id': z.string().uuid().nullable(),
})
export type CheckoutLot = z.infer<typeof CheckoutLot>
// generated:end

import { Lot } from '../lots/items.js'

// A basket line is one of two shapes and the boundary decides which (ruling
// 80): a bullion line names a product and a quantity, a scrap line declares its
// own metal and weights. Neither accepts the other's columns, and neither
// carries a premium - at checkout the premium is a live quote.
export const CheckoutBullionLot = Lot.pick({ bullion_id: true, quantity: true })
  .extend({
    bullion_id: Lot.shape.bullion_id.unwrap(),
    quantity: Lot.shape.quantity.optional(),
  })
  .strict()
export type CheckoutBullionLot = z.infer<typeof CheckoutBullionLot>

export const CheckoutScrapLot = Lot.pick({
  metal_id: true,
  pre_melt: true,
  post_melt: true,
  purity: true,
  unit: true,
  quantity: true,
})
  .extend({
    pre_melt: Lot.shape.pre_melt.unwrap(),
    post_melt: Lot.shape.post_melt.optional(),
    purity: Lot.shape.purity.unwrap(),
    quantity: Lot.shape.quantity.optional(),
  })
  .strict()
export type CheckoutScrapLot = z.infer<typeof CheckoutScrapLot>

export const CheckoutLotPatch = z.union([CheckoutBullionLot, CheckoutScrapLot])
export type CheckoutLotPatch = z.infer<typeof CheckoutLotPatch>

export const CheckoutLotsBody = z.object({ lots: z.array(CheckoutLotPatch) }).strict()
export type CheckoutLotsBody = z.infer<typeof CheckoutLotsBody>
