// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Every entity of the `organizations` schema, one namespace each.
export * from './organizations.js'
