// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: organizations.organizations
import { z } from "zod/v4";

export const Row = z.object({
  "id": z.string().uuid(),
  "image_id": z.string().uuid().nullable(),
  "type": z.string(),
  "name": z.string(),
  "email": z.string().nullable(),
  "phone": z.string().nullable(),
  "website": z.string().nullable(),
  "description": z.string().nullable(),
  "enabled": z.boolean(),
  "created_at": z.string(),
  "updated_at": z.string(),
  "created_by": z.string().nullable(),
  "updated_by": z.string().nullable(),
  "created_by_id": z.string().uuid().nullable(),
  "updated_by_id": z.string().uuid().nullable(),
});
export type Row = z.infer<typeof Row>;
// generated:end
// The organization BESIDE a carrier or a refiner, never smeared across it.
// name and enabled widen to nullable: both are composed through a join that
// can miss.
export const Summary = Row.pick({
  id: true,
  name: true,
  email: true,
  phone: true,
  enabled: true,
})
  .partial({ id: true })
  .extend({
    name: Row.shape.name.nullable(),
    enabled: Row.shape.enabled.nullable(),
  });
export type Summary = z.infer<typeof Summary>;

// What a carrier/refiner create or patch may write on the organization.
export const Write = Row.pick({
  name: true,
  email: true,
  phone: true,
  enabled: true,
}).partial();
export type Write = z.infer<typeof Write>;

