// Generates a zod schema per table, from information_schema.
//
// These are the *leaf* schemas: one per table, matching the columns exactly,
// including nullability and enum values. They are the ground truth the wire
// schemas are composed from, so a column added, dropped or made nullable shows
// up here rather than being discovered in production.
//
// The database holds two schema designs at once: the live `exchange` schema,
// and the domain-namespaced schemas (core, orders, payments, ...) a migration
// is moving toward. This generates from any list of them, one output file each,
// so a feature being moved can be written against the new tables while the rest
// of the API still reads the old ones.
//
// Never edit src/generated/*.ts by hand.
//
//   pnpm --filter @dorado/contracts generate
//   CONTRACT_SCHEMAS=exchange,orders pnpm --filter @dorado/contracts generate
import "dotenv/config";
import fs from "node:fs";
import path from "node:path";
import pg from "pg";

// Every schema the API reads. exchange is the one still serving traffic; the
// rest are the per-feature schemas it is migrating to.
const DEFAULT_SCHEMAS = [
  "exchange",
  "leads", "reviews", "rates", "spots", "products",
  "media", "organizations", "metals",
  "orders", "shipping", "tax", "payments", "fulfillments", "places",
].join(",");

const SCHEMAS = (process.env.CONTRACT_SCHEMAS ?? DEFAULT_SCHEMAS)
  .split(",")
  .map((s) => s.trim())
  .filter(Boolean);

const OUTDIR = path.join(import.meta.dirname, "..", "src", "generated");

// Contracts describe what crosses the wire, not what the driver hands back.
// Timestamps are therefore strings: they are ISO-8601 by the time they have
// been through JSON.stringify, whatever pg returned in process.
const TYPE_MAP = {
  uuid: "z.string().uuid()",
  text: "z.string()",
  character: "z.string()",
  "character varying": "z.string()",
  boolean: "z.boolean()",
  numeric: "z.number()",
  integer: "z.number().int()",
  bigint: "z.number().int()",
  smallint: "z.number().int()",
  "double precision": "z.number()",
  real: "z.number()",
  date: "z.string()",
  "time without time zone": "z.string()",
  "time with time zone": "z.string()",
  "timestamp with time zone": "z.string()",
  "timestamp without time zone": "z.string()",
  jsonb: "z.unknown()",
  json: "z.unknown()",
  bytea: "z.string()", // encoded to base64 in the queries that select it
};

const pascal = (s) =>
  s.split(/[_\s]+/).map((w) => w[0].toUpperCase() + w.slice(1)).join("");

const client = new pg.Client({
  connectionString: process.env.DATABASE_URL,
  ssl: { rejectUnauthorized: false },
});
await client.connect();

const target = new URL(process.env.DATABASE_URL);
console.log(`reading from ${target.pathname.slice(1)} @ ${target.hostname}`);

// Enums are keyed by schema AND name, never by name alone. Two schemas can
// hold different types with the same name - this database has orders.direction
// (purchase, sale) and shipping.direction (Inbound, Outbound, Return) - and
// collapsing them by name produces one enum with the union of both, which would
// accept values that are invalid everywhere they are used.
const { rows: enumRows } = await client.query(`
  SELECT n.nspname AS schema, t.typname AS name, e.enumlabel AS label
  FROM pg_type t
  JOIN pg_namespace n ON n.oid = t.typnamespace
  JOIN pg_enum e ON e.enumtypid = t.oid
  ORDER BY n.nspname, t.typname, e.enumsortorder
`);
const enums = {};
for (const r of enumRows) {
  (enums[`${r.schema}.${r.name}`] ??= new Set()).add(r.label);
}

fs.mkdirSync(OUTDIR, { recursive: true });
const unmapped = new Set();
const written = [];

for (const schema of SCHEMAS) {
  const { rows: tables } = await client.query(
    `SELECT table_name FROM information_schema.tables
     WHERE table_schema = $1 AND table_type = 'BASE TABLE'
     ORDER BY table_name`,
    [schema]
  );
  if (!tables.length) {
    console.log(`  ${schema}: no tables, skipped`);
    continue;
  }

  const { rows: columns } = await client.query(
    `SELECT table_name, column_name, data_type, udt_schema, udt_name, is_nullable
     FROM information_schema.columns
     WHERE table_schema = $1
     ORDER BY table_name, ordinal_position`,
    [schema]
  );
  const byTable = {};
  for (const c of columns) (byTable[c.table_name] ??= []).push(c);

  const parts = [
    `// GENERATED by packages/contracts/scripts/generate-tables.mjs
// Do not edit. Run \`pnpm --filter @dorado/contracts generate\` to refresh.
//
// Postgres schema: ${schema}
import { z } from "zod/v4";
`,
  ];

  // Only emit the enums this schema actually uses, so each file stands alone.
  const used = new Set(
    columns
      .filter((c) => c.data_type === "USER-DEFINED" && enums[`${c.udt_schema}.${c.udt_name}`])
      .map((c) => `${c.udt_schema}.${c.udt_name}`)
  );
  for (const qualified of used) {
    const values = [...enums[qualified]].map((l) => JSON.stringify(l)).join(", ");
    parts.push(`export const ${pascal(qualified.split(".")[1])} = z.enum([${values}]);`);
  }
  if (used.size) parts.push("");

  for (const { table_name } of tables) {
    const lines = (byTable[table_name] ?? []).map((c) => {
      let zod;
      if (c.data_type === "USER-DEFINED" && enums[`${c.udt_schema}.${c.udt_name}`]) {
        zod = pascal(c.udt_name);
      } else if (c.data_type === "ARRAY") {
        zod = `z.array(${TYPE_MAP[c.udt_name.replace(/^_/, "")] ?? "z.unknown()"})`;
      } else {
        zod = TYPE_MAP[c.data_type];
        if (!zod) {
          unmapped.add(`${c.data_type} (${schema}.${table_name}.${c.column_name})`);
          zod = "z.unknown()";
        }
      }
      if (c.is_nullable === "YES") zod += ".nullable()";
      return `  ${JSON.stringify(c.column_name)}: ${zod},`;
    });

    const name = `${pascal(table_name)}Row`;
    parts.push(`export const ${name} = z.object({
${lines.join("\n")}
});
export type ${name} = z.infer<typeof ${name}>;
`);
  }

  fs.writeFileSync(path.join(OUTDIR, `${schema}.ts`), parts.join("\n") + "\n");
  written.push(`${schema}.ts (${tables.length} tables)`);
}

await client.end();

console.log(`wrote ${written.join(", ")}`);
if (unmapped.size) {
  console.log("unmapped types (fell back to z.unknown()):");
  for (const u of unmapped) console.log("  " + u);
}
