// Generates a zod schema per table from information_schema.
//
// These are the *leaf* schemas: one per table, matching the columns exactly,
// including nullability and enum values. They are the ground truth the wire
// schemas are composed from, so a column added, dropped or made nullable shows
// up here rather than being discovered in production.
//
// Never edit src/generated/tables.ts by hand.
//
//   pnpm --filter @dorado/contracts generate
import "dotenv/config";
import fs from "node:fs";
import path from "node:path";
import pg from "pg";

const OUT = path.join(import.meta.dirname, "..", "src", "generated", "tables.ts");

// Contracts describe what crosses the wire, not what the driver hands back.
// Timestamps are therefore strings: they are ISO-8601 by the time they have
// been through JSON.stringify, whatever pg returned in process.
const TYPE_MAP = {
  uuid: "z.string().uuid()",
  text: "z.string()",
  character: "z.string()",
  "character varying": "z.string()",
  boolean: "z.boolean()",
  numeric: "z.number()",
  integer: "z.number().int()",
  bigint: "z.number().int()",
  smallint: "z.number().int()",
  "double precision": "z.number()",
  real: "z.number()",
  date: "z.string()",
  "timestamp with time zone": "z.string()",
  "timestamp without time zone": "z.string()",
  jsonb: "z.unknown()",
  json: "z.unknown()",
  bytea: "z.string()", // encoded to base64 in the queries that select it
};

const pascal = (s) =>
  s.split(/[_\s]+/).map((w) => w[0].toUpperCase() + w.slice(1)).join("");

const client = new pg.Client({
  connectionString: process.env.DATABASE_URL,
  ssl: { rejectUnauthorized: false },
});
await client.connect();

const target = new URL(process.env.DATABASE_URL);
console.log(`reading schema from ${target.pathname.slice(1)} @ ${target.hostname}`);

// Enum types, so USER-DEFINED columns become a real z.enum rather than a string.
const { rows: enumRows } = await client.query(`
  SELECT t.typname, e.enumlabel
  FROM pg_type t
  JOIN pg_enum e ON e.enumtypid = t.oid
  JOIN pg_namespace n ON n.oid = t.typnamespace
  ORDER BY t.typname, e.enumsortorder
`);
const enums = {};
for (const r of enumRows) (enums[r.typname] ??= new Set()).add(r.enumlabel);

const { rows: tables } = await client.query(`
  SELECT table_name FROM information_schema.tables
  WHERE table_schema = 'exchange' AND table_type = 'BASE TABLE'
  ORDER BY table_name
`);

const { rows: columns } = await client.query(`
  SELECT table_name, column_name, data_type, udt_name, is_nullable
  FROM information_schema.columns
  WHERE table_schema = 'exchange'
  ORDER BY table_name, ordinal_position
`);

const byTable = {};
for (const c of columns) (byTable[c.table_name] ??= []).push(c);

const unmapped = new Set();
const parts = [];

parts.push(`// GENERATED by packages/contracts/scripts/generate-tables.mjs
// Do not edit. Run \`pnpm --filter @dorado/contracts generate\` to refresh.
//
// One schema per table in the exchange schema, matching columns, nullability
// and enum values exactly. Wire schemas compose from these; they never restate
// a column type by hand.
import { z } from "zod/v4";
`);

// Enums first, so table schemas can reference them.
for (const [name, labels] of Object.entries(enums)) {
  const values = [...labels].map((l) => JSON.stringify(l)).join(", ");
  parts.push(`export const ${pascal(name)} = z.enum([${values}]);`);
}
if (Object.keys(enums).length) parts.push("");

for (const table of tables.map((t) => t.table_name)) {
  const cols = byTable[table] ?? [];
  const lines = cols.map((c) => {
    let zod;
    if (c.data_type === "USER-DEFINED" && enums[c.udt_name]) {
      zod = pascal(c.udt_name);
    } else if (c.data_type === "ARRAY") {
      const inner = TYPE_MAP[c.udt_name.replace(/^_/, "")] ?? "z.unknown()";
      zod = `z.array(${inner})`;
    } else {
      zod = TYPE_MAP[c.data_type];
      if (!zod) {
        unmapped.add(`${c.data_type} (${table}.${c.column_name})`);
        zod = "z.unknown()";
      }
    }
    if (c.is_nullable === "YES") zod += ".nullable()";
    return `  ${JSON.stringify(c.column_name)}: ${zod},`;
  });

  parts.push(`export const ${pascal(table)}Row = z.object({
${lines.join("\n")}
});
export type ${pascal(table)}Row = z.infer<typeof ${pascal(table)}Row>;
`);
}

fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, parts.join("\n") + "\n");

console.log(`wrote ${tables.length} table schemas to ${path.relative(process.cwd(), OUT)}`);
if (unmapped.size) {
  console.log("unmapped types (fell back to z.unknown()):");
  for (const u of unmapped) console.log("  " + u);
}
await client.end();
