// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: tax.sales_tax
import { z } from "zod/v4";

export const SalesTax = z.object({
  "id": z.string().uuid(),
  "state": z.string(),
  "reached_nexus": z.boolean(),
  "amount_owed": z.number(),
  "last_remitted": z.string().nullable(),
});
export type SalesTax = z.infer<typeof SalesTax>;
// generated:end
import { Bullion } from "../products/bullion.js";
import { Address } from "../places/addresses.js";

export const SalesTaxQuoteLine = Bullion.pick({ id: true }).extend({
  quantity: z.number(),
}).strict();
export type SalesTaxQuoteLine = z.infer<typeof SalesTaxQuoteLine>;

export const GetSalesTaxBody = z.object({
  address_id: Address.shape.id.nullable().optional(),
  items: z.array(SalesTaxQuoteLine).min(1),
}).strict();
export type GetSalesTaxBody = z.infer<typeof GetSalesTaxBody>;
