-- Stripe reconciliation data, from a dashboard export.
--
-- GENERATED by scripts/dump-stripe-reconciliation.mjs. Regenerate rather than
-- editing by hand, from a fresh export at the repo root:
--
--   node scripts/dump-stripe-reconciliation.mjs
--
-- 45 payment intents, 8 of which settled into a charge.
-- Export taken 2026-08-23.
--
-- Amounts are in DOLLARS, as Stripe exports them. exchange.payment_intents
-- stores CENTS.
--
-- Carries no personal data: no cardholder name, no billing address, no card
-- last4. See 054 for why this table exists and why it is not a correction
-- applied to exchange.
--
-- Idempotent: keyed on payment_intent_id, and re-running updates in place.
-- exchange is not read or written here at all.

INSERT INTO payments.stripe_charges (
  payment_intent_id, charge_id, created_at,
  amount, amount_refunded, fee,
  currency, captured, status,
  refunded_at, payment_source_type, stripe_customer_id, livemode
)
VALUES
  ('pi_3TuK5tCuc07t1nZa05PphD1v', 'ch_3TuK5tCuc07t1nZa0oiSdKd4', '2026-07-17 22:21:51'::timestamp AT TIME ZONE 'UTC', 10, 0, 0.59, 'usd', true, 'Paid', NULL, 'card', 'cus_UFfXA3UMHg4vxU', true),
  ('pi_3T0oFLCuc07t1nZa1zvmSa3g', NULL, '2026-02-14 19:11:15'::timestamp AT TIME ZONE 'UTC', 10, NULL, NULL, 'usd', NULL, 'requires_payment_method', NULL, NULL, 'cus_SY4gQUKZfr0bcT', true),
  ('pi_3SmgYrCuc07t1nZa0VM2li3C', NULL, '2026-01-06 20:09:01'::timestamp AT TIME ZONE 'UTC', 10, NULL, NULL, 'usd', NULL, 'requires_payment_method', NULL, NULL, 'cus_TkAQtP0c954NYW', true),
  ('pi_3SmgSLCuc07t1nZa0DfwwW3m', NULL, '2026-01-06 20:02:17'::timestamp AT TIME ZONE 'UTC', 10, NULL, NULL, 'usd', NULL, 'requires_payment_method', NULL, NULL, 'cus_TkAQtP0c954NYW', true),
  ('pi_3SmgF0Cuc07t1nZa0C45Ieg0', NULL, '2026-01-06 19:48:30'::timestamp AT TIME ZONE 'UTC', 10, NULL, NULL, 'usd', NULL, 'requires_payment_method', NULL, NULL, 'cus_SY4gQUKZfr0bcT', true),
  ('pi_3Smg4pCuc07t1nZa0L78DEEr', NULL, '2026-01-06 19:37:59'::timestamp AT TIME ZONE 'UTC', 10, NULL, NULL, 'usd', NULL, 'requires_payment_method', NULL, NULL, 'cus_SY4gQUKZfr0bcT', true),
  ('pi_3SgDpYCuc07t1nZa1C4RQt1J', NULL, '2025-12-20 00:15:32'::timestamp AT TIME ZONE 'UTC', 10, NULL, NULL, 'usd', NULL, 'requires_payment_method', NULL, NULL, 'cus_SY4gQUKZfr0bcT', true),
  ('pi_3SfoNgCuc07t1nZa1Hq2RMfo', NULL, '2025-12-18 21:05:04'::timestamp AT TIME ZONE 'UTC', 95.19, NULL, NULL, 'usd', NULL, 'requires_payment_method', NULL, NULL, 'cus_SXdS6D55wfw0JU', true),
  ('pi_3SfWZmCuc07t1nZa1vS2CbPe', NULL, '2025-12-18 02:04:22'::timestamp AT TIME ZONE 'UTC', 254.8, NULL, NULL, 'usd', NULL, 'requires_payment_method', NULL, NULL, 'cus_SYmfw38H9U9Hbk', true),
  ('pi_3SfQlOCuc07t1nZa0mGyh9fx', NULL, '2025-12-17 19:51:58'::timestamp AT TIME ZONE 'UTC', 4720.58, NULL, NULL, 'usd', NULL, 'requires_payment_method', NULL, NULL, 'cus_SY4gQUKZfr0bcT', true),
  ('pi_3SfQTSCuc07t1nZa0iRGSUSM', 'ch_3SfQTSCuc07t1nZa0mSLHmVn', '2025-12-17 19:38:45'::timestamp AT TIME ZONE 'UTC', 255.17, 0, 7.7, 'usd', true, 'Paid', NULL, 'card', 'cus_SYmfw38H9U9Hbk', true),
  ('pi_3SJzqiCuc07t1nZa1B0ciR9T', NULL, '2025-10-19 16:52:52'::timestamp AT TIME ZONE 'UTC', 5860.26, NULL, NULL, 'usd', NULL, 'requires_payment_method', NULL, NULL, 'cus_SXdS6D55wfw0JU', true),
  ('pi_3SAyWFCuc07t1nZa0Zwfb6VK', NULL, '2025-09-24 19:38:27'::timestamp AT TIME ZONE 'UTC', 4457.46, NULL, NULL, 'usd', NULL, 'requires_payment_method', NULL, NULL, 'cus_SY4gQUKZfr0bcT', true),
  ('pi_3S6Z94Cuc07t1nZa07guOnMQ', NULL, '2025-09-12 15:44:18'::timestamp AT TIME ZONE 'UTC', 74.83, NULL, NULL, 'usd', NULL, 'requires_payment_method', NULL, NULL, 'cus_SXdS6D55wfw0JU', true),
  ('pi_3S6MyVCuc07t1nZa0F98zCzF', NULL, '2025-09-12 02:44:35'::timestamp AT TIME ZONE 'UTC', 69.21, NULL, NULL, 'usd', NULL, 'requires_payment_method', NULL, NULL, 'cus_SXdS6D55wfw0JU', true),
  ('pi_3RvkVJCuc07t1nZa1GiS9Mxw', NULL, '2025-08-13 19:38:33'::timestamp AT TIME ZONE 'UTC', 10, NULL, NULL, 'usd', NULL, 'requires_payment_method', NULL, NULL, 'cus_SY4gQUKZfr0bcT', true),
  ('pi_3RvkITCuc07t1nZa1iuftgMc', 'py_3RvkITCuc07t1nZa1m4ULipV', '2025-08-13 19:30:09'::timestamp AT TIME ZONE 'UTC', 51.78, 0, 0.41, 'usd', true, 'Paid', NULL, 'us_bank_account', 'cus_SrTEGCYdQjrqRG', true),
  ('pi_3Rv5tPCuc07t1nZa0ygnpIyP', NULL, '2025-08-12 00:16:43'::timestamp AT TIME ZONE 'UTC', 68.01, NULL, NULL, 'usd', NULL, 'requires_payment_method', NULL, NULL, 'cus_SXdS6D55wfw0JU', true),
  ('pi_3RsX3lCuc07t1nZa0ETskMaH', NULL, '2025-08-04 22:40:49'::timestamp AT TIME ZONE 'UTC', 41.56, NULL, NULL, 'usd', NULL, 'requires_payment_method', NULL, NULL, 'cus_SXdS6D55wfw0JU', true),
  ('pi_3Royj7Cuc07t1nZa0brmjZDT', NULL, '2025-07-26 03:24:49'::timestamp AT TIME ZONE 'UTC', 421.63, NULL, NULL, 'usd', NULL, 'requires_payment_method', NULL, NULL, 'cus_SY4gQUKZfr0bcT', true),
  ('pi_3Rns6wCuc07t1nZa061DBVBc', NULL, '2025-07-23 02:08:50'::timestamp AT TIME ZONE 'UTC', 4507.23, NULL, NULL, 'usd', NULL, 'requires_payment_method', NULL, NULL, 'cus_SXdS6D55wfw0JU', true),
  ('pi_3RnPY8Cuc07t1nZa131etcqx', NULL, '2025-07-21 19:39:00'::timestamp AT TIME ZONE 'UTC', 25.73, NULL, NULL, 'usd', NULL, 'requires_confirmation', NULL, NULL, 'cus_SXdS6D55wfw0JU', true),
  ('pi_3Rn20SCuc07t1nZa0qvP7jc0', NULL, '2025-07-20 18:30:40'::timestamp AT TIME ZONE 'UTC', 70.14, NULL, NULL, 'usd', NULL, 'requires_confirmation', NULL, NULL, 'cus_SXdS6D55wfw0JU', true),
  ('pi_3Rn1naCuc07t1nZa15Yg7Cg5', NULL, '2025-07-20 18:17:22'::timestamp AT TIME ZONE 'UTC', 142.84, NULL, NULL, 'usd', NULL, 'requires_payment_method', NULL, NULL, 'cus_SY4gQUKZfr0bcT', true),
  ('pi_3RkuheCuc07t1nZa1qtyWVKL', NULL, '2025-07-14 22:18:30'::timestamp AT TIME ZONE 'UTC', 3623.8, NULL, NULL, 'usd', NULL, 'requires_payment_method', NULL, NULL, 'cus_SXdS6D55wfw0JU', true),
  ('pi_3RkugmCuc07t1nZa1kxD7kAY', NULL, '2025-07-14 22:17:36'::timestamp AT TIME ZONE 'UTC', 8887.68, NULL, NULL, 'usd', NULL, 'requires_payment_method', NULL, NULL, 'cus_SY4gQUKZfr0bcT', true),
  ('pi_3RkAmJCuc07t1nZa07rdVvxJ', NULL, '2025-07-12 21:16:15'::timestamp AT TIME ZONE 'UTC', 140.33, NULL, NULL, 'usd', NULL, 'requires_payment_method', NULL, NULL, 'cus_SY4gQUKZfr0bcT', true),
  ('pi_3RkAeYCuc07t1nZa0afpFl9u', NULL, '2025-07-12 21:08:14'::timestamp AT TIME ZONE 'UTC', 1365.69, NULL, NULL, 'usd', NULL, 'requires_payment_method', NULL, NULL, 'cus_SXdS6D55wfw0JU', true),
  ('pi_3RiODwCuc07t1nZa0y5ZZ9DQ', NULL, '2025-07-07 23:13:24'::timestamp AT TIME ZONE 'UTC', 25.72, NULL, NULL, 'usd', NULL, 'requires_payment_method', NULL, NULL, 'cus_SdfZCJl42LFuyK', true),
  ('pi_3RgCh9Cuc07t1nZa01NNQtKI', 'ch_3RgCh9Cuc07t1nZa0MpFUJQe', '2025-07-01 22:31:59'::timestamp AT TIME ZONE 'UTC', 1248.37, 1248.37, 36.5, 'usd', true, 'Refunded', '2025-07-01 22:53:10'::timestamp AT TIME ZONE 'UTC', 'card', 'cus_SbOuiJB71SE0sP', true),
  ('pi_3RgC6HCuc07t1nZa0yzhdIR6', NULL, '2025-07-01 21:52:25'::timestamp AT TIME ZONE 'UTC', 0.5, NULL, NULL, 'usd', NULL, 'requires_payment_method', NULL, NULL, 'cus_SbOuiJB71SE0sP', true),
  ('pi_3RgC6FCuc07t1nZa182pahx2', NULL, '2025-07-01 21:52:23'::timestamp AT TIME ZONE 'UTC', 1284.78, NULL, NULL, 'usd', NULL, 'requires_payment_method', NULL, NULL, 'cus_SbOudJ7b4cCFxn', true),
  ('pi_3Rf1gfCuc07t1nZa1PeT3Za6', NULL, '2025-06-28 16:33:09'::timestamp AT TIME ZONE 'UTC', 65.77, NULL, NULL, 'usd', NULL, 'requires_payment_method', NULL, NULL, 'cus_SXdS6D55wfw0JU', true),
  ('pi_3RehfSCuc07t1nZa1cjCxO4B', NULL, '2025-06-27 19:10:34'::timestamp AT TIME ZONE 'UTC', 25.71, NULL, NULL, 'usd', NULL, 'requires_payment_method', NULL, NULL, 'cus_SZrOw9bfVLMaAO', true),
  ('pi_3RdyRACuc07t1nZa16haHq7i', NULL, '2025-06-25 18:52:48'::timestamp AT TIME ZONE 'UTC', 428.84, NULL, NULL, 'usd', NULL, 'requires_payment_method', NULL, NULL, 'cus_SY4gQUKZfr0bcT', true),
  ('pi_3RdgEdCuc07t1nZa0WavNi4b', NULL, '2025-06-24 23:26:39'::timestamp AT TIME ZONE 'UTC', 425.71, NULL, NULL, 'usd', NULL, 'requires_payment_method', NULL, NULL, 'cus_SY4gQUKZfr0bcT', true),
  ('pi_3RdagpCuc07t1nZa1FMJ5gyD', NULL, '2025-06-24 17:31:23'::timestamp AT TIME ZONE 'UTC', 424.84, NULL, NULL, 'usd', NULL, 'requires_payment_method', NULL, NULL, 'cus_SY4gQUKZfr0bcT', true),
  ('pi_3RdLnXCuc07t1nZa0WhMVwZP', NULL, '2025-06-24 01:37:19'::timestamp AT TIME ZONE 'UTC', 451.97, NULL, NULL, 'usd', NULL, 'requires_payment_method', NULL, NULL, 'cus_SXdS6D55wfw0JU', true),
  ('pi_3Rd1X4Cuc07t1nZa1vFA3qRo', NULL, '2025-06-23 03:58:58'::timestamp AT TIME ZONE 'UTC', 70.39, NULL, NULL, 'usd', NULL, 'requires_payment_method', NULL, NULL, 'cus_SY7m6dZWL9wCQY', true),
  ('pi_3RcyXPCuc07t1nZa14bd0P9e', NULL, '2025-06-23 00:47:07'::timestamp AT TIME ZONE 'UTC', 90.44, NULL, NULL, 'usd', NULL, 'requires_payment_method', NULL, NULL, 'cus_SY4gQUKZfr0bcT', true),
  ('pi_3RcYBYCuc07t1nZa02fkDGj7', 'ch_3RcYBYCuc07t1nZa0brpwSU6', '2025-06-21 23:19:19'::timestamp AT TIME ZONE 'UTC', 64.7, 0, 2.18, 'usd', true, 'Paid', NULL, 'card', 'cus_SXdS6D55wfw0JU', true),
  ('pi_3RcYeyCuc07t1nZa1ZhVp9v4', NULL, '2025-06-21 21:09:12'::timestamp AT TIME ZONE 'UTC', 64.7, NULL, NULL, 'usd', NULL, 'requires_payment_method', NULL, NULL, 'cus_SXdwNHyR28vC9u', true),
  ('pi_3RcYBRCuc07t1nZa1YgtxcS5', 'ch_3RcYBRCuc07t1nZa18sWDeGg', '2025-06-21 20:42:04'::timestamp AT TIME ZONE 'UTC', 434, 434, 0, 'usd', false, 'Refunded', '2025-06-21 21:05:35'::timestamp AT TIME ZONE 'UTC', 'card', 'cus_SXdJdfRi9aEnsr', true),
  ('pi_3RcVdpCuc07t1nZa0SElqSGU', 'ch_3RcVdpCuc07t1nZa0exK9xKW', '2025-06-21 17:56:18'::timestamp AT TIME ZONE 'UTC', 114.8, 0, 3.63, 'usd', true, 'Paid', NULL, 'card', 'cus_SXaL4qR7SGg8OD', true),
  ('pi_3RcV9lCuc07t1nZa0u3oEneL', 'ch_3RcV9lCuc07t1nZa0FDYYKtv', '2025-06-21 17:25:30'::timestamp AT TIME ZONE 'UTC', 0.5, 0, 0.31, 'usd', true, 'Paid', NULL, 'card', 'cus_SXaKVDtOlduH4J', true)
ON CONFLICT (payment_intent_id) DO UPDATE SET
  charge_id           = EXCLUDED.charge_id,
  created_at          = EXCLUDED.created_at,
  amount              = EXCLUDED.amount,
  amount_refunded     = EXCLUDED.amount_refunded,
  fee                 = EXCLUDED.fee,
  currency            = EXCLUDED.currency,
  captured            = EXCLUDED.captured,
  status              = EXCLUDED.status,
  refunded_at         = EXCLUDED.refunded_at,
  payment_source_type = EXCLUDED.payment_source_type,
  stripe_customer_id  = EXCLUDED.stripe_customer_id,
  livemode            = EXCLUDED.livemode;
