// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: orders.addresses
import { z } from 'zod/v4'

export const OrderAddressLink = z.object({
  'id': z.string().uuid(),
  'address_id': z.string().uuid(),
  'order_id': z.string().uuid(),
  'source_address_id': z.string().uuid().nullable(),
})
export type OrderAddressLink = z.infer<typeof OrderAddressLink>
// generated:end
