// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: orders.items
import { z } from "zod/v4";

export const OrderItem = z.object({
  "id": z.string().uuid(),
  "order_id": z.string().uuid(),
  "bullion_id": z.string().uuid().nullable(),
  "metal_id": z.string().uuid(),
  "pre_melt": z.number().nullable(),
  "post_melt": z.number().nullable(),
  "purity": z.number().nullable(),
  "content": z.number().nullable(),
  "premium": z.number().nullable(),
  "quantity": z.number().nullable(),
  "confirmed": z.boolean(),
  "sales_tax_charged": z.number(),
  "unit": z.string().nullable(),
  "price": z.number().nullable(),
});
export type OrderItem = z.infer<typeof OrderItem>;
// generated:end
import { BullionPublic } from "../products/bullion.js";

// The line as ONE order's view carries it: the row plus the catalogue product
// behind a bullion line. Null on a scrap line, where the weights and the
// purity are columns of the line itself.
export const OrderViewItem = OrderItem.extend({ product: BullionPublic.nullable() });
export type OrderViewItem = z.infer<typeof OrderViewItem>;

// PATCH /api/orders/items/:id, and POST /orders/:id/items - ONE ROW, ONE PATCH
// (Jacob, 2026-09-03: the scrap / bullion split "is the old drawer document",
// and "For new, it can just send the patch!!"). A new line is a bullion_id or
// a metal_id with its weights; which one it is is a rule, not a type.
//
//   ABSENT   leave the column alone
//   null     clear it
//   a value  write it
//
// which is buildUpdate's contract. THREE COLUMNS ARE DELIBERATELY NOT HERE.
// `content` is DERIVED by rules.lineContent - two definitions of what content
// means is the defect that costs money. `price` is written by
// finalize-pricing from the frozen spots. `order_id` is the line's identity.
// The refiner's assay numbers are refiners.items and have their own patch.
export const OrderItemPatch = OrderItem.pick({
  bullion_id: true,
  metal_id: true,
  pre_melt: true,
  post_melt: true,
  purity: true,
  premium: true,
  quantity: true,
  confirmed: true,
  unit: true,
}).partial().strict();
export type OrderItemPatch = z.infer<typeof OrderItemPatch>;

