// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: orders.list_sorts
import { z } from 'zod/v4'

export const OrderSort = z.object({
  'id': z.string().uuid(),
  'key': z.string(),
  'label': z.string(),
  'sort_field': z.string(),
  'descending': z.boolean(),
  'sort_order': z.number().int(),
  'created_at': z.string(),
  'updated_at': z.string(),
  'created_by_id': z.string().uuid().nullable(),
  'updated_by_id': z.string().uuid().nullable(),
})
export type OrderSort = z.infer<typeof OrderSort>
// generated:end

// Hand-written derivations go here: New, Patch, named reads.
