// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: orders.lots
import { z } from 'zod/v4'

export const OrderLot = z.object({
  'id': z.string().uuid(),
  'order_id': z.string().uuid(),
  'lot_id': z.string().uuid(),
  'premium': z.number().nullable(),
  'price': z.number().nullable(),
  'sales_tax_charged': z.number(),
  'confirmed': z.boolean(),
  'created_at': z.string(),
  'updated_at': z.string(),
  'created_by_id': z.string().uuid().nullable(),
  'updated_by_id': z.string().uuid().nullable(),
})
export type OrderLot = z.infer<typeof OrderLot>
// generated:end

import { Lot, LotView } from '../lots/items.js'
import { RefiningOrder } from '../refining/orders.js'

export const OrderLotPatch = OrderLot.pick({
  premium: true,
  price: true,
  sales_tax_charged: true,
  confirmed: true,
})
  .merge(
    Lot.pick({
      bullion_id: true,
      metal_id: true,
      pre_melt: true,
      post_melt: true,
      purity: true,
      unit: true,
      quantity: true,
    })
  )
  .partial()
  .strict()
export type OrderLotPatch = z.infer<typeof OrderLotPatch>

export const OrderLotView = OrderLot.extend({
  lot: LotView,
  payable: Lot.shape.content,
  line_total: OrderLot.shape.price,
  settled: OrderLot.shape.confirmed,
  refining_order_number: RefiningOrder.shape.number.nullable(),
})
export type OrderLotView = z.infer<typeof OrderLotView>

export const OrderLotLine = OrderLot.pick({ lot_id: true })
export type OrderLotLine = z.infer<typeof OrderLotLine>

export const SoldLotPrice = z.object({
  lot_id: OrderLot.shape.lot_id,
  premium: OrderLot.shape.premium.unwrap(),
  sales_tax: OrderLot.shape.sales_tax_charged,
  price: OrderLot.shape.price.unwrap(),
})
export type SoldLotPrice = z.infer<typeof SoldLotPrice>
