// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: orders.lots
import { z } from 'zod/v4'

export const OrderLot = z.object({
  'id': z.string().uuid(),
  'order_id': z.string().uuid(),
  'lot_id': z.string().uuid(),
  'created_at': z.string(),
  'updated_at': z.string(),
  'created_by_id': z.string().uuid().nullable(),
  'updated_by_id': z.string().uuid().nullable(),
})
export type OrderLot = z.infer<typeof OrderLot>
// generated:end

import { Lot, LotPatch, LotView } from '../inventory/lots.js'
import { RefiningOrder } from '../refining/orders.js'

export const OrderLotPatch = Lot.pick({
  bullion_id: true,
  metal_id: true,
  pre_melt: true,
  post_melt: true,
  purity: true,
  unit: true,
  quantity: true,
  premium: true,
  sales_tax_rate: true,
  confirmed_at: true,
  settled_spot: true,
  source: true,
})
  .partial()
  .strict()
export type OrderLotPatch = z.infer<typeof OrderLotPatch>

export const OrderLotView = OrderLot.extend({
  lot: LotView,
  payable: Lot.shape.content,
  price: Lot.shape.content,
  line_total: Lot.shape.content,
  settled: z.boolean(),
  refining_order_number: RefiningOrder.shape.number.nullable(),
})
export type OrderLotView = z.infer<typeof OrderLotView>

export const OrderLotLine = OrderLot.pick({ lot_id: true })
export type OrderLotLine = z.infer<typeof OrderLotLine>

export const SoldLotPrice = z.object({
  lot_id: OrderLot.shape.lot_id,
  premium: Lot.shape.premium.unwrap(),
  sales_tax: Lot.shape.sales_tax_rate,
})
export type SoldLotPrice = z.infer<typeof SoldLotPrice>

export const AdoptAssayCandidate = z
  .object({ id: OrderLot.shape.id, lot_id: OrderLot.shape.lot_id })
  .extend({
    current: LotPatch,
    refiner: LotPatch.nullable(),
    share: Lot.shape.content,
    proposed: LotPatch,
  })
  .strict()
export type AdoptAssayCandidate = z.infer<typeof AdoptAssayCandidate>

export const AdoptAssayProposal = z.object({}).extend({
  lots: z.array(AdoptAssayCandidate),
})
export type AdoptAssayProposal = z.infer<typeof AdoptAssayProposal>

export const AdoptAssayLot = z
  .object({ id: OrderLot.shape.id })
  .extend({ figures: OrderLotPatch })
  .strict()
export type AdoptAssayLot = z.infer<typeof AdoptAssayLot>

export const AdoptAssayBody = z
  .object({})
  .extend({ lots: z.array(AdoptAssayLot).min(1), combine: z.boolean() })
  .partial({ combine: true })
  .strict()
export type AdoptAssayBody = z.infer<typeof AdoptAssayBody>
