// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: orders.orders
import { z } from "zod/v4";
import { Direction } from "./enums.js";

export const Row = z.object({
  "id": z.string().uuid(),
  "user_id": z.string().uuid().nullable(),
  "direction": Direction.nullable(),
  "status": z.string().nullable(),
  "number": z.number().int(),
  "notes": z.string().nullable(),
  "review_created": z.boolean().nullable(),
  "created_by": z.string().nullable(),
  "updated_by": z.string().nullable(),
  "created_at": z.string().nullable(),
  "updated_at": z.string().nullable(),
  "created_by_id": z.string().uuid().nullable(),
  "updated_by_id": z.string().uuid().nullable(),
  "order_sent": z.boolean().nullable(),
  "tracking_updated": z.boolean().nullable(),
  "spots_locked": z.boolean(),
});
export type Row = z.infer<typeof Row>;
// generated:end
import * as transactions from "./transactions.js";
import * as items from "./items.js";
import * as addresses from "../places/addresses.js";
import * as shipments from "../shipping/shipments.js";
import * as carrierPickups from "../shipping/pickups.js";
import * as payouts from "../exchange/payouts.js";
import * as users from "../auth/users.js";
import * as checkouts from "../checkout/checkouts.js";
import * as services from "../shipping/services.js";
import * as packages from "../shipping/packages.js";
import * as refiners from "../refiners/refiners.js";

// THE ORDER ON THE WIRE IS THE ROW (Jacob, wave 3): "We only need the
// bullion_id for production information. We don't need to send all that shit
// back in the body with it."
//
// So an order read returns the row VERBATIM plus `totals`, and nothing else.
// Every other piece of an order is its own parent-path read of its own table:
// /orders/:id/items, /spots, /address, /payouts, /fulfillments, /shipments,
// /pickups, /directs, /refiners. Display names are the CLIENT's job, mapped by
// id against reference reads it already caches.
//
// `totals` survives as a nested member where nothing else did, for the reason
// Jacob gave when he pinned the slim: transactions IS the order's money, not
// another resource's row borrowed onto it.
export const Read = Row.extend({ totals: transactions.Row.nullable() });
export type Read = z.infer<typeof Read>;

// THE ORDER VIEW - one order, assembled from its tables (D214 item 12).
//
// THE RULES THIS SHAPE OBEYS, each of which the composer it replaced broke:
//   ROWS, NOT PROJECTIONS. Every member is a generated row schema.
//   NESTED BY TABLE, NOT BY SLOT. `shipments` is the rows with their own
//   `direction` column - not a shipment / return_shipment pair.
//   ABSENT IS null. Never an object whose every key is null.
//   NO RENAMES and NO DERIVED SCALARS.
//   NOT A LIST WIRE. `Read` above is still what GET /orders serves.
export const View = z.object({
  order: Row,
  totals: transactions.Row.nullable(),
  items: z.array(items.ViewItem),
  address: addresses.Row.nullable(),
  shipments: z.array(shipments.View),
  pickup: carrierPickups.Row.nullable(),
  payout: payouts.OrderView.nullable(),
  user: users.Summary.nullable(),
});
export type View = z.infer<typeof View>;

// POST /{purchase,sales}_orders/create_* - THE WHOLE BODY IS ONE ID. Every
// fact the old body carried is a column of checkout.checkouts or
// checkout.items, which the server already holds; the customer is the
// checkout row's own user_id, so the admin door and the customer door take
// the same body.
export const New = z.object({ checkout_id: checkouts.Row.shape.id }).strict();
export type New = z.infer<typeof New>;

// PATCH /api/orders/:id - THE ORDER ROW'S OWN FIELDS, AND ONLY THOSE.
//
// Four operations left this document on 2026-09-03 (D214 item 11): add_funds,
// finalize_pricing, cancel and supplier were ACTIONS multiplexed through a
// PATCH body, and each is now POST /api/orders/:id/<action>. `status` is a
// pure customer-facing label driving no logic (ruling 2); `notes` is free
// text. Both are nullable, so an explicit null CLEARS and an absent key
// leaves the column alone - exactly what buildUpdate does with it.
export const Patch = Row.pick({ status: true, notes: true }).partial().strict();
export type Patch = z.infer<typeof Patch>;

// POST /{purchase,sales}_orders/create_review - the review flag. The order is
// sent whole because requireOwnOrder reads its id out of the body.
export const ReviewBody = z.object({
  order: z.looseObject({ id: Row.shape.id }),
  user_id: users.Row.shape.id.optional(),
}).strict();
export type ReviewBody = z.infer<typeof ReviewBody>;

// POST /orders/:id/cancel - the customer's metal goes back. Where the parcel
// goes is the ORDER's own address snapshot; who signs for it is the
// provider's configured contact; what it is worth is priced from the order's
// own lines. `weight` is the one MEASUREMENT: nothing stores what the parcel
// going back weighs, and a label cannot be bought without it.
export const CancelBody = z.object({
  carrier_service_id: services.Row.shape.id,
  package_id: packages.Row.shape.id,
}).extend({
  declared_value: z.number(),
  weight: z.number(),
}).strict();
export type CancelBody = z.infer<typeof CancelBody>;

// POST /orders/:id/send_to_refiner - which refinery gets the metal. The spots
// the message quotes are the ORDER's frozen ones, read server-side: they used
// to arrive in the body, which is the $26.81-an-ounce hazard.
export const SendToRefinerBody = z.object({
  refiner_id: refiners.Row.shape.id,
}).strict();
export type SendToRefinerBody = z.infer<typeof SendToRefinerBody>;

