// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: orders.orders
import { z } from 'zod/v4'
import { Direction } from './enums.js'

export const Order = z.object({
  'id': z.string().uuid(),
  'user_id': z.string().uuid().nullable(),
  'direction': Direction.nullable(),
  'status': z.string().nullable(),
  'number': z.number().int(),
  'notes': z.string().nullable(),
  'review_created': z.boolean().nullable(),
  'created_by': z.string().nullable(),
  'updated_by': z.string().nullable(),
  'created_at': z.string().nullable(),
  'updated_at': z.string().nullable(),
  'created_by_id': z.string().uuid().nullable(),
  'updated_by_id': z.string().uuid().nullable(),
  'order_sent': z.boolean().nullable(),
  'tracking_updated': z.boolean().nullable(),
  'spots_locked': z.boolean(),
  'assigned_to_id': z.string().uuid().nullable(),
})
export type Order = z.infer<typeof Order>
// generated:end
import { OrderTotals } from './transactions.js'
import { OrderLotView } from './lots.js'
import { Address } from '../places/addresses.js'
import { OrderViewShipment, Shipment } from '../shipping/shipments.js'
import { ShipmentPickup } from '../shipping/pickups.js'
import { OrderViewPayout } from '../payments/details.js'
import { User } from '../auth/users.js'
import { Checkout, CheckoutPayoutForm } from '../checkout/checkouts.js'
import { CheckoutLotPatch } from '../checkout/lots.js'
import { FulfillmentMethod } from '../fulfillments/methods.js'
import { FulfillmentPatchBody } from '../fulfillments/fulfillments.js'
import { CarrierService } from '../shipping/services.js'
import { Package } from '../shipping/packages.js'
import { Refiner } from '../refiners/refiners.js'
import { OrderActions, OrderViewUser } from '../computed/orders.js'
import { UserSummary } from '../auth/users.js'

export const OrderRead = Order.extend({ totals: OrderTotals.nullable() })
export type OrderRead = z.infer<typeof OrderRead>

// GET /api/orders' row: the header's reference and who the order belongs to,
// same as the single view (ruling 83 - no browser decides either).
export const OrderListItem = OrderRead.extend({
  reference: z.string(),
  customer: UserSummary.nullable(),
})
export type OrderListItem = z.infer<typeof OrderListItem>

// A shipment as an order shows it: the row, plus the two labels a document
// prints instead of an id. Both are scalar subselects in `db/orders/sql/view.sql`
// (ruling 78 - the shape is the SQL read's, not a services/packages Map).
export const OrderViewShipmentDetail = OrderViewShipment.extend({
  service_name: CarrierService.shape.name.nullable(),
  package_label: Package.shape.label.nullable(),
})
export type OrderViewShipmentDetail = z.infer<typeof OrderViewShipmentDetail>

export const OrderViewFacts = z
  .object({
    order: Order,
    totals: OrderTotals.nullable(),
    lots: z.array(OrderLotView),
    address: Address.nullable(),
    shipments: z.array(OrderViewShipmentDetail),
    pickup: ShipmentPickup.nullable(),
    payout: OrderViewPayout.nullable(),
    user: OrderViewUser.nullable(),
  })
  .extend({
    // No column holds this: it is EXISTS over the order's payments.ledger rows,
    // read in db/orders/sql/view.sql. `actions.add_funds` turns itself off from
    // it, and `addFunds` refuses on it (MP F4).
    credited: z.boolean(),
    // "PO-2481" / "SO-2481", built in db/orders/sql/view.sql. The prefix is a
    // label and no browser decides it (ruling 83).
    reference: z.string(),
  })
export type OrderViewFacts = z.infer<typeof OrderViewFacts>

export const OrderView = OrderViewFacts.extend({ actions: OrderActions })
export type OrderView = z.infer<typeof OrderView>

export const OrderPatch = Order.pick({ status: true, notes: true, assigned_to_id: true })
  .partial()
  .strict()
export type OrderPatch = z.infer<typeof OrderPatch>

export const OrderCreateBody = z.object({ checkout_id: Checkout.shape.id }).strict()
export type OrderCreateBody = z.infer<typeof OrderCreateBody>

// An admin places on a customer's behalf, so the body is exactly what makes a
// checkout placeable: checkout/rules.ts `checkoutState` (items, a fulfillment,
// and the direction's own settlement column) plus fulfillments/rules.ts
// `missingFor` (the chosen category's own choices).
export const AdminOrderFulfillment = z
  .object({
    method_id: FulfillmentMethod.shape.id,
    choices: FulfillmentPatchBody,
  })
  .strict()
export type AdminOrderFulfillment = z.infer<typeof AdminOrderFulfillment>

export const AdminPurchaseCreate = z
  .object({
    direction: Direction.extract(['purchase']),
    user_id: User.shape.id,
    lots: z.array(CheckoutLotPatch),
    fulfillment: AdminOrderFulfillment,
    payout: CheckoutPayoutForm,
  })
  .strict()
export type AdminPurchaseCreate = z.infer<typeof AdminPurchaseCreate>

export const AdminSaleCreate = z
  .object({
    direction: Direction.extract(['sale']),
    user_id: User.shape.id,
    lots: z.array(CheckoutLotPatch),
    fulfillment: AdminOrderFulfillment,
    payment_method_id: Checkout.shape.payment_method_id.unwrap(),
    recipient_address_id: Checkout.shape.recipient_address_id.unwrap(),
  })
  .strict()
export type AdminSaleCreate = z.infer<typeof AdminSaleCreate>

export const AdminOrderCreate = z.discriminatedUnion('direction', [
  AdminPurchaseCreate,
  AdminSaleCreate,
])
export type AdminOrderCreate = z.infer<typeof AdminOrderCreate>

// Every field is optional: the Figma header's Cancel is a bare button, so the
// server chooses the default return service and package when the caller names
// neither (ruling 76).
export const OrderCancelBody = z
  .object({
    carrier_service_id: CarrierService.shape.id,
    package_id: Package.shape.id,
  })
  .extend({ bill_return_to_customer: Shipment.shape.bill_return_to_customer })
  .partial()
  .strict()
export type OrderCancelBody = z.infer<typeof OrderCancelBody>

export const OrderSupplyBody = z
  .object({
    refiner_id: Refiner.shape.id,
  })
  .strict()
export type OrderSupplyBody = z.infer<typeof OrderSupplyBody>

export const OrderWrite = Order.omit({
  id: true,
  user_id: true,
  direction: true,
  number: true,
  created_by: true,
  updated_by: true,
  created_at: true,
  updated_at: true,
  created_by_id: true,
  updated_by_id: true,
}).partial()
export type OrderWrite = z.infer<typeof OrderWrite>

export const OrderGuard = Order.pick({ status: true, direction: true }).partial()
export type OrderGuard = z.infer<typeof OrderGuard>
