// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: orders.spots
import { z } from "zod/v4";

export const Row = z.object({
  "id": z.string().uuid(),
  "metal_id": z.string().uuid(),
  "order_id": z.string().uuid(),
  "ask": z.number().nullable(),
  "bid": z.number().nullable(),
  "scrap_percentage": z.number().nullable(),
  "bullion_percentage": z.number().nullable(),
  "created_at": z.string().nullable(),
  "updated_at": z.string().nullable(),
});
export type Row = z.infer<typeof Row>;
// generated:end
// PUT /orders/:id/spots - pin or unpin the order's spots, and adjust one.
// `set` names a metal by ID and not by name: a display string used to decide
// which money row an edit landed on.
export const Write = z.object({
  metal_id: Row.shape.metal_id,
  bid: Row.shape.bid.unwrap(),
}).strict();
export type Write = z.infer<typeof Write>;

// `lock: true` freezes every metal on the order at today's feed;
// `lock: false` clears the bids it pinned.
export const PutBody = z.object({ set: z.array(Write).optional() })
  .extend({ lock: z.boolean().optional() })
  .strict();
export type PutBody = z.infer<typeof PutBody>;

