// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: orders.spot_locks
import { z } from 'zod/v4'

export const SpotLockEvent = z.object({
  'id': z.string().uuid(),
  'order_id': z.string().uuid(),
  'metal_id': z.string(),
  'action': z.string(),
  'bid': z.number().nullable(),
  'ask': z.number().nullable(),
  'created_at': z.string(),
  'updated_at': z.string(),
  'created_by': z.string(),
  'updated_by': z.string(),
  'created_by_id': z.string().uuid().nullable(),
  'updated_by_id': z.string().uuid().nullable(),
})
export type SpotLockEvent = z.infer<typeof SpotLockEvent>
// generated:end

export const SpotLockAction = z.enum(['lock', 'unlock'])
export type SpotLockAction = z.infer<typeof SpotLockAction>
