// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: orders.transactions
import { z } from "zod/v4";

export const OrderTotals = z.object({
  "id": z.string().uuid(),
  "order_id": z.string().uuid().nullable(),
  "total": z.number().nullable(),
  "items": z.number().nullable(),
  "shipping": z.number().nullable(),
  "surcharge": z.number().nullable(),
  "sales_tax": z.number().nullable(),
  "funds": z.number().nullable(),
  "created_by": z.string().nullable(),
  "updated_by": z.string().nullable(),
  "created_at": z.string().nullable(),
  "updated_at": z.string().nullable(),
  "refiner_fee": z.number().nullable(),
  "created_by_id": z.string().uuid().nullable(),
  "updated_by_id": z.string().uuid().nullable(),
  "base_total": z.number().nullable(),
  "post_charges_amount": z.number().nullable(),
  "subject_to_charges_amount": z.number().nullable(),
  "used_funds": z.boolean().nullable(),
  "waive_shipping_fee": z.boolean().nullable(),
  "waive_payout_fee": z.boolean().nullable(),
  "shipping_paid": z.boolean().nullable(),
  "shipping_fee_actual": z.number().nullable(),
  "pool_remediation": z.number().nullable(),
  "pool_oz_deducted": z.number().nullable(),
  "shipping_service": z.string().nullable(),
  "payout_fee": z.number().nullable(),
  "payout_details_id": z.string().uuid().nullable(),
});
export type OrderTotals = z.infer<typeof OrderTotals>;
// generated:end

// Hand-written derivations go here: New, Patch, named reads.
