// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: orders.transactions
import { z } from "zod/v4";

export const OrderTotals = z.object({
  "id": z.string().uuid(),
  "order_id": z.string().uuid().nullable(),
  "total": z.number().nullable(),
  "items": z.number().nullable(),
  "shipping": z.number().nullable(),
  "surcharge": z.number().nullable(),
  "sales_tax": z.number().nullable(),
  "funds": z.number().nullable(),
  "created_by": z.string().nullable(),
  "updated_by": z.string().nullable(),
  "created_at": z.string().nullable(),
  "updated_at": z.string().nullable(),
  "refiner_fee": z.number().nullable(),
  "created_by_id": z.string().uuid().nullable(),
  "updated_by_id": z.string().uuid().nullable(),
  "base_total": z.number().nullable(),
  "post_charges_amount": z.number().nullable(),
  "subject_to_charges_amount": z.number().nullable(),
  "used_funds": z.boolean().nullable(),
  "waive_shipping_fee": z.boolean().nullable(),
  "waive_payout_fee": z.boolean().nullable(),
  "shipping_paid": z.boolean().nullable(),
  "shipping_fee_actual": z.number().nullable(),
  "pool_remediation": z.number().nullable(),
  "pool_oz_deducted": z.number().nullable(),
  "shipping_service": z.string().nullable(),
  "payout_fee": z.number().nullable(),
  "payout_details_id": z.string().uuid().nullable(),
});
export type OrderTotals = z.infer<typeof OrderTotals>;
// generated:end

// Hand-written derivations go here: Patch, named reads.

// WHAT ONE ORDER CAME TO, as a write. The audit columns are the `audit_stamp`
// trigger's and the id is the key, so everything else is nameable - a create
// and an update take the same document (there is no `New<Entity>`).
export const OrderTotalsPatch = OrderTotals.omit({
  id: true,
  created_by: true, updated_by: true, created_at: true, updated_at: true,
  created_by_id: true, updated_by_id: true,
}).partial();
export type OrderTotalsPatch = z.infer<typeof OrderTotalsPatch>;

// The nine columns an UPDATE may touch after placement. Most of this table is
// not patchable through there: the customer-facing subtotals are derived at
// placement and rewritten by finalize-pricing. `shipping` and
// `shipping_service` are on the list because the label is bought AFTER the
// placement commits (label-after-commit, 2026-09-03), so the carrier's answer
// arrives as a patch.
export const OrderTotalsWrite = OrderTotals.pick({
  total: true, shipping: true, shipping_service: true, shipping_fee_actual: true,
  refiner_fee: true, pool_oz_deducted: true, pool_remediation: true,
  payout_fee: true, waive_payout_fee: true, payout_details_id: true,
}).partial();
export type OrderTotalsWrite = z.infer<typeof OrderTotalsWrite>;
