// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: refiners.items
import { z } from "zod/v4";

export const RefinerItem = z.object({
  "id": z.string().uuid(),
  "order_item_id": z.string().uuid(),
  "refiner_id": z.string().uuid().nullable(),
  "bullion_id": z.string().uuid().nullable(),
  "metal_id": z.string().uuid(),
  "pre_melt": z.number().nullable(),
  "post_melt": z.number().nullable(),
  "purity": z.number().nullable(),
  "content": z.number().nullable(),
  "premium": z.number().nullable(),
  "quantity": z.number(),
  "unit": z.string().nullable(),
  "refiner_order_id": z.string().uuid().nullable(),
});
export type RefinerItem = z.infer<typeof RefinerItem>;
// generated:end
// PATCH /api/refiners/items/by-order-item/:orderItemId - the refinery's
// report on one customer line. EVERY FIELD IS NULLABLE HERE and that is not
// an oversight: an assay figure that is not yet known is null, the admin
// drawer clears an input to exactly that, and the service reads the current
// row and merges the document over it - so a null means "not measured" rather
// than "leave alone".
//
// `content` is DELIBERATELY not a field: it is derived from post_melt (or
// pre_melt) and purity, and the service refuses a raw override by name.
export const RefinerItemPatch = RefinerItem.pick({
  premium: true,
  pre_melt: true,
  post_melt: true,
  purity: true,
  unit: true,
}).partial().strict();
export type RefinerItemPatch = z.infer<typeof RefinerItemPatch>;

