// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: refiners.orders
import { z } from "zod/v4";

export const Row = z.object({
  "id": z.string().uuid(),
  "order_id": z.string().uuid(),
  "refiner_id": z.string().uuid().nullable(),
  "pool_oz_deducted": z.number().nullable(),
  "pool_remediation": z.number().nullable(),
  "fee": z.number().nullable(),
  "created_at": z.string(),
  "updated_at": z.string(),
});
export type Row = z.infer<typeof Row>;
// generated:end
import * as spots from "./spots.js";

// PATCH /api/refiners/orders/:id - the ENGAGEMENT's writable facts, and the
// file where the null question splits. Four of these five fields refuse null
// and the fifth keeps it, because they are not the same kind of value.
//
// THE THREE NUMBERS AND THE FEE REFUSE NULL: every reader defaults them to 0,
// so clearing a pool deduction and setting it to 0 are the same order.
//
// `refiner_id` KEEPS NULL, and it is a different kind of field: a nullable
// foreign key, not a fee. Every engagement starts with it null, so null is the
// column's own "no refinery yet". Detaching an engagement from a refinery is a
// real operation - the metal went to the wrong one.
export const Patch = Row.pick({
  pool_oz_deducted: true,
  pool_remediation: true,
  fee: true,
  refiner_id: true,
})
  .extend({
    spots: z.array(spots.Write).min(1).optional(),
    pool_oz_deducted: Row.shape.pool_oz_deducted.unwrap().optional(),
    pool_remediation: Row.shape.pool_remediation.unwrap().optional(),
    fee: Row.shape.fee.unwrap().optional(),
    refiner_id: Row.shape.refiner_id.optional(),
  })
  .strict();
export type Patch = z.infer<typeof Patch>;

