// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: refiners.refiners
import { z } from "zod/v4";

export const Row = z.object({
  "id": z.string().uuid(),
  "logo": z.string().nullable(),
  "organization_id": z.string().uuid(),
});
export type Row = z.infer<typeof Row>;
// generated:end
import * as organizations from "../organizations/organizations.js";

// A refiner and the organization it is, KEPT APART. A supplier is two rows in
// the new schema and the response says so rather than smearing the
// organization's fields across the top level.
export const Read = Row.omit({ organization_id: true }).extend({
  created_at: organizations.Row.shape.created_at.nullable(),
  updated_at: organizations.Row.shape.updated_at.nullable(),
  organization: organizations.Summary,
});
export type Read = z.infer<typeof Read>;

