// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: refiners.spots
import { z } from "zod/v4";

export const Row = z.object({
  "id": z.string().uuid(),
  "metal_id": z.string().uuid(),
  "refiner_id": z.string().uuid().nullable(),
  "order_id": z.string().uuid(),
  "pool_oz_deducted": z.number().nullable(),
  "ask": z.number().nullable(),
  "bid": z.number().nullable(),
  "scrap_percentage": z.number().nullable(),
  "bullion_percentage": z.number().nullable(),
  "created_at": z.string().nullable(),
  "updated_at": z.string().nullable(),
  "refiner_order_id": z.string().uuid().nullable(),
});
export type Row = z.infer<typeof Row>;
// generated:end
// A refiner spot write: which metal, at what bid. THE METAL IS AN ID, not a
// display name (D214 item 11): refiners.spots is keyed on
// (order_id, metal_id), the client already holds the id, and a name the
// server had to resolve turned an unrecognised spelling into a silently
// skipped bid.
export const Write = z.object({
  metal_id: Row.shape.metal_id,
  bid: Row.shape.bid.unwrap(),
}).strict();
export type Write = z.infer<typeof Write>;

