// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: shipping.carriers
import { z } from "zod/v4";

export const Row = z.object({
  "id": z.string().uuid(),
  "organization_id": z.string().uuid().nullable(),
  "logo": z.string().nullable(),
});
export type Row = z.infer<typeof Row>;
// generated:end
import * as organizations from "../organizations/organizations.js";

// A carrier and the organization it is, KEPT APART - the same split refiners
// gets. An organization exists independently and can be a refiner or a
// carrier, so it stays its own object.
export const Read = Row.omit({ organization_id: true }).extend({
  created_at: organizations.Row.shape.created_at.nullable(),
  updated_at: organizations.Row.shape.updated_at.nullable(),
  organization: organizations.Summary,
});
export type Read = z.infer<typeof Read>;

export const New = z.object({
  logo: Row.shape.logo.optional(),
  organization: organizations.Write.strict().optional(),
}).strict();
export type New = z.infer<typeof New>;

export const Patch = New.extend({ id: Row.shape.id });
export type Patch = z.infer<typeof Patch>;

export const DeleteBody = z.object({ carrier_id: Row.shape.id }).strict();
export type DeleteBody = z.infer<typeof DeleteBody>;

