// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres enum types owned by the `shipping` schema.
import { z } from "zod/v4";

export const Direction = z.enum(["Inbound", "Outbound", "Return"]);
export type Direction = z.infer<typeof Direction>;
