// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: shipping.packages
import { z } from "zod/v4";

export const Row = z.object({
  "id": z.string().uuid(),
  "carrier_id": z.string().uuid().nullable(),
  "image_id": z.string().uuid().nullable(),
  "created_by": z.string().uuid().nullable(),
  "updated_by": z.string().uuid().nullable(),
  "length": z.number().nullable(),
  "width": z.number().nullable(),
  "height": z.number().nullable(),
  "created_at": z.string(),
  "updated_at": z.string(),
  "label": z.string(),
  "is_carrier_packaging": z.boolean(),
  "min_weight_lb": z.number().nullable(),
});
export type Row = z.infer<typeof Row>;
// generated:end

// Hand-written derivations go here: New, Patch, named reads.
