// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: shipping.pickups
import { z } from "zod/v4";

export const Row = z.object({
  "id": z.string().uuid(),
  "shipment_id": z.string().uuid(),
  "requested_at": z.string().nullable(),
  "status": z.string(),
  "confirmation_number": z.string().nullable(),
  "location": z.string().nullable(),
});
export type Row = z.infer<typeof Row>;
// generated:end
import * as carriers from "./carriers.js";
import * as addresses from "../places/addresses.js";

// POST /shipping/check_pickup_availability - can this address be collected on
// that day, under that handoff code.
export const CheckBody = z.object({
  carrier_id: carriers.Row.shape.id.optional(),
  address_id: addresses.Row.shape.id,
}).extend({
  code: z.string(),
  readyDate: z.string(),
}).strict();
export type CheckBody = z.infer<typeof CheckBody>;

export const CancelBody = z.object({
  pickup_id: Row.shape.id,
  carrier_id: carriers.Row.shape.id.optional(),
}).strict();
export type CancelBody = z.infer<typeof CancelBody>;

