// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: shipping.services
import { z } from "zod/v4";

export const CarrierService = z.object({
  "id": z.string().uuid(),
  "carrier_id": z.string().uuid().nullable(),
  "name": z.string(),
  "description": z.string().nullable(),
  "code": z.string().nullable(),
  "provider_code": z.string().nullable(),
  "supports_pickups": z.boolean(),
  "supports_dropoffs": z.boolean(),
  "supports_returns": z.boolean(),
  "supports_insurance": z.boolean(),
  "is_international": z.boolean(),
  "is_residential": z.boolean(),
  "is_active": z.boolean(),
  "max_weight_lb": z.number().nullable(),
  "max_length_in": z.number().nullable(),
  "max_width_in": z.number().nullable(),
  "max_height_in": z.number().nullable(),
  "max_declared_value": z.number().nullable(),
  "min_transit_days": z.number().int().nullable(),
  "max_transit_days": z.number().int().nullable(),
  "display_order": z.number().int().nullable(),
  "created_at": z.string().nullable(),
  "updated_at": z.string().nullable(),
  "created_by": z.string().nullable(),
  "updated_by": z.string().nullable(),
  "created_by_id": z.string().uuid().nullable(),
  "updated_by_id": z.string().uuid().nullable(),
  "max_insured_value": z.number(),
  "price": z.number().nullable(),
  "display": z.boolean(),
});
export type CarrierService = z.infer<typeof CarrierService>;
// generated:end
// THE THREE LEGACY SPELLINGS ARE THE WIRE'S, KEPT ON PURPOSE: the column is
// `supports_pickups` and the field is `supports_pickup`; likewise
// `supports_dropoffs` and `max_weight_lb`. Both the read and the write use
// them, and get_all.sql aliases in the SELECT to match.
const Fields = CarrierService.omit({
  created_by_id: true,
  updated_by_id: true,
  supports_pickups: true,
  supports_dropoffs: true,
  max_weight_lb: true,
  max_insured_value: true,
  price: true,
  display: true,
}).extend({
  supports_pickup: CarrierService.shape.supports_pickups,
  supports_dropoff: CarrierService.shape.supports_dropoffs,
  max_weight_lbs: CarrierService.shape.max_weight_lb,
});

// GET /carrier_services - the admin per-carrier list, exactly what
// db/shipping/services/sql/get_all.sql projects.
export const CarrierServiceRead = Fields;
export type CarrierServiceRead = z.infer<typeof CarrierServiceRead>;

// Create and update take the same patch; the id names an existing service.
export const CarrierServicePatch = Fields.omit({
  created_at: true,
  updated_at: true,
  created_by: true,
  updated_by: true,
}).partial().strict();
export type CarrierServicePatch = z.infer<typeof CarrierServicePatch>;

// GET /carrier_services/sale_options - PUBLIC. The business's own
// carrier-agnostic priced rows: the customer picks the SERVICE at its fixed
// price and the refinery picks the carrier later. `display=false` rows ride
// along (FREE is the admin's grant), so which rows a surface shows is its own
// branch. Exactly db/shipping/services/sql/get_sale_options.sql's projection.
export const SaleShippingService = CarrierService.pick({
  id: true, name: true, code: true, price: true, display: true, is_active: true,
  min_transit_days: true, max_transit_days: true,
});
export type SaleShippingService = z.infer<typeof SaleShippingService>;

export const CarrierServiceDeleteBody = z.object({ id: CarrierService.shape.id }).strict();
export type CarrierServiceDeleteBody = z.infer<typeof CarrierServiceDeleteBody>;


// EVERY COLUMN A CREATE OR AN UPDATE SUPPLIES, in the TABLE's spelling. Three
// of them alias on the wire (supports_pickup(s), supports_dropoff(s),
// max_weight_lb(s)) and `CarrierServicePatch` above is the wire's list; this is
// the column list the statements bind, so the one map between them lives in
// db/shipping/services/repo.ts and nowhere else.
export const CarrierServiceWrite = CarrierService.pick({
  carrier_id: true, name: true, description: true, code: true, provider_code: true,
  supports_pickups: true, supports_dropoffs: true, supports_returns: true,
  supports_insurance: true, is_international: true, is_residential: true,
  is_active: true, max_weight_lb: true, max_length_in: true, max_width_in: true,
  max_height_in: true, max_declared_value: true, min_transit_days: true,
  max_transit_days: true, display_order: true,
});
export type CarrierServiceWrite = z.infer<typeof CarrierServiceWrite>;

// WHAT DORADO WILL INSURE A PARCEL FOR on one service, read on its own rather
// than folded into the row reads - it is the one column the checkout catalogue
// joins on (migration 097).
export const InsuranceCeiling = CarrierService.pick({
  id: true, name: true, max_insured_value: true,
});
export type InsuranceCeiling = z.infer<typeof InsuranceCeiling>;
