// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: shipping.services
import { z } from "zod/v4";

export const Row = z.object({
  "id": z.string().uuid(),
  "carrier_id": z.string().uuid().nullable(),
  "name": z.string(),
  "description": z.string().nullable(),
  "code": z.string().nullable(),
  "provider_code": z.string().nullable(),
  "supports_pickups": z.boolean(),
  "supports_dropoffs": z.boolean(),
  "supports_returns": z.boolean(),
  "supports_insurance": z.boolean(),
  "is_international": z.boolean(),
  "is_residential": z.boolean(),
  "is_active": z.boolean(),
  "max_weight_lb": z.number().nullable(),
  "max_length_in": z.number().nullable(),
  "max_width_in": z.number().nullable(),
  "max_height_in": z.number().nullable(),
  "max_declared_value": z.number().nullable(),
  "min_transit_days": z.number().int().nullable(),
  "max_transit_days": z.number().int().nullable(),
  "display_order": z.number().int().nullable(),
  "created_at": z.string().nullable(),
  "updated_at": z.string().nullable(),
  "created_by": z.string().nullable(),
  "updated_by": z.string().nullable(),
  "created_by_id": z.string().uuid().nullable(),
  "updated_by_id": z.string().uuid().nullable(),
  "max_insured_value": z.number(),
  "price": z.number().nullable(),
  "display": z.boolean(),
});
export type Row = z.infer<typeof Row>;
// generated:end
// The writable columns of one carrier service.
//
// THE THREE LEGACY SPELLINGS ARE THE WIRE'S, KEPT ON PURPOSE: the column is
// `supports_pickups` and the field is `supports_pickup`; likewise
// `supports_dropoffs` and `max_weight_lb`. Wire shapes never moved during
// the schema migration and these are what the admin form sends.
const Fields = Row.omit({
  id: true,
  created_at: true,
  updated_at: true,
  created_by: true,
  updated_by: true,
  created_by_id: true,
  updated_by_id: true,
  supports_pickups: true,
  supports_dropoffs: true,
  max_weight_lb: true,
  max_insured_value: true,
  price: true,
  display: true,
}).extend({
  supports_pickup: Row.shape.supports_pickups,
  supports_dropoff: Row.shape.supports_dropoffs,
  max_weight_lbs: Row.shape.max_weight_lb,
}).partial({
  carrier_id: true,
  description: true,
  code: true,
  provider_code: true,
  supports_pickup: true,
  supports_dropoff: true,
  supports_returns: true,
  supports_insurance: true,
  is_international: true,
  is_residential: true,
  is_active: true,
  max_weight_lbs: true,
  max_length_in: true,
  max_width_in: true,
  max_height_in: true,
  max_declared_value: true,
  min_transit_days: true,
  max_transit_days: true,
  display_order: true,
});

export const New = Fields.strict();
export type New = z.infer<typeof New>;

export const Patch = Fields.extend({ id: Row.shape.id }).strict();
export type Patch = z.infer<typeof Patch>;

export const DeleteBody = z.object({ id: Row.shape.id }).strict();
export type DeleteBody = z.infer<typeof DeleteBody>;

