// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: shipping.shipments
import { z } from 'zod/v4'
import { ShipmentDirection } from './enums.js'

export const Shipment = z.object({
  'id': z.string().uuid(),
  'carrier_service_id': z.string().uuid().nullable(),
  'package_id': z.string().uuid().nullable(),
  'recipient_address_id': z.string().uuid().nullable(),
  'shipper_address_id': z.string().uuid().nullable(),
  'tracking_number': z.string().nullable(),
  'delivered_at': z.string().nullable(),
  'shipped_at': z.string().nullable(),
  'est_delivery': z.string().nullable(),
  'label_type': z.string().nullable(),
  'label': z.string().nullable(),
  'direction': ShipmentDirection,
  'insured': z.boolean(),
  'declared_value': z.number().nullable(),
  'cost': z.number().nullable(),
  'actual_cost': z.number().nullable(),
  'shipping_status': z.string().nullable(),
  'pickup_type': z.string().nullable(),
  'created_at': z.string().nullable(),
  'pickup_date': z.string().nullable(),
  'pickup_time': z.string().nullable(),
  'user_id': z.string().uuid().nullable(),
})
export type Shipment = z.infer<typeof Shipment>
// generated:end
import { Carrier } from './carriers.js'
import { Address } from '../places/addresses.js'

// Without user_id: 137 stamps the parcel's owner so the composite key can check
// its addresses, and no read projects it - the owner of a parcel is the order's
// owner, which every one of these views already carries.
export const OrderViewShipment = Shipment.omit({ user_id: true }).extend({
  direction: z.string(),
})
export type OrderViewShipment = z.infer<typeof OrderViewShipment>

export const ShipmentRead = OrderViewShipment.omit({ label: true })
export type ShipmentRead = z.infer<typeof ShipmentRead>

// No `carrier_id`. It was required to travel with `tracking_number` and then
// discarded - the carrier a tracking number belongs to is whatever the
// shipment's own `carrier_service_id` already says (LD F16).
export const ShipmentPatch = Shipment.pick({ tracking_number: true })
  .extend({
    shipping_charge: z.number().optional(),
    shipping_actual: z.number().optional(),
    tracking_number: Shipment.shape.tracking_number.unwrap().optional(),
  })
  .strict()
export type ShipmentPatch = z.infer<typeof ShipmentPatch>

// `user_id` is the parcel owner 137's composite key checks the address against.
// It is claimed by its own statement (`claimOwner`), never through a patch, so
// no caller can move a parcel into somebody else's book by sending a field.
export const ShipmentPatchColumns = Shipment.omit({
  id: true,
  created_at: true,
  user_id: true,
}).partial()
export type ShipmentPatchColumns = z.infer<typeof ShipmentPatchColumns>

export const ShippingValidateAddressBody = z
  .object({
    carrier_id: Carrier.shape.id.optional(),
    address_id: Address.shape.id,
  })
  .strict()
export type ShippingValidateAddressBody = z.infer<typeof ShippingValidateAddressBody>

export const ShippingGetLocationsBody = z
  .object({
    carrier_id: Carrier.shape.id.optional(),
    address_id: Address.shape.id,
  })
  .extend({
    radius_miles: z.number().optional(),
    max_results: z.number().optional(),
  })
  .strict()
export type ShippingGetLocationsBody = z.infer<typeof ShippingGetLocationsBody>

export const ShippingCancelLabelBody = z
  .object({
    shipment_id: Shipment.shape.id,
    carrier_id: Carrier.shape.id.optional(),
  })
  .strict()
export type ShippingCancelLabelBody = z.infer<typeof ShippingCancelLabelBody>

export const ShipmentWrite = ShipmentPatchColumns.extend({
  label: z.union([z.string(), z.custom<Uint8Array>()]).nullable().optional(),
  est_delivery: z.union([z.string(), z.date()]).nullable().optional(),
  shipped_at: z.union([z.string(), z.date()]).nullable().optional(),
  delivered_at: z.union([z.string(), z.date()]).nullable().optional(),
})
export type ShipmentWrite = z.infer<typeof ShipmentWrite>
