// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: shipping.shipments
import { z } from "zod/v4";
import { Direction } from "./enums.js";

export const Row = z.object({
  "id": z.string().uuid(),
  "carrier_service_id": z.string().uuid().nullable(),
  "package_id": z.string().uuid().nullable(),
  "recipient_address_id": z.string().uuid().nullable(),
  "shipper_address_id": z.string().uuid().nullable(),
  "tracking_number": z.string().nullable(),
  "delivered_at": z.string().nullable(),
  "shipped_at": z.string().nullable(),
  "est_delivery": z.string().nullable(),
  "label_type": z.string().nullable(),
  "label": z.string().nullable(),
  "direction": Direction,
  "insured": z.boolean(),
  "declared_value": z.number().nullable(),
  "cost": z.number().nullable(),
  "actual_cost": z.number().nullable(),
  "shipping_status": z.string().nullable(),
  "pickup_type": z.string().nullable(),
  "created_at": z.string().nullable(),
});
export type Row = z.infer<typeof Row>;
// generated:end
import * as carriers from "./carriers.js";
import * as packages from "./packages.js";
import * as addresses from "../places/addresses.js";
import { Direction as ShippingDirection } from "./enums.js";

// The order's parcels as ONE order's view carries them. `direction` widens to
// text because the read casts it - it is an enum in the table and a string on
// every wire it has ever reached.
export const View = Row.extend({ direction: z.string() });
export type View = z.infer<typeof View>;

// PATCH /api/shipments/:id - the shipment's money and its tracking pair.
//
// `shipping_charge` IS NOT NULLABLE, and this is one of the five decisions
// the API/frontend drift forced. A cleared charge would be indistinguishable
// from a zero one: every consumer reads `?? 0`. A stored fee is a record
// (D117) - "free" is 0, and there is no third state to express.
//
// `tracking_number` and `carrier_id` travel together; the service refuses
// half a pair by name.
export const Patch = Row.pick({ tracking_number: true })
  .extend({
    shipping_charge: z.number().optional(),
    shipping_actual: z.number().optional(),
    tracking_number: Row.shape.tracking_number.unwrap().optional(),
    carrier_id: carriers.Row.shape.id.optional(),
  })
  .strict();
export type Patch = z.infer<typeof Patch>;

// The provider calls. Every one names an ADDRESS BY ID (ruling 43); the
// carrier is optional because one provider is configured by default.
export const ValidateAddressBody = z.object({
  carrier_id: carriers.Row.shape.id.optional(),
  address_id: addresses.Row.shape.id,
}).strict();
export type ValidateAddressBody = z.infer<typeof ValidateAddressBody>;

export const RatesBody = z.object({
  carrier_id: carriers.Row.shape.id.optional(),
  address_id: addresses.Row.shape.id,
  package_id: packages.Row.shape.id,
  shippingType: ShippingDirection,
}).extend({
  weight: z.number(),
  pickupType: z.string().optional(),
  declaredValue: z.number().optional(),
}).strict();
export type RatesBody = z.infer<typeof RatesBody>;

export const LocationsBody = z.object({
  carrier_id: carriers.Row.shape.id.optional(),
  address_id: addresses.Row.shape.id,
}).extend({
  radius_miles: z.number().optional(),
  max_results: z.number().optional(),
}).strict();
export type LocationsBody = z.infer<typeof LocationsBody>;

export const CancelBody = z.object({
  shipment_id: Row.shape.id,
  carrier_id: carriers.Row.shape.id.optional(),
}).strict();
export type CancelBody = z.infer<typeof CancelBody>;

