// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: shipping.tracking
import { z } from "zod/v4";

export const TrackingRecord = z.object({
  "id": z.string().uuid(),
  "shipment_id": z.string().uuid(),
  "status": z.string().nullable(),
  "location": z.string().nullable(),
  "time": z.string().nullable(),
});
export type TrackingRecord = z.infer<typeof TrackingRecord>;
// generated:end
import { Shipment } from "./shipments.js";

// POST /shipping/get_tracking - the shipment id alone; the carrier and the
// tracking number are the shipment's own columns.
export const ShippingGetTrackingBody = z.object({
  shipment_id: Shipment.shape.id,
}).strict();
export type ShippingGetTrackingBody = z.infer<typeof ShippingGetTrackingBody>;

