// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: shipping.tracking
import { z } from "zod/v4";

export const Row = z.object({
  "id": z.string().uuid(),
  "shipment_id": z.string().uuid(),
  "status": z.string().nullable(),
  "location": z.string().nullable(),
  "time": z.string().nullable(),
});
export type Row = z.infer<typeof Row>;
// generated:end
import * as shipments from "./shipments.js";

// POST /shipping/get_tracking - the shipment id alone; the carrier and the
// tracking number are the shipment's own columns.
export const Body = z.object({
  shipment_id: shipments.Row.shape.id,
}).strict();
export type Body = z.infer<typeof Body>;

