// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: reviews.reviews
import { z } from "zod/v4";

export const Row = z.object({
  "id": z.string().uuid(),
  "user_id": z.string().uuid().nullable(),
  "order_id": z.string().uuid().nullable(),
  "name": z.string().nullable(),
  "review_text": z.string().nullable(),
  "rating": z.number().nullable(),
  "hidden": z.boolean(),
  "created_at": z.string(),
  "updated_at": z.string(),
  "created_by": z.string().nullable(),
  "updated_by": z.string().nullable(),
  "created_by_id": z.string().uuid().nullable(),
  "updated_by_id": z.string().uuid().nullable(),
});
export type Row = z.infer<typeof Row>;
// generated:end
// POST /reviews/create - THE FOUR COLUMNS THE SERVICE ACTUALLY WRITES.
// created_by/updated_by are NOT fields here: public.audit_stamp writes both
// from the connection's actor, and neither was ever a column create() took -
// carrying them just meant a caller's claimed author was silently discarded
// rather than refused.
export const New = Row.pick({
  review_text: true,
  rating: true,
  name: true,
  hidden: true,
}).partial();
export type New = z.infer<typeof New>;

// PATCH - the same four columns.
export const Patch = New;
export type Patch = z.infer<typeof Patch>;

