// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: fulfillments.directs
import { z } from "zod/v4";

export const FulfillmentDirect = z.object({
  "id": z.string().uuid(),
  "fulfillment_id": z.string().uuid(),
  "location_id": z.string().uuid(),
  "assigned_employee_id": z.string().uuid().nullable(),
  "is_appointment": z.boolean(),
  "start_time": z.string().nullable(),
  "end_time": z.string().nullable(),
});
export type FulfillmentDirect = z.infer<typeof FulfillmentDirect>;
// generated:end
// The booking's own columns, all optional; the id is the service's to issue.
export const FulfillmentDirectPatch = FulfillmentDirect.omit({ id: true }).partial();
export type FulfillmentDirectPatch = z.infer<typeof FulfillmentDirectPatch>;

// THE COLUMNS db/fulfillments/directs/repo.ts's update() MAY TOUCH (ruling 64) -
// `fulfillment_id` is the WHERE key, dropped for the same reason the schedule
// body drops it too.
export const FulfillmentDirectPatchColumns = FulfillmentDirectPatch.omit({ fulfillment_id: true });
export type FulfillmentDirectPatchColumns = z.infer<typeof FulfillmentDirectPatchColumns>;

// POST /fulfillments/schedule_direct - the fulfillment named ONCE, at the top
// level, and the appointment beside it (ruling 43).
export const FulfillmentScheduleDirectBody = z.object({
  fulfillment_id: FulfillmentDirect.shape.fulfillment_id,
  direct: FulfillmentDirectPatch.omit({ fulfillment_id: true }).strict(),
}).strict();
export type FulfillmentScheduleDirectBody = z.infer<typeof FulfillmentScheduleDirectBody>;

