// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: fulfillments.directs
import { z } from "zod/v4";

export const FulfillmentDirect = z.object({
  "id": z.string().uuid(),
  "fulfillment_id": z.string().uuid(),
  "location_id": z.string().uuid(),
  "assigned_employee_id": z.string().uuid().nullable(),
  "is_appointment": z.boolean(),
  "start_time": z.string().nullable(),
  "end_time": z.string().nullable(),
});
export type FulfillmentDirect = z.infer<typeof FulfillmentDirect>;
// generated:end
// POST /fulfillments/schedule_direct - the booking's own columns, all
// optional; the id is the service's to issue.
export const FulfillmentDirectPatch = FulfillmentDirect.omit({ id: true }).partial();
export type FulfillmentDirectPatch = z.infer<typeof FulfillmentDirectPatch>;

