// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: fulfillments.dropoffs
import { z } from 'zod/v4'

export const FulfillmentDropoff = z.object({
  'id': z.string().uuid(),
  'fulfillment_id': z.string().uuid(),
  'refiner_id': z.string().uuid().nullable(),
  'location_id': z.string().uuid().nullable(),
  'driver_employee_id': z.string().uuid().nullable(),
  'start_time': z.string().nullable(),
  'end_time': z.string().nullable(),
  'departed_at': z.string().nullable(),
  'dropped_off_at': z.string().nullable(),
  'created_at': z.string(),
  'updated_at': z.string(),
  'created_by_id': z.string().uuid().nullable(),
  'updated_by_id': z.string().uuid().nullable(),
})
export type FulfillmentDropoff = z.infer<typeof FulfillmentDropoff>
// generated:end

export const FulfillmentDropoffPatch = FulfillmentDropoff.omit({ id: true }).partial()
export type FulfillmentDropoffPatch = z.infer<typeof FulfillmentDropoffPatch>

export const FulfillmentDropoffPatchColumns = FulfillmentDropoffPatch.omit({
  fulfillment_id: true,
})
export type FulfillmentDropoffPatchColumns = z.infer<typeof FulfillmentDropoffPatchColumns>
