// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres enum types owned by the `fulfillments` schema.
import { z } from 'zod/v4'

export const FulfillmentCategory = z.enum(['SHIPMENT', 'PICKUP', 'DIRECT', 'DROPOFF'])
export type FulfillmentCategory = z.infer<typeof FulfillmentCategory>

export const FulfillmentStatus = z.enum([
  'PENDING',
  'SCHEDULED',
  'IN_TRANSIT',
  'PICKED_UP',
  'IN_PROGRESS',
  'COMPLETED',
  'DROPPED_OFF',
])
export type FulfillmentStatus = z.infer<typeof FulfillmentStatus>
