// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres enum types owned by the `fulfillments` schema.
import { z } from "zod/v4";

export const Category = z.enum(["SHIPMENT", "PICKUP", "DIRECT"]);
export type Category = z.infer<typeof Category>;
