// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: fulfillments.fulfillments
import { z } from "zod/v4";

export const Fulfillment = z.object({
  "id": z.string().uuid(),
  "method_id": z.string().uuid(),
  "order_id": z.string().uuid().nullable(),
  "status": z.string(),
  "created_by": z.string().nullable(),
  "updated_by": z.string().nullable(),
  "created_at": z.string(),
  "updated_at": z.string(),
  "created_by_id": z.string().uuid().nullable(),
  "updated_by_id": z.string().uuid().nullable(),
});
export type Fulfillment = z.infer<typeof Fulfillment>;
// generated:end
import { FulfillmentMethod } from "./methods.js";

// GET /orders/:orderId/fulfillments - THE BARE ROW, verbatim, and nothing
// else (rulings 9 + 12). No method embed - methods are reference data the
// client maps by method_id off GET /fulfillments/methods - and no resolved
// children: the shipment, pickup and direct reads are their own parent-path
// endpoints.
// THE COLUMNS A WRITE MAY TOUCH, and the only list of them: db/fulfillments/
// repo.ts derives its PATCHABLE from these keys rather than spelling a second
// one (ruling 64). `id` is the WHERE key and the audit columns are the
// trigger's, so neither is here.
export const FulfillmentPatch = Fulfillment.pick({
  method_id: true,
  order_id: true,
  status: true,
}).partial();
export type FulfillmentPatch = z.infer<typeof FulfillmentPatch>;

export const FulfillmentSetMethodBody = z.object({
  fulfillment_id: Fulfillment.shape.id,
  method_id: FulfillmentMethod.shape.id,
}).strict();
export type FulfillmentSetMethodBody = z.infer<typeof FulfillmentSetMethodBody>;

export const FulfillmentSetStatusBody = z.object({
  fulfillment_id: Fulfillment.shape.id,
  status: Fulfillment.shape.status,
}).strict();
export type FulfillmentSetStatusBody = z.infer<typeof FulfillmentSetStatusBody>;

export const FulfillmentCancelScheduleBody = z.object({
  fulfillment_id: Fulfillment.shape.id,
}).strict();
export type FulfillmentCancelScheduleBody = z.infer<typeof FulfillmentCancelScheduleBody>;

