// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: fulfillments.fulfillments
import { z } from "zod/v4";

export const Row = z.object({
  "id": z.string().uuid(),
  "method_id": z.string().uuid(),
  "order_id": z.string().uuid().nullable(),
  "status": z.string(),
  "created_by": z.string().nullable(),
  "updated_by": z.string().nullable(),
  "created_at": z.string(),
  "updated_at": z.string(),
  "created_by_id": z.string().uuid().nullable(),
  "updated_by_id": z.string().uuid().nullable(),
});
export type Row = z.infer<typeof Row>;
// generated:end
import * as methods from "./methods.js";

// GET /orders/:orderId/fulfillments - THE BARE ROW, verbatim, and nothing
// else (rulings 9 + 12). No method embed - methods are reference data the
// client maps by method_id off GET /fulfillments/methods - and no resolved
// children: the shipment, pickup and direct reads are their own parent-path
// endpoints.
export const SetMethodBody = z.object({
  fulfillment_id: Row.shape.id,
  method_id: methods.Row.shape.id,
}).strict();
export type SetMethodBody = z.infer<typeof SetMethodBody>;

export const SetStatusBody = z.object({
  fulfillment_id: Row.shape.id,
  status: Row.shape.status,
}).strict();
export type SetStatusBody = z.infer<typeof SetStatusBody>;

export const CancelScheduleBody = z.object({
  fulfillment_id: Row.shape.id,
}).strict();
export type CancelScheduleBody = z.infer<typeof CancelScheduleBody>;

