// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: fulfillments.methods
import { z } from "zod/v4";
import { Category } from "./enums.js";
import { Direction } from "../orders/enums.js";

export const Row = z.object({
  "id": z.string().uuid(),
  "type": z.string(),
  "label": z.string(),
  "direction": Direction.nullable(),
  "enabled": z.boolean(),
  "created_by": z.string().nullable(),
  "updated_by": z.string().nullable(),
  "created_at": z.string(),
  "updated_at": z.string(),
  "category": Category,
  "hidden": z.boolean(),
  "admin_label": z.string().nullable(),
  "is_default": z.boolean(),
  "created_by_id": z.string().uuid().nullable(),
  "updated_by_id": z.string().uuid().nullable(),
});
export type Row = z.infer<typeof Row>;
// generated:end
// The customer-facing menu and the admin list are the same row, minus the
// audit columns nobody outside the API needs.
export const Read = Row.pick({
  id: true,
  type: true,
  label: true,
  admin_label: true,
  category: true,
  direction: true,
  enabled: true,
  hidden: true,
  is_default: true,
  created_at: true,
  updated_at: true,
});
export type Read = z.infer<typeof Read>;

// The four columns an admin may change. `admin_label` refuses null: an empty
// admin label is the empty string, not an absent one.
export const Patch = Row.pick({
  label: true,
  admin_label: true,
  enabled: true,
  hidden: true,
}).extend({
  admin_label: Row.shape.admin_label.unwrap(),
}).partial();
export type Patch = z.infer<typeof Patch>;

