// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: fulfillments.methods
import { z } from "zod/v4";
import { FulfillmentCategory } from "./enums.js";
import { Direction } from "../orders/enums.js";

export const FulfillmentMethod = z.object({
  "id": z.string().uuid(),
  "type": z.string(),
  "label": z.string(),
  "direction": Direction.nullable(),
  "enabled": z.boolean(),
  "created_by": z.string().nullable(),
  "updated_by": z.string().nullable(),
  "created_at": z.string(),
  "updated_at": z.string(),
  "category": FulfillmentCategory,
  "hidden": z.boolean(),
  "admin_label": z.string().nullable(),
  "is_default": z.boolean(),
  "created_by_id": z.string().uuid().nullable(),
  "updated_by_id": z.string().uuid().nullable(),
});
export type FulfillmentMethod = z.infer<typeof FulfillmentMethod>;
// generated:end
// The customer-facing menu and the admin list are the same row, minus the
// audit columns nobody outside the API needs.
export const FulfillmentMethodRead = FulfillmentMethod.pick({
  id: true,
  type: true,
  label: true,
  admin_label: true,
  category: true,
  direction: true,
  enabled: true,
  hidden: true,
  is_default: true,
  created_at: true,
  updated_at: true,
});
export type FulfillmentMethodRead = z.infer<typeof FulfillmentMethodRead>;

// The four columns an admin may change. `admin_label` refuses null: an empty
// admin label is the empty string, not an absent one.
export const FulfillmentMethodPatch = FulfillmentMethod.pick({
  label: true,
  admin_label: true,
  enabled: true,
  hidden: true,
}).extend({
  admin_label: FulfillmentMethod.shape.admin_label.unwrap(),
}).partial();
export type FulfillmentMethodPatch = z.infer<typeof FulfillmentMethodPatch>;

// POST /fulfillments/methods/update - the row named ONCE by id, and the
// columns beside it (ruling 43). The id used to be extended onto the patch
// itself, where it read as a column being written.
export const FulfillmentMethodUpdateBody = z.object({
  id: FulfillmentMethod.shape.id,
  method: FulfillmentMethodPatch.strict(),
}).strict();
export type FulfillmentMethodUpdateBody = z.infer<typeof FulfillmentMethodUpdateBody>;

