// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: fulfillments.pickups
import { z } from "zod/v4";

export const FulfillmentPickup = z.object({
  "id": z.string().uuid(),
  "fulfillment_id": z.string().uuid(),
  "pickup_address_id": z.string().uuid(),
  "assigned_employee_id": z.string().uuid().nullable(),
  "start_time": z.string().nullable(),
  "end_time": z.string().nullable(),
});
export type FulfillmentPickup = z.infer<typeof FulfillmentPickup>;
// generated:end
// POST /fulfillments/schedule_pickup - the booking's own columns, all
// optional; the id is the service's to issue.
export const FulfillmentPickupPatch = FulfillmentPickup.omit({ id: true }).partial();
export type FulfillmentPickupPatch = z.infer<typeof FulfillmentPickupPatch>;

