// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: fulfillments.pickups
import { z } from "zod/v4";

export const FulfillmentPickup = z.object({
  "id": z.string().uuid(),
  "fulfillment_id": z.string().uuid(),
  "pickup_address_id": z.string().uuid().nullable(),
  "assigned_employee_id": z.string().uuid().nullable(),
  "start_time": z.string().nullable(),
  "end_time": z.string().nullable(),
});
export type FulfillmentPickup = z.infer<typeof FulfillmentPickup>;
// generated:end
// The booking's own columns, all optional; the id is the service's to issue.
export const FulfillmentPickupPatch = FulfillmentPickup.omit({ id: true }).partial();
export type FulfillmentPickupPatch = z.infer<typeof FulfillmentPickupPatch>;

// THE COLUMNS db/fulfillments/pickups/repo.ts's update() MAY TOUCH (ruling 64) -
// `fulfillment_id` is the WHERE key, dropped for the same reason the schedule
// body drops it too.
export const FulfillmentPickupPatchColumns = FulfillmentPickupPatch.omit({ fulfillment_id: true });
export type FulfillmentPickupPatchColumns = z.infer<typeof FulfillmentPickupPatchColumns>;

// POST /fulfillments/schedule_pickup - the fulfillment named ONCE, at the top
// level, and the booking beside it (ruling 43). It used to be nested inside
// the patch, where it read as one of the columns being written and had to be
// checked for by hand before the service could look the fulfillment up.
export const FulfillmentSchedulePickupBody = z.object({
  fulfillment_id: FulfillmentPickup.shape.fulfillment_id,
  pickup: FulfillmentPickupPatch.omit({ fulfillment_id: true }).strict(),
}).strict();
export type FulfillmentSchedulePickupBody = z.infer<typeof FulfillmentSchedulePickupBody>;

