// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: fulfillments.pickups
import { z } from "zod/v4";

export const Row = z.object({
  "id": z.string().uuid(),
  "fulfillment_id": z.string().uuid(),
  "pickup_address_id": z.string().uuid(),
  "assigned_employee_id": z.string().uuid().nullable(),
  "start_time": z.string().nullable(),
  "end_time": z.string().nullable(),
});
export type Row = z.infer<typeof Row>;
// generated:end
// POST /fulfillments/schedule_pickup - the booking's own row, minus the id
// the service issues.
export const New = Row.omit({ id: true }).partial({
  assigned_employee_id: true,
  start_time: true,
  end_time: true,
});
export type New = z.infer<typeof New>;

