// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: fulfillments.shipments
import { z } from "zod/v4";

export const FulfillmentShipment = z.object({
  "id": z.string().uuid(),
  "fulfillment_id": z.string().uuid(),
  "recipient_location_id": z.string().uuid().nullable(),
  "shipper_location_id": z.string().uuid().nullable(),
  "shipment_id": z.string().uuid(),
});
export type FulfillmentShipment = z.infer<typeof FulfillmentShipment>;
// generated:end

// Hand-written derivations go here: New, Patch, named reads.

// THE COLUMNS A WRITE MAY TOUCH (ruling 64): `shipment_id` is the link's WHERE
// key and `id` its own, so a patch names neither.
export const FulfillmentShipmentPatch = FulfillmentShipment.omit({
  id: true,
  shipment_id: true,
}).partial();
export type FulfillmentShipmentPatch = z.infer<typeof FulfillmentShipmentPatch>;
