// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: fulfillments.shipments
import { z } from "zod/v4";

export const Row = z.object({
  "id": z.string().uuid(),
  "fulfillment_id": z.string().uuid(),
  "recipient_location_id": z.string().uuid().nullable(),
  "shipper_location_id": z.string().uuid().nullable(),
  "shipment_id": z.string().uuid(),
});
export type Row = z.infer<typeof Row>;
// generated:end

// Hand-written derivations go here: New, Patch, named reads.
