import { Forbidden, Invalid, NotFound } from '#shared/errors.ts'
import { columnsOf } from '#shared/db/columns.ts'
import { CheckoutWrite, WeightUnit } from '@dorado/contracts'
import type {
  Checkout,
  PaymentDetailsView,
  PaymentMethod,
  CheckoutDecisions,
  CheckoutMissing,
  CheckoutScrapLot,
  Lot,
  LotPatch,
  CheckoutViewFacts,
  Direction,
  FulfillmentStep,
} from '@dorado/contracts'

export function assertCatalogueLine(direction: Direction): void {
  if (direction === 'sale') {
    throw new Invalid('a buy basket holds catalogue products - every line needs a bullion_id')
  }
}

export function assertProductAvailable(
  written: Lot | undefined,
  bullion_id: string,
  direction: Direction
): asserts written is Lot {
  if (!written) {
    throw new Invalid(
      direction === 'sale'
        ? `product ${bullion_id} is not available`
        : `no product ${bullion_id} to put in the basket`
    )
  }
}

// The lot's fine content is generated by the database from these weights - one
// definition, one expression, and nothing the caller sends can set it.
export function scrapLot(line: CheckoutScrapLot): LotPatch {
  assertWeighable(line.unit, line.post_melt ?? line.pre_melt, line.purity)
  return {
    metal_id: line.metal_id,
    pre_melt: line.pre_melt,
    post_melt: line.post_melt ?? null,
    purity: line.purity,
    unit: line.unit,
    quantity: line.quantity ?? undefined,
  }
}

export function assertWeighable(
  unit: string | null | undefined,
  weight: number | null | undefined,
  purity: number | null | undefined
): void {
  if (weight === null || weight === undefined) return
  if (purity === null || purity === undefined) return
  if (!WeightUnit.safeParse(typeof unit === 'string' ? unit.toLowerCase() : unit).success) {
    throw new Invalid(
      `a lot weighed in ${unit === null || unit === undefined ? 'no unit' : `"${unit}"`} ` +
        `cannot be valued - the business quotes in ${WeightUnit.options.join(', ')}`
    )
  }
}

// MP F2: `PATCH /api/checkout` took any payment_method_id at all, and both
// quotes read the card surcharge and the payout fee straight off whatever row
// the customer named. A CREDIT method on a card checkout waived the surcharge
// while Stripe still charged the card; DORADO_ACCOUNT on a WIRE payout made
// the business pay the wire fee. The method has to be a real, enabled method of
// this checkout's own direction, and it has to be the method of the payout
// account the checkout already holds.
export function assertSettlementMethod(
  method: PaymentMethod | undefined,
  method_id: string,
  direction: Direction,
  details: Pick<PaymentDetailsView, 'method_id'> | undefined
): void {
  if (!method) throw new NotFound(`no payment method ${method_id}`)
  if (method.direction !== direction) {
    throw new Invalid(
      `payment method ${method.type} settles a ${method.direction} and this is a ${direction}`
    )
  }
  if (!method.enabled) {
    throw new Invalid(`payment method ${method.type} is not accepted`)
  }
  if (details && details.method_id !== null && details.method_id !== method_id) {
    throw new Invalid(
      `payment method ${method.type} is not the method of the payout account this ` +
        `checkout holds`
    )
  }
}

export function checkoutState(
  view: CheckoutViewFacts,
  handover: FulfillmentStep[]
): CheckoutDecisions {
  const missing: CheckoutMissing[] = []
  if (view.lots.length === 0) missing.push('lots')

  if (!view.fulfillment_id) missing.push('fulfillment_id')
  else missing.push(...handover)

  if (view.direction === 'purchase') {
    if (!view.payment_details_id) missing.push('payment_details_id')
  } else if (!view.recipient_address_id) {
    missing.push('recipient_address_id')
  }

  return { missing }
}

export const CHOICE_COLUMNS = columnsOf(CheckoutWrite)

type CheckoutWriteColumns = Partial<Pick<Checkout, (typeof CHOICE_COLUMNS)[number]>>

export function mergeChoices(
  anonymous: CheckoutWriteColumns,
  real: CheckoutWriteColumns
): CheckoutWriteColumns {
  const patch: Record<string, unknown> = {}
  for (const column of CHOICE_COLUMNS) {
    const chosen = anonymous[column] ?? real[column] ?? null
    if (chosen !== (real[column] ?? null)) patch[column] = chosen
  }
  return patch as CheckoutWriteColumns
}

export function assertSession<T>(row: T | null | undefined): asserts row is T {
  if (!row) throw new Error('the checkout session could not be created')
}

export function assertMaySubjectAnother(is_admin: boolean): void {
  if (!is_admin) throw new Forbidden('user_id is admin-only')
}

export function assertSubject(found: boolean, named_user_id: string): void {
  if (!found) throw new NotFound(`no user ${named_user_id}`)
}

export function assertRealAccount(anonymous: boolean, action: string): void {
  if (anonymous) throw new Forbidden(`sign in to ${action}`)
}

export function assertPayoutDirection(direction: Direction): void {
  if (direction !== 'purchase') {
    throw new Invalid('the payout step belongs to the purchase checkout')
  }
}

export function assertRekeyed(rekeyed: boolean, checkout_id: string, user_id: string): void {
  if (!rekeyed) {
    throw new Error(`checkout ${checkout_id} could not be re-keyed to ${user_id}`)
  }
}

export function assertLinesCarried(carried: number, expected: number, checkout_id: string): void {
  if (carried !== expected) {
    throw new Error(`checkout ${checkout_id}: ${expected} line(s) to carry, ${carried} moved`)
  }
}

export function assertVisitorRowGone(
  removed: boolean,
  visitor_id: string,
  survivor_id: string
): void {
  if (!removed) {
    throw new Error(`checkout ${visitor_id} survived the merge onto ${survivor_id}`)
  }
}
