// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: refining.documents
import { z } from 'zod/v4'
import { PdfKind } from '../media/enums.js'

export const RefiningDocument = z.object({
  'id': z.string().uuid(),
  'kind': PdfKind,
  'name': z.string(),
  'renderable': z.boolean(),
  'sort_order': z.number().int(),
  'created_at': z.string(),
  'updated_at': z.string(),
  'created_by_id': z.string().uuid().nullable(),
  'updated_by_id': z.string().uuid().nullable(),
})
export type RefiningDocument = z.infer<typeof RefiningDocument>
// generated:end

// Hand-written derivations go here: New, Patch, named reads.
