// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres enum types owned by the `refining` schema.
import { z } from 'zod/v4'

export const RefiningDirection = z.enum(['sell', 'buy'])
export type RefiningDirection = z.infer<typeof RefiningDirection>

export const SettlementType = z.enum(['paid', 'pooled'])
export type SettlementType = z.infer<typeof SettlementType>
