// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: refining.lots
import { z } from 'zod/v4'

export const RefiningLot = z.object({
  'id': z.string().uuid(),
  'refining_order_id': z.string().uuid(),
  'lot_id': z.string().uuid(),
  'unit': z.string(),
  'pre_melt': z.number().nullable(),
  'post_melt': z.number().nullable(),
  'purity': z.number().nullable(),
  'content': z.number().nullable(),
  'premium': z.number().nullable(),
  'settled_at': z.string().nullable(),
  'created_at': z.string(),
  'updated_at': z.string(),
  'created_by_id': z.string().uuid().nullable(),
  'updated_by_id': z.string().uuid().nullable(),
})
export type RefiningLot = z.infer<typeof RefiningLot>
// generated:end

import { Lot } from '../lots/items.js'

export const RefiningLotPatch = RefiningLot.pick({
  pre_melt: true,
  post_melt: true,
  purity: true,
  unit: true,
  premium: true,
})
  .partial()
  .strict()
export type RefiningLotPatch = z.infer<typeof RefiningLotPatch>

export const RefiningLotsBody = z.object({ lot_ids: z.array(Lot.shape.id).min(1) }).strict()
export type RefiningLotsBody = z.infer<typeof RefiningLotsBody>
