// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: refining.orders
import { z } from 'zod/v4'
import { RefiningDirection } from './enums.js'

export const RefiningOrder = z.object({
  'id': z.string().uuid(),
  'number': z.number().int(),
  'direction': RefiningDirection,
  'refiner_id': z.string().uuid(),
  'assigned_to_id': z.string().uuid().nullable(),
  'sent_at': z.string().nullable(),
  'settled_at': z.string().nullable(),
  'disputed_at': z.string().nullable(),
  'expected_settlement_on': z.string().nullable(),
  'assay_lab': z.string().nullable(),
  'fee': z.number().nullable(),
  'statement_reference': z.string().nullable(),
  'created_at': z.string(),
  'updated_at': z.string(),
  'created_by_id': z.string().uuid().nullable(),
  'updated_by_id': z.string().uuid().nullable(),
  'location_id': z.string().uuid().nullable(),
  'cancelled_at': z.string().nullable(),
})
export type RefiningOrder = z.infer<typeof RefiningOrder>
// generated:end

import { Lot } from '../lots/items.js'
import { RefiningLot, RefiningLotPatch } from './lots.js'

// `lot_ids` is optional and, when named, the create and the assignment are one
// transaction - a failure after the insert used to leave an empty refiner order
// behind.
export const RefiningOrderCreate = RefiningOrder.pick({
  refiner_id: true,
  direction: true,
})
  .extend({ lot_ids: z.array(Lot.shape.id).min(1).optional() })
  .strict()
export type RefiningOrderCreate = z.infer<typeof RefiningOrderCreate>

export const RefiningOrderPatch = RefiningOrder.pick({
  refiner_id: true,
  assigned_to_id: true,
  location_id: true,
  fee: true,
  statement_reference: true,
  assay_lab: true,
  expected_settlement_on: true,
  disputed_at: true,
})
  .partial()
  .strict()
export type RefiningOrderPatch = z.infer<typeof RefiningOrderPatch>

export const RefiningSettlementLot = RefiningLotPatch.extend({
  lot_id: RefiningLot.shape.lot_id,
}).strict()
export type RefiningSettlementLot = z.infer<typeof RefiningSettlementLot>

export const RefiningSettlement = RefiningOrder.pick({
  fee: true,
  statement_reference: true,
})
  .extend({ lots: z.array(RefiningSettlementLot) })
  .partial({ fee: true, statement_reference: true })
  .strict()
export type RefiningSettlement = z.infer<typeof RefiningSettlement>

export const RefiningSupply = RefiningOrder.pick({ refiner_id: true }).strict()
export type RefiningSupply = z.infer<typeof RefiningSupply>
