// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: refining.pool
import { z } from 'zod/v4'
import { PoolEntryKind } from './enums.js'

export const PoolEntry = z.object({
  'id': z.string().uuid(),
  'refiner_id': z.string().uuid(),
  'metal_id': z.string(),
  'entry': PoolEntryKind,
  'troy_oz': z.number(),
  'lock_price': z.number().nullable(),
  'refining_order_id': z.string().uuid(),
  'occurred_at': z.string(),
  'created_at': z.string(),
  'created_by_id': z.string().uuid().nullable(),
})
export type PoolEntry = z.infer<typeof PoolEntry>
// generated:end

export const PoolLockCreate = PoolEntry.pick({
  refiner_id: true,
  metal_id: true,
  troy_oz: true,
  lock_price: true,
  refining_order_id: true,
})
  .extend({ lock_price: PoolEntry.shape.lock_price.unwrap() })
  .strict()
export type PoolLockCreate = z.infer<typeof PoolLockCreate>

// The balance is sum(troy_oz), never a column somebody keeps correct. It may be
// negative - metal taken before it settled is a real business state - and the
// view reports the sign rather than the write refusing.
export const PoolBalance = PoolEntry.pick({ refiner_id: true, metal_id: true }).extend({
  troy_oz: PoolEntry.shape.troy_oz,
  last_lock_price: PoolEntry.shape.lock_price,
})
export type PoolBalance = z.infer<typeof PoolBalance>
