// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: products.bullion
import { z } from "zod/v4";

export const Row = z.object({
  "id": z.string().uuid(),
  "metal_id": z.string().uuid(),
  "mint_id": z.string().uuid(),
  "name": z.string(),
  "description": z.string(),
  "bid_premium": z.number(),
  "ask_premium": z.number(),
  "type": z.string(),
  "display": z.boolean(),
  "homepage_display": z.boolean(),
  "legal_tender": z.boolean(),
  "domestic_tender": z.boolean(),
  "is_generic": z.boolean(),
  "content": z.number(),
  "gross": z.number(),
  "purity": z.number(),
  "variant_group": z.string(),
  "variant_label": z.string(),
  "shadow_offset": z.number().int(),
  "slug": z.string().nullable(),
  "filter_category": z.string().nullable(),
  "image_front": z.string(),
  "image_back": z.string(),
  "created_by": z.string(),
  "updated_by": z.string(),
  "created_at": z.string(),
  "updated_at": z.string(),
  "created_by_id": z.string().uuid().nullable(),
  "updated_by_id": z.string().uuid().nullable(),
  "supplier_id": z.string().uuid(),
  "stock": z.number(),
  "quantity": z.number(),
});
export type Row = z.infer<typeof Row>;
// generated:end
// THE CATALOGUE ROW BEHIND A BULLION LINE - the PUBLIC columns, which is
// exactly what db/products/sql/get_by_ids.sql projects. Stock, display flags,
// the supplier and the audit columns are not facts about an order line and do
// not travel with one.
export const Public = Row.pick({
  id: true, name: true, description: true, content: true, purity: true,
  gross: true, bid_premium: true, ask_premium: true, type: true,
  image_front: true, image_back: true, variant_group: true,
  shadow_offset: true, slug: true, legal_tender: true, domestic_tender: true,
  is_generic: true, variant_label: true, metal_id: true, mint_id: true,
});
export type Public = z.infer<typeof Public>;

// POST /products/save_product - the id of an EXISTING product plus every
// writable column, full-replace (an absent field is not "unchanged": the admin
// form always sends the whole product back). Audit columns are omitted -
// public.audit_stamp writes them.
//
// metal_id/supplier_id/mint_id travel as IDS, not names (ruling 43). The body
// used to carry "Silver"/"APMEX"/"U.S. Mint" and the service resolved each
// with an in-memory name lookup. Booleans are real booleans - zod refuses the
// string "true" the old bespoke flag() coercion accepted.
export const Patch = Row.omit({
  created_by: true,
  updated_by: true,
  created_at: true,
  updated_at: true,
  created_by_id: true,
  updated_by_id: true,
});
export type Patch = z.infer<typeof Patch>;

// POST /products/create_product - a bare name; every other column is filled
// server-side from the create defaults.
export const New = Row.pick({ name: true });
export type New = z.infer<typeof New>;


import * as metals from "../metals/metals.js";
import * as mints from "./mints.js";

// THE STOREFRONT ROW - the public projection, plus the two labels the read
// attaches in JS. db/products/sql/get_storefront.sql projects exactly `Public`
// (its own comment: "anyone on the internet reads this, so no display, stock,
// created_by, timestamps, filter_category or quantity"), carries metal_id and
// mint_id only to resolve them, and drops both.
//
// The two extends are the join, and they are what a later products read pivot
// removes: a client that holds /metals and /mints maps the ids itself.
export const Storefront = Public.omit({ metal_id: true, mint_id: true }).extend({
  metal_type: metals.Row.shape.name,
  mint_name: mints.Row.shape.name,
});
export type Storefront = z.infer<typeof Storefront>;
