// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: products.mints
import { z } from "zod/v4";

export const Row = z.object({
  "id": z.string().uuid(),
  "name": z.string(),
  "type": z.string(),
  "country": z.string().nullable(),
  "created_at": z.string().nullable(),
  "updated_at": z.string().nullable(),
  "image_id": z.string().uuid().nullable(),
  "organization_id": z.string().uuid(),
});
export type Row = z.infer<typeof Row>;
// generated:end

// Hand-written derivations go here: New, Patch, named reads.
