// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres enum types owned by the `auth` schema.
import { z } from 'zod/v4'

export const Factor = z.enum(['email', 'phone'])
export type Factor = z.infer<typeof Factor>

export const OtpChannel = z.enum(['sms', 'email'])
export type OtpChannel = z.infer<typeof OtpChannel>

export const ThrottleKind = z.enum(['phone', 'email', 'ip'])
export type ThrottleKind = z.infer<typeof ThrottleKind>
