// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: auth.otp_throttles
import { z } from 'zod/v4'
import { ThrottleKind } from './enums.js'

export const AuthOtpThrottle = z.object({
  'id': z.string().uuid(),
  'subject': z.string(),
  'kind': ThrottleKind,
  'sends': z.number().int(),
  'window_started_at': z.string().nullable(),
  'attempts': z.number().int(),
  'locked_until': z.string().nullable(),
  'last_sent_at': z.string().nullable(),
  'created_at': z.string(),
  'updated_at': z.string(),
  'created_by_id': z.string().uuid().nullable(),
  'updated_by_id': z.string().uuid().nullable(),
})
export type AuthOtpThrottle = z.infer<typeof AuthOtpThrottle>
// generated:end

// Hand-written derivations go here: New, Patch, named reads.
