// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: auth.pending_signups
import { z } from 'zod/v4'

export const AuthPendingSignup = z.object({
  'id': z.string().uuid(),
  'phone_number': z.string().nullable(),
  'email': z.string(),
  'name': z.string(),
  'expires_at': z.string(),
  'created_at': z.string(),
  'updated_at': z.string(),
  'created_by_id': z.string().uuid().nullable(),
  'updated_by_id': z.string().uuid().nullable(),
})
export type AuthPendingSignup = z.infer<typeof AuthPendingSignup>
// generated:end
