// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: auth.pending_changes
import { z } from 'zod/v4'
import { Factor, OtpChannel } from './enums.js'

export const AuthPendingChange = z.object({
  'id': z.string().uuid(),
  'user_id': z.string().uuid(),
  'factor': Factor,
  'next_value': z.string(),
  'verified_via': OtpChannel,
  'sent_to': z.string(),
  'expires_at': z.string(),
  'confirmed_at': z.string().nullable(),
  'created_at': z.string(),
  'updated_at': z.string(),
  'created_by_id': z.string().uuid().nullable(),
  'updated_by_id': z.string().uuid().nullable(),
})
export type AuthPendingChange = z.infer<typeof AuthPendingChange>
// generated:end
