// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: auth.users
import { z } from "zod/v4";

export const Row = z.object({
  "id": z.string().uuid(),
  "email": z.string(),
  "name": z.string().nullable(),
  "createdAt": z.string(),
  "updatedAt": z.string(),
  "emailVerified": z.boolean(),
  "image": z.string().nullable(),
  "role": z.string().nullable(),
  "stripeCustomerId": z.string().nullable(),
  "dorado_funds": z.number(),
  "banned": z.boolean().nullable(),
  "banReason": z.string().nullable(),
  "banExpires": z.string().nullable(),
  "phone_number": z.string().nullable(),
});
export type Row = z.infer<typeof Row>;
// generated:end
// WHO AN ORDER IS FOR: three columns of auth.users, the authoritative
// identity row since the 2026-09-01 cutover.
export const Summary = Row.pick({ id: true, name: true, email: true });
export type Summary = z.infer<typeof Summary>;

// POST /users/update_credit - the admin balance edit. `amount` matches
// auth.users.dorado_funds's own type: a magnitude, never a signed delta -
// the sign is `op`.
export const CreditOp = z.enum(["add", "subtract", "edit"]);
export type CreditOp = z.infer<typeof CreditOp>;

export const CreditBody = z.object({
  user_id: Row.shape.id,
  op: CreditOp,
  amount: Row.shape.dorado_funds,
}).strict();
export type CreditBody = z.infer<typeof CreditBody>;

