// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Every entity of the `metals` schema, one namespace each.
export * as metals from "./metals.js";
