// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: metals.metals
import { z } from 'zod/v4'

export const Metal = z.object({
  'id': z.string(),
})
export type Metal = z.infer<typeof Metal>
// generated:end

// The weight vocabulary the business quotes in. `metals.fine_content` in SQL
// is the one definition of what each label converts to; these are the labels
// it knows, and a lot carrying anything else is refused before it is written
// rather than valued at nothing (MA F4).
export const WeightUnit = z.enum(['t oz', 'g', 'dwt', 'lb'])
export type WeightUnit = z.infer<typeof WeightUnit>
