// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: metals.metals
import { z } from 'zod/v4'

export const Metal = z.object({
  'id': z.string(),
})
export type Metal = z.infer<typeof Metal>
// generated:end
