// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: metals.purity_labels
import { z } from 'zod/v4'

export const PurityLabel = z.object({
  'id': z.string().uuid(),
  'metal_id': z.string(),
  'label': z.string(),
  'purity': z.number(),
  'sort_order': z.number().int(),
  'created_at': z.string(),
  'updated_at': z.string(),
  'created_by_id': z.string().uuid().nullable(),
  'updated_by_id': z.string().uuid().nullable(),
  'tolerance': z.number(),
})
export type PurityLabel = z.infer<typeof PurityLabel>
// generated:end

// Hand-written derivations go here: New, Patch, named reads.
