// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: media.emails
import { z } from "zod/v4";
import { EmailKind, EmailStatus } from "./enums.js";

export const Row = z.object({
  "id": z.string().uuid(),
  "kind": EmailKind,
  "status": EmailStatus,
  "to_address": z.string(),
  "subject": z.string().nullable(),
  "order_id": z.string().uuid().nullable(),
  "user_id": z.string().uuid().nullable(),
  "pdf_id": z.string().uuid().nullable(),
  "provider_message_id": z.string().nullable(),
  "error": z.string().nullable(),
  "sent_at": z.string(),
});
export type Row = z.infer<typeof Row>;
// generated:end
import * as orders from "../orders/orders.js";

// POST /media/emails/send_created and /send_priced - the order id alone
// (ruling 10). Everything else is resolved server-side from it.
export const SendBody = z.object({ order_id: orders.Row.shape.id }).strict();
export type SendBody = z.infer<typeof SendBody>;

