// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: media.images
import { z } from "zod/v4";

export const Row = z.object({
  "id": z.string().uuid(),
  "bucket": z.string(),
  "mime_type": z.string(),
  "size_bytes": z.number().int().nullable(),
  "width": z.number().int().nullable(),
  "height": z.number().int().nullable(),
  "checksum": z.string().nullable(),
  "metadata": z.unknown().nullable(),
  "path": z.string(),
  "filename": z.string(),
  "user_id": z.string().uuid().nullable(),
  "created_at": z.string(),
});
export type Row = z.infer<typeof Row>;
// generated:end
// POST /media/images/upload - a presigned-PUT request. The server names the
// object; `filename` survives only as a sanitised suffix and `path` is not
// accepted at all - it was accepted and silently ignored.
export const UploadBody = Row.pick({
  mime_type: true,
  size_bytes: true,
  filename: true,
}).extend({
  mime_type: Row.shape.mime_type.nullable().optional(),
  size_bytes: Row.shape.size_bytes.optional(),
});
export type UploadBody = z.infer<typeof UploadBody>;

// DELETE /media/images/delete - the id alone; ownership is the session's.
export const DeleteBody = Row.pick({ id: true });
export type DeleteBody = z.infer<typeof DeleteBody>;

