// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: places.addresses
import { z } from "zod/v4";

export const Address = z.object({
  "id": z.string().uuid(),
  "line_1": z.string().nullable(),
  "line_2": z.string().nullable(),
  "city": z.string().nullable(),
  "state": z.string().nullable(),
  "country": z.string().nullable(),
  "zip": z.string().nullable(),
  "country_code": z.string().nullable(),
  "phone_number": z.string().nullable(),
  "created_at": z.string(),
  "updated_at": z.string(),
  "is_valid": z.boolean().nullable(),
  "is_residential": z.boolean(),
});
export type Address = z.infer<typeof Address>;
// generated:end
import { UserAddressPatch } from "./user_addresses.js";
import { User } from "../auth/users.js";

// The postal fields a caller may write. is_valid/is_residential are NOT here:
// create.sql hard-codes them and validation sets the real values through its
// own write, so a body naming either is a 400 rather than a value quietly
// overwritten server-side.
//
// A CREATE TAKES THE SAME PATCH (Jacob, 2026-09-03: "For new, it can just send
// the patch!!"). There is no second type: the database's NOT NULL columns and
// defaults decide what a create needs, and a missing one surfaces as the shared
// pg-error translation naming the column.
export const AddressPatch = Address.pick({
  line_1: true,
  line_2: true,
  city: true,
  state: true,
  country: true,
  zip: true,
  country_code: true,
  phone_number: true,
}).partial();
export type AddressPatch = z.infer<typeof AddressPatch>;

// `user_id` is an ID for what the server holds (ruling 43): an admin naming
// another customer's book. A non-admin caller sending one is overridden by
// the session.
export const AddressCreateBody = z.object({
  address: AddressPatch.strict(),
  user_address: UserAddressPatch.optional(),
  user_id: User.shape.id.optional(),
}).strict();
export type AddressCreateBody = z.infer<typeof AddressCreateBody>;

export const AddressUpdateBody = z.object({
  address: AddressPatch.extend({ id: Address.shape.id }).strict(),
  user_address: UserAddressPatch.optional(),
  user_id: User.shape.id.optional(),
}).strict();
export type AddressUpdateBody = z.infer<typeof AddressUpdateBody>;

// DELETE /places/addresses/delete and POST /set_default - the id alone.
export const AddressIdBody = z.object({
  address_id: Address.shape.id,
  user_id: User.shape.id.optional(),
}).strict();
export type AddressIdBody = z.infer<typeof AddressIdBody>;

