// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: places.user_addresses
import { z } from "zod/v4";

export const UserAddress = z.object({
  "id": z.string().uuid(),
  "address_id": z.string().uuid(),
  "user_id": z.string().uuid(),
  "label": z.string().nullable(),
  "default_shipping": z.boolean(),
  "default_billing": z.boolean(),
});
export type UserAddress = z.infer<typeof UserAddress>;
// generated:end
// One person's relationship to one address - ITS OWN read, never nested
// inside the address; the client joins the two lists by address_id.
export const UserAddressRead = UserAddress.omit({ id: true, default_billing: true }).extend({
  user_id: UserAddress.shape.user_id.nullable(),
  default_shipping: UserAddress.shape.default_shipping.nullable(),
});
export type UserAddressRead = z.infer<typeof UserAddressRead>;

// The relationship beside the address: genuinely new data (a label) plus one
// flag, never an id the caller could instead have sent (ruling 43).
export const UserAddressPatch = UserAddress.pick({
  label: true,
  default_shipping: true,
}).partial().strict();
export type UserAddressPatch = z.infer<typeof UserAddressPatch>;

