// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: places.user_addresses
import { z } from "zod/v4";

export const Row = z.object({
  "id": z.string().uuid(),
  "address_id": z.string().uuid(),
  "user_id": z.string().uuid(),
  "label": z.string().nullable(),
  "default_shipping": z.boolean(),
  "default_billing": z.boolean(),
});
export type Row = z.infer<typeof Row>;
// generated:end
// One person's relationship to one address - ITS OWN read, never nested
// inside the address; the client joins the two lists by address_id.
export const Read = Row.omit({ id: true, default_billing: true }).extend({
  user_id: Row.shape.user_id.nullable(),
  default_shipping: Row.shape.default_shipping.nullable(),
});
export type Read = z.infer<typeof Read>;

// The relationship beside the address: genuinely new data (a label) plus one
// flag, never an id the caller could instead have sent (ruling 43).
export const Write = Row.pick({ label: true })
  .extend({ default_shipping: Row.shape.default_shipping.optional() })
  .partial({ label: true })
  .strict();
export type Write = z.infer<typeof Write>;

