// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: exchange.account_transactions
import { z } from "zod/v4";

export const Row = z.object({
  "id": z.string().uuid(),
  "user_id": z.string().uuid(),
  "transaction_type": z.string(),
  "purchase_order_id": z.string().uuid().nullable(),
  "sales_order_id": z.string().uuid().nullable(),
  "amount": z.number(),
  "occurred_at": z.string(),
  "created_at": z.string(),
  "updated_at": z.string(),
});
export type Row = z.infer<typeof Row>;
// generated:end

// Hand-written derivations go here: New, Patch, named reads.
