// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: exchange.addresses
import { z } from "zod/v4";

export const Row = z.object({
  "id": z.string().uuid(),
  "user_id": z.string().uuid().nullable(),
  "line_1": z.string().nullable(),
  "line_2": z.string().nullable(),
  "city": z.string().nullable(),
  "state": z.string().nullable(),
  "country": z.string().nullable(),
  "zip": z.string().nullable(),
  "created_at": z.string().nullable(),
  "updated_at": z.string().nullable(),
  "name": z.string().nullable(),
  "is_default": z.boolean().nullable(),
  "phone_number": z.string().nullable(),
  "is_valid": z.boolean().nullable(),
  "country_code": z.string().nullable(),
  "is_residential": z.boolean().nullable(),
});
export type Row = z.infer<typeof Row>;
// generated:end

// Hand-written derivations go here: New, Patch, named reads.
