// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: exchange.auctions
import { z } from "zod/v4";

export const Row = z.object({
  "id": z.string().uuid(),
  "status": z.string(),
  "scheduled_date": z.string().nullable(),
  "number": z.number().int(),
  "created_by": z.string().uuid().nullable(),
  "updated_by": z.string().uuid().nullable(),
  "created_at": z.string(),
  "updated_at": z.string(),
  "current_item_id": z.string().uuid().nullable(),
});
export type Row = z.infer<typeof Row>;
// generated:end

// Hand-written derivations go here: New, Patch, named reads.
