// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: exchange.auction_items
import { z } from "zod/v4";

export const Row = z.object({
  "id": z.string().uuid(),
  "bullion_id": z.string().uuid(),
  "auction_id": z.string().uuid(),
  "number": z.number().int(),
  "buyer_email": z.string().nullable(),
  "buyer_name": z.string().nullable(),
  "sold": z.boolean(),
  "starting_bid": z.number().nullable(),
  "ending_bid": z.number().nullable(),
  "quantity": z.number().nullable(),
});
export type Row = z.infer<typeof Row>;
// generated:end

// Hand-written derivations go here: New, Patch, named reads.
