// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: exchange.carriers
import { z } from "zod/v4";

export const Row = z.object({
  "id": z.string().uuid(),
  "name": z.string(),
  "email": z.string().nullable(),
  "phone": z.string().nullable(),
  "logo": z.string().nullable(),
  "is_active": z.boolean(),
  "created_at": z.string(),
  "updated_at": z.string(),
});
export type Row = z.infer<typeof Row>;
// generated:end

// Hand-written derivations go here: New, Patch, named reads.
