// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: exchange.carrier_pickups
import { z } from "zod/v4";

export const Row = z.object({
  "id": z.string().uuid(),
  "user_id": z.string().uuid().nullable(),
  "order_id": z.string().uuid().nullable(),
  "carrier": z.string(),
  "pickup_requested_at": z.string().nullable(),
  "pickup_status": z.string(),
  "confirmation_number": z.number().nullable(),
  "location": z.string().nullable(),
});
export type Row = z.infer<typeof Row>;
// generated:end

// Hand-written derivations go here: New, Patch, named reads.
