// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: exchange.carrier_services
import { z } from "zod/v4";

export const Row = z.object({
  "id": z.string().uuid(),
  "carrier_id": z.string().uuid(),
  "name": z.string(),
  "description": z.string().nullable(),
  "code": z.string().nullable(),
  "provider_code": z.string().nullable(),
  "supports_pickup": z.boolean().nullable(),
  "supports_dropoff": z.boolean().nullable(),
  "supports_returns": z.boolean().nullable(),
  "max_weight_lbs": z.number().nullable(),
  "max_length_in": z.number().nullable(),
  "max_width_in": z.number().nullable(),
  "max_height_in": z.number().nullable(),
  "supports_insurance": z.boolean().nullable(),
  "max_declared_value": z.number().nullable(),
  "is_international": z.boolean().nullable(),
  "is_residential": z.boolean().nullable(),
  "is_active": z.boolean().nullable(),
  "display_order": z.number().int().nullable(),
  "created_by": z.string().nullable(),
  "updated_by": z.string().nullable(),
  "created_at": z.string().nullable(),
  "updated_at": z.string().nullable(),
  "min_transit_days": z.number().nullable(),
  "max_transit_days": z.number().nullable(),
});
export type Row = z.infer<typeof Row>;
// generated:end

// Hand-written derivations go here: New, Patch, named reads.
