// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: exchange.gems
import { z } from "zod/v4";

export const Row = z.object({
  "id": z.string().uuid(),
  "cut": z.string(),
  "clarity": z.string(),
  "color": z.string(),
  "carat": z.number(),
});
export type Row = z.infer<typeof Row>;
// generated:end

// Hand-written derivations go here: New, Patch, named reads.
