// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: exchange.images
import { z } from "zod/v4";

export const Row = z.object({
  "id": z.string().uuid(),
  "user_id": z.string().uuid().nullable(),
  "bucket": z.string(),
  "mime_type": z.string().nullable(),
  "size_bytes": z.number().int().nullable(),
  "width": z.number().int().nullable(),
  "height": z.number().int().nullable(),
  "checksum_sha256": z.string().nullable(),
  "metadata": z.unknown().nullable(),
  "created_at": z.string(),
  "path": z.string().nullable(),
  "filename": z.string().nullable(),
});
export type Row = z.infer<typeof Row>;
// generated:end

// Hand-written derivations go here: New, Patch, named reads.
