// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: exchange.leads
import { z } from "zod/v4";

export const Row = z.object({
  "id": z.string().uuid(),
  "name": z.string(),
  "phone": z.string().nullable(),
  "email": z.string().nullable(),
  "created_at": z.string(),
  "updated_at": z.string(),
  "last_contacted": z.string().nullable(),
  "converted": z.boolean(),
  "contacted": z.boolean(),
  "responded": z.boolean(),
  "created_by": z.string().nullable(),
  "updated_by": z.string().nullable(),
  "notes": z.string().nullable(),
  "contact": z.string().nullable(),
  "priority": z.string(),
});
export type Row = z.infer<typeof Row>;
// generated:end

// Hand-written derivations go here: New, Patch, named reads.
