// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: exchange.payment_intents
import { z } from "zod/v4";

export const Row = z.object({
  "id": z.string().uuid(),
  "session_id": z.string().uuid().nullable(),
  "user_id": z.string().uuid().nullable(),
  "type": z.string(),
  "payment_intent_id": z.string(),
  "created_at": z.string(),
  "updated_at": z.string(),
  "payment_status": z.string().nullable(),
  "sales_order_id": z.string().uuid().nullable(),
  "purchase_order_id": z.string().uuid().nullable(),
  "method_id": z.string().nullable(),
  "method_type": z.string().nullable(),
  "routing": z.string().nullable(),
  "last_four": z.string().nullable(),
  "card_brand": z.string().nullable(),
  "bank_name": z.string().nullable(),
  "bank_account_type": z.string().nullable(),
  "amount": z.number().nullable(),
  "amount_received": z.number().nullable(),
  "amount_capturable": z.number().nullable(),
});
export type Row = z.infer<typeof Row>;
// generated:end

// Hand-written derivations go here: New, Patch, named reads.
