// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: exchange.payouts
import { z } from "zod/v4";

export const Row = z.object({
  "id": z.string().uuid(),
  "user_id": z.string().uuid().nullable(),
  "order_id": z.string().uuid().nullable(),
  "method": z.string(),
  "account_holder_name": z.string(),
  "bank_name": z.string().nullable(),
  "account_type": z.string().nullable(),
  "routing_number": z.string().nullable(),
  "account_number": z.string().nullable(),
  "created_at": z.string().nullable(),
  "email_to": z.string().nullable(),
  "cost": z.number().nullable(),
});
export type Row = z.infer<typeof Row>;
// generated:end
// GET /orders/:orderId/payouts - the payouts of one order.
//
// RULING 12'S ONE DEVIATION CLASS IS SECURITY, and this is it: routing and
// account numbers are absent by design and only the last four travel. They
// are not columns of the statement behind this shape at all, so nothing on
// this path can leak one.
export const Read = Row.omit({
  routing_number: true,
  account_number: true,
}).extend({
  account_last4: Row.shape.account_number,
  routing_last4: Row.shape.routing_number,
});
export type Read = z.infer<typeof Read>;

// GET /payouts/:id/details, admin only - the ONE read allowed to carry the
// full bank numbers, fetched one payout at a time by someone about to execute
// a transfer. It is the payout read plus the two sealed values opened onto it.
export const Details = Read.extend({
  routing_number: Row.shape.routing_number,
  account_number: Row.shape.account_number,
});
export type Details = z.infer<typeof Details>;

// The payout as it hangs off ONE order's view. `created_at` is dropped: when
// a customer saved their bank account is not a fact about this order.
// `method` and `account_holder_name` widen to nullable here and nowhere
// else - the order-scoped read reaches the method through a LEFT JOIN, so a
// payout account saved before a method existed carries neither.
export const OrderView = Read.omit({ created_at: true }).extend({
  method: Row.shape.method.nullable(),
  account_holder_name: Row.shape.account_holder_name.nullable(),
});
export type OrderView = z.infer<typeof OrderView>;

// PATCH /api/payouts/:id - the payout's own writable facts, never the bank
// details, which have their own admin-only read and no write surface at all.
//
// `cost` IS THE PER-ORDER FEE. `waive_payout_fee` is the other half and
// does NOT overwrite it (D117: a stored fee is a record and must never be
// re-derived) - waiving sets the flag on orders.transactions and the stored
// fee keeps what it would have been.
export const Patch = Row.pick({ cost: true, method: true })
  .extend({
    cost: Row.shape.cost.unwrap().optional(),
    method: Row.shape.method.optional(),
    waive_payout_fee: z.boolean().optional(),
  })
  .strict();
export type Patch = z.infer<typeof Patch>;

