// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: exchange.products
import { z } from "zod/v4";

export const Row = z.object({
  "id": z.string().uuid(),
  "metal_id": z.string().uuid(),
  "supplier_id": z.string().uuid(),
  "product_name": z.string(),
  "product_description": z.string(),
  "bid_premium": z.number(),
  "ask_premium": z.number(),
  "product_type": z.string(),
  "created_at": z.string(),
  "updated_at": z.string(),
  "image_front": z.string(),
  "image_back": z.string(),
  "display": z.boolean(),
  "content": z.number(),
  "gross": z.number(),
  "purity": z.number(),
  "mint_id": z.string().uuid(),
  "variant_group": z.string(),
  "shadow_offset": z.number().int(),
  "stock": z.number(),
  "created_by": z.string(),
  "updated_by": z.string(),
  "homepage_display": z.boolean().nullable(),
  "filter_category": z.string().nullable(),
  "quantity": z.number(),
  "slug": z.string().nullable(),
  "legal_tender": z.boolean().nullable(),
  "domestic_tender": z.boolean().nullable(),
  "sell_display": z.boolean(),
  "is_generic": z.boolean().nullable(),
  "variant_label": z.string().nullable(),
});
export type Row = z.infer<typeof Row>;
// generated:end

// Hand-written derivations go here: New, Patch, named reads.
