// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: exchange.purchase_order_items
import { z } from "zod/v4";

export const Row = z.object({
  "id": z.string().uuid(),
  "purchase_order_id": z.string().uuid().nullable(),
  "scrap_id": z.string().uuid().nullable(),
  "price": z.number().nullable(),
  "product_id": z.string().uuid().nullable(),
  "quantity": z.number().nullable(),
  "confirmed": z.boolean(),
  "premium": z.number().nullable(),
  "refiner_premium": z.number().nullable(),
});
export type Row = z.infer<typeof Row>;
// generated:end

// Hand-written derivations go here: New, Patch, named reads.
