// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: exchange.purchase_orders
import { z } from "zod/v4";

export const Row = z.object({
  "id": z.string().uuid(),
  "user_id": z.string().uuid().nullable(),
  "address_id": z.string().uuid().nullable(),
  "purchase_order_status": z.string().nullable(),
  "notes": z.string().nullable(),
  "created_at": z.string().nullable(),
  "updated_at": z.string().nullable(),
  "created_by": z.string().nullable(),
  "updated_by": z.string().nullable(),
  "order_number": z.number().int(),
  "spots_locked": z.boolean().nullable(),
  "total_price": z.number().nullable(),
  "waive_shipping_fee": z.boolean().nullable(),
  "waive_payout_fee": z.boolean().nullable(),
  "shipping_paid": z.boolean().nullable(),
  "review_created": z.boolean().nullable(),
  "shipping_fee_actual": z.number().nullable(),
  "refiner_fee": z.number().nullable(),
  "pool_remediation": z.number().nullable(),
  "pool_oz_deducted": z.number().nullable(),
});
export type Row = z.infer<typeof Row>;
// generated:end

// Hand-written derivations go here: New, Patch, named reads.
