// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: exchange.rates
import { z } from "zod/v4";

export const Row = z.object({
  "id": z.string().uuid(),
  "metal_id": z.string().uuid(),
  "unit": z.string(),
  "min_qty": z.number(),
  "max_qty": z.number().nullable(),
  "scrap_pct": z.number(),
  "bullion_pct": z.number(),
  "created_at": z.string(),
  "updated_at": z.string(),
  "created_by": z.string(),
  "updated_by": z.string(),
});
export type Row = z.infer<typeof Row>;
// generated:end

// Hand-written derivations go here: New, Patch, named reads.
