// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: exchange.refiner_metals
import { z } from "zod/v4";

export const Row = z.object({
  "id": z.string().uuid(),
  "purchase_order_id": z.string().uuid().nullable(),
  "sales_order_id": z.string().uuid().nullable(),
  "type": z.string(),
  "ask_spot": z.number().nullable(),
  "bid_spot": z.number().nullable(),
  "percent_change": z.number().nullable(),
  "dollar_change": z.number().nullable(),
  "scrap_percentage": z.number().nullable(),
  "created_at": z.string().nullable(),
  "updated_at": z.string().nullable(),
  "bullion_percentage": z.number().nullable(),
});
export type Row = z.infer<typeof Row>;
// generated:end

// Hand-written derivations go here: New, Patch, named reads.
