// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: exchange.reviews
import { z } from "zod/v4";

export const Row = z.object({
  "id": z.string().uuid(),
  "review_text": z.string().nullable(),
  "created_at": z.string().nullable(),
  "updated_at": z.string().nullable(),
  "rating": z.number().nullable(),
  "created_by": z.string().nullable(),
  "updated_by": z.string().nullable(),
  "name": z.string().nullable(),
  "hidden": z.boolean().nullable(),
});
export type Row = z.infer<typeof Row>;
// generated:end

// Hand-written derivations go here: New, Patch, named reads.
