// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: exchange.sales_orders
import { z } from "zod/v4";

export const Row = z.object({
  "id": z.string().uuid(),
  "user_id": z.string().uuid().nullable(),
  "address_id": z.string().uuid().nullable(),
  "sales_order_status": z.string(),
  "notes": z.string().nullable(),
  "created_at": z.string().nullable(),
  "updated_at": z.string().nullable(),
  "created_by": z.string().nullable(),
  "updated_by": z.string().nullable(),
  "order_number": z.number().int(),
  "order_total": z.number(),
  "review_created": z.boolean().nullable(),
  "shipping_service": z.string().nullable(),
  "shipping_cost": z.number(),
  "pre_charges_amount": z.number(),
  "post_charges_amount": z.number(),
  "subject_to_charges_amount": z.number(),
  "used_funds": z.boolean(),
  "item_total": z.number(),
  "base_total": z.number(),
  "charges_amount": z.number(),
  "order_sent": z.boolean().nullable(),
  "tracking_updated": z.boolean().nullable(),
  "sales_tax": z.number(),
  "supplier_id": z.string().uuid().nullable(),
});
export type Row = z.infer<typeof Row>;
// generated:end

// Hand-written derivations go here: New, Patch, named reads.
