// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: exchange.sales_order_items
import { z } from "zod/v4";

export const Row = z.object({
  "id": z.string().uuid(),
  "sales_order_id": z.string().uuid().nullable(),
  "product_id": z.string().uuid().nullable(),
  "price": z.number().nullable(),
  "quantity": z.number().nullable(),
  "premium": z.number().nullable(),
  "sales_tax_rate": z.number(),
});
export type Row = z.infer<typeof Row>;
// generated:end

// Hand-written derivations go here: New, Patch, named reads.
