// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: exchange.schema_migrations
import { z } from "zod/v4";

export const Row = z.object({
  "name": z.string(),
  "checksum": z.string(),
  "applied_at": z.string(),
});
export type Row = z.infer<typeof Row>;
// generated:end

// Hand-written derivations go here: New, Patch, named reads.
