// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: exchange.scrap
import { z } from "zod/v4";

export const Row = z.object({
  "id": z.string().uuid(),
  "metal_id": z.string().uuid().nullable(),
  "gem_id": z.string().uuid().nullable(),
  "pre_melt": z.number().nullable(),
  "purity": z.number().nullable(),
  "content": z.number().nullable(),
  "gross_unit": z.string().nullable(),
  "post_melt": z.number().nullable(),
  "bid_premium": z.number().nullable(),
  "purity_actual": z.number().nullable(),
  "post_melt_actual": z.number().nullable(),
  "content_actual": z.number().nullable(),
});
export type Row = z.infer<typeof Row>;
// generated:end

// Hand-written derivations go here: New, Patch, named reads.
