// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: exchange.sell_cart_items
import { z } from "zod/v4";

export const Row = z.object({
  "id": z.string().uuid(),
  "cart_id": z.string().uuid().nullable(),
  "product_id": z.string().uuid().nullable(),
  "scrap_id": z.string().uuid().nullable(),
  "quantity": z.number().int(),
  "gross_unit": z.string().nullable(),
});
export type Row = z.infer<typeof Row>;
// generated:end

// Hand-written derivations go here: New, Patch, named reads.
