// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: exchange.shipments
import { z } from "zod/v4";

export const Row = z.object({
  "id": z.string().uuid(),
  "purchase_order_id": z.string().uuid().nullable(),
  "tracking_number": z.string().nullable(),
  "shipping_status": z.string().nullable(),
  "estimated_delivery": z.string().nullable(),
  "shipped_at": z.string().nullable(),
  "delivered_at": z.string().nullable(),
  "created_at": z.string().nullable(),
  "shipping_label": z.string().nullable(),
  "label_type": z.string().nullable(),
  "pickup_type": z.string().nullable(),
  "package": z.string().nullable(),
  "service_type": z.string().nullable(),
  "net_charge": z.number().nullable(),
  "insured": z.boolean().nullable(),
  "declared_value": z.number().nullable(),
  "type": z.string().nullable(),
  "sales_order_id": z.string().uuid().nullable(),
  "carrier_id": z.string().uuid().nullable(),
});
export type Row = z.infer<typeof Row>;
// generated:end

// Hand-written derivations go here: New, Patch, named reads.
