// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: exchange.state_sales_tax
import { z } from "zod/v4";

export const Row = z.object({
  "id": z.string().uuid(),
  "state": z.string(),
  "reached_nexus": z.boolean(),
  "amount_owed": z.number(),
  "last_remitted": z.string().nullable(),
});
export type Row = z.infer<typeof Row>;
// generated:end

// Hand-written derivations go here: New, Patch, named reads.
