// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: exchange.tracking_events
import { z } from "zod/v4";

export const Row = z.object({
  "id": z.string().uuid(),
  "shipment_id": z.string().uuid().nullable(),
  "status": z.string().nullable(),
  "location": z.string().nullable(),
  "scan_time": z.string().nullable(),
});
export type Row = z.infer<typeof Row>;
// generated:end

// Hand-written derivations go here: New, Patch, named reads.
