// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: exchange.users
import { z } from "zod/v4";

export const Row = z.object({
  "id": z.string().uuid(),
  "email": z.string(),
  "name": z.string().nullable(),
  "createdAt": z.string().nullable(),
  "updatedAt": z.string().nullable(),
  "emailVerified": z.boolean().nullable(),
  "image": z.string().nullable(),
  "role": z.string().nullable(),
  "stripeCustomerId": z.string().nullable(),
  "dorado_funds": z.number(),
  "banned": z.boolean().nullable(),
  "banReason": z.string().nullable(),
  "banExpires": z.string().nullable(),
});
export type Row = z.infer<typeof Row>;
// generated:end
// The user endpoints alias better-auth's camelCase columns to snake_case and
// omit the Stripe and ban columns. One of the few places where the wire
// genuinely differs from the table.
export const Read = Row.omit({
  createdAt: true,
  updatedAt: true,
  emailVerified: true,
  stripeCustomerId: true,
  banned: true,
  banReason: true,
  banExpires: true,
}).extend({
  created_at: Row.shape.createdAt,
  updated_at: Row.shape.updatedAt,
  email_verified: Row.shape.emailVerified,
});
export type Read = z.infer<typeof Read>;

