// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: exchange.verification
import { z } from "zod/v4";

export const Row = z.object({
  "id": z.string().uuid(),
  "identifier": z.string(),
  "value": z.string(),
  "expiresAt": z.string(),
  "createdAt": z.string().nullable(),
  "updatedAt": z.string().nullable(),
});
export type Row = z.infer<typeof Row>;
// generated:end

// Hand-written derivations go here: New, Patch, named reads.
