// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: payments.attempts
import { z } from "zod/v4";

export const Row = z.object({
  "id": z.string().uuid(),
  "intent_id": z.string().uuid(),
  "method_id": z.string().uuid().nullable(),
  "provider": z.string().nullable(),
  "provider_ref": z.string(),
  "amount": z.number().nullable(),
  "status": z.string(),
  "error_code": z.string().nullable(),
  "error_message": z.string().nullable(),
  "created_at": z.string(),
});
export type Row = z.infer<typeof Row>;
// generated:end
// The latest attempt on an intent, as the checkout surface reads it.
export const Read = Row.pick({
  provider: true,
  provider_ref: true,
  status: true,
}).extend({
  provider_ref: Row.shape.provider_ref.nullable(),
  status: Row.shape.status.nullable(),
});
export type Read = z.infer<typeof Read>;

