// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: payments.attempts
import { z } from "zod/v4";

export const PaymentAttempt = z.object({
  "id": z.string().uuid(),
  "intent_id": z.string().uuid(),
  "method_id": z.string().uuid().nullable(),
  "provider": z.string().nullable(),
  "provider_ref": z.string(),
  "amount": z.number().nullable(),
  "status": z.string(),
  "error_code": z.string().nullable(),
  "error_message": z.string().nullable(),
  "created_at": z.string(),
});
export type PaymentAttempt = z.infer<typeof PaymentAttempt>;
// generated:end
// The latest attempt on an intent, as the checkout surface reads it.
export const IntentAttempt = PaymentAttempt.pick({
  provider: true,
  provider_ref: true,
  status: true,
}).extend({
  provider_ref: PaymentAttempt.shape.provider_ref.nullable(),
  status: PaymentAttempt.shape.status.nullable(),
});
export type IntentAttempt = z.infer<typeof IntentAttempt>;


// A payments.attempts WRITE. The same patch serves create and update - the
// two local shapes it replaced (`NewAttempt`, `AttemptPatch`) listed the same
// columns twice, one file over from the entity that declares them.
export const PaymentAttemptPatch = PaymentAttempt.pick({
  id: true,
  intent_id: true,
  method_id: true,
  provider: true,
  provider_ref: true,
  amount: true,
  status: true,
  error_code: true,
  error_message: true,
}).extend({
  status: PaymentAttempt.shape.status.nullable(),
}).partial();
export type PaymentAttemptPatch = z.infer<typeof PaymentAttemptPatch>;
