// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: payments.bank_links
import { z } from 'zod/v4'
import { LinkMethod, LinkStatus, Rail } from './enums.js'

export const BankLink = z.object({
  'id': z.string().uuid(),
  'user_id': z.string().uuid(),
  'provider': z.string(),
  'moov_account_id': z.string(),
  'moov_bank_account_id': z.string().nullable(),
  'payment_method_id': z.string().nullable(),
  'rail': Rail.nullable(),
  'holder_name': z.string().nullable(),
  'bank_name': z.string().nullable(),
  'last_four': z.string().nullable(),
  'status': LinkStatus,
  'linked_by': LinkMethod,
  'failure_reason': z.string().nullable(),
  'created_at': z.string(),
  'updated_at': z.string(),
  'created_by_id': z.string().uuid().nullable(),
  'updated_by_id': z.string().uuid().nullable(),
})
export type BankLink = z.infer<typeof BankLink>
// generated:end

// Hand-written derivations go here: New, Patch, named reads.

export const BankLinkWrite = BankLink.pick({
  user_id: true,
  provider: true,
  moov_account_id: true,
  moov_bank_account_id: true,
  payment_method_id: true,
  rail: true,
  holder_name: true,
  bank_name: true,
  last_four: true,
  status: true,
  linked_by: true,
})
export type BankLinkWrite = z.infer<typeof BankLinkWrite>

export const BankLinkPatch = BankLink.pick({
  moov_bank_account_id: true,
  payment_method_id: true,
  rail: true,
  bank_name: true,
  last_four: true,
  status: true,
  failure_reason: true,
}).partial()
export type BankLinkPatch = z.infer<typeof BankLinkPatch>
