// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: payments.details
import { z } from "zod/v4";

export const Row = z.object({
  "id": z.string().uuid(),
  "user_id": z.string().uuid(),
  "method_id": z.string().uuid().nullable(),
  "account_holder": z.string().nullable(),
  "bank_name": z.string().nullable(),
  "account_type": z.string().nullable(),
  "routing_number": z.string().nullable(),
  "account_number": z.string().nullable(),
  "last_four": z.string().nullable(),
  "card_brand": z.string().nullable(),
  "email_to": z.string().nullable(),
  "created_at": z.string(),
  "updated_at": z.string(),
  "created_by": z.string().nullable(),
  "updated_by": z.string().nullable(),
  "created_by_id": z.string().uuid().nullable(),
  "updated_by_id": z.string().uuid().nullable(),
  "provider": z.string().nullable(),
  "provider_ref": z.string().nullable(),
  "routing_number_encrypted": z.string().nullable(),
  "account_number_encrypted": z.string().nullable(),
  "encryption_key_id": z.string().nullable(),
  "routing_last_four": z.string().nullable(),
});
export type Row = z.infer<typeof Row>;
// generated:end
// The payment instrument behind an intent. NEVER the two bank numbers: those
// are sealed at rest (AES-256-GCM, D210) and open in exactly one place.
export const Read = Row.pick({
  provider: true,
  provider_ref: true,
  last_four: true,
  card_brand: true,
  bank_name: true,
  account_type: true,
}).extend({
  type: z.string().nullable(),
});
export type Read = z.infer<typeof Read>;

