// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres enum types owned by the `payments` schema.
import { z } from 'zod/v4'

export const InboundSource = z.enum(['moov', 'plaid', 'manual'])
export type InboundSource = z.infer<typeof InboundSource>

export const LinkMethod = z.enum(['plaid', 'micro_deposits', 'vendor_form'])
export type LinkMethod = z.infer<typeof LinkMethod>

export const LinkStatus = z.enum(['pending', 'verified', 'errored'])
export type LinkStatus = z.infer<typeof LinkStatus>

export const MatchState = z.enum(['Unmatched', 'Matched', 'Ignored'])
export type MatchState = z.infer<typeof MatchState>

export const Rail = z.enum(['ACH', 'ACH_SAME_DAY', 'RTP', 'FEDNOW', 'CARD', 'WIRE'])
export type Rail = z.infer<typeof Rail>

export const TransferKind = z.enum(['payout', 'charge'])
export type TransferKind = z.infer<typeof TransferKind>

export const TransferState = z.enum(['Not sent', 'Due', 'Processing', 'Sent', 'Received', 'Failed'])
export type TransferState = z.infer<typeof TransferState>
