// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: payments.feed_cursors
import { z } from 'zod/v4'

export const FeedCursor = z.object({
  'id': z.string().uuid(),
  'source': z.string(),
  'cursor': z.string().nullable(),
  'synced_at': z.string().nullable(),
  'created_at': z.string(),
  'updated_at': z.string(),
})
export type FeedCursor = z.infer<typeof FeedCursor>
// generated:end

// Hand-written derivations go here: New, Patch, named reads.

export const FeedCursorPatch = FeedCursor.pick({ cursor: true, synced_at: true }).partial()
export type FeedCursorPatch = z.infer<typeof FeedCursorPatch>
