// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: payments.inbound_transactions
import { z } from 'zod/v4'
import { InboundSource, MatchState } from './enums.js'

export const InboundTransaction = z.object({
  'id': z.string().uuid(),
  'source': InboundSource,
  'external_id': z.string().nullable(),
  'amount': z.number(),
  'currency': z.string(),
  'occurred_at': z.string(),
  'counterparty_name': z.string().nullable(),
  'memo': z.string().nullable(),
  'account_ref': z.string().nullable(),
  'state': MatchState,
  'order_id': z.string().uuid().nullable(),
  'transfer_id': z.string().uuid().nullable(),
  'matched_at': z.string().nullable(),
  'matched_by_id': z.string().uuid().nullable(),
  'created_at': z.string(),
  'updated_at': z.string(),
  'created_by_id': z.string().uuid().nullable(),
  'updated_by_id': z.string().uuid().nullable(),
})
export type InboundTransaction = z.infer<typeof InboundTransaction>
// generated:end

export const InboundTransactionWrite = InboundTransaction.pick({
  source: true,
  external_id: true,
  amount: true,
  occurred_at: true,
  counterparty_name: true,
  memo: true,
  account_ref: true,
})
export type InboundTransactionWrite = z.infer<typeof InboundTransactionWrite>

export const InboundTransactionPatch = InboundTransaction.pick({
  state: true,
  order_id: true,
  transfer_id: true,
  matched_at: true,
  matched_by_id: true,
}).partial()
export type InboundTransactionPatch = z.infer<typeof InboundTransactionPatch>

export const MatchRung = z.enum(['account', 'reference', 'heuristic', 'manual'])
export type MatchRung = z.infer<typeof MatchRung>

export const MatchCandidate = InboundTransaction.pick({
  id: true,
  source: true,
  amount: true,
  occurred_at: true,
  counterparty_name: true,
  memo: true,
  account_ref: true,
}).extend({
  rung: MatchRung,
  amount_delta: z.number(),
})
export type MatchCandidate = z.infer<typeof MatchCandidate>
