// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: payments.inbound_transactions
import { z } from 'zod/v4'
import { InboundSource, MatchState } from './enums.js'

export const InboundTransaction = z.object({
  'id': z.string().uuid(),
  'source': InboundSource,
  'external_id': z.string().nullable(),
  'amount': z.number(),
  'currency': z.string(),
  'occurred_at': z.string(),
  'counterparty_name': z.string().nullable(),
  'memo': z.string().nullable(),
  'account_ref': z.string().nullable(),
  'state': MatchState,
  'order_id': z.string().uuid().nullable(),
  'transfer_id': z.string().uuid().nullable(),
  'matched_at': z.string().nullable(),
  'matched_by_id': z.string().uuid().nullable(),
  'created_at': z.string(),
  'updated_at': z.string(),
  'created_by_id': z.string().uuid().nullable(),
  'updated_by_id': z.string().uuid().nullable(),
})
export type InboundTransaction = z.infer<typeof InboundTransaction>
// generated:end

// Hand-written derivations go here: New, Patch, named reads.
