// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: payments.intents
import { z } from "zod/v4";

export const Row = z.object({
  "id": z.string().uuid(),
  "order_id": z.string().uuid().nullable(),
  "method_id": z.string().uuid().nullable(),
  "details_id": z.string().uuid().nullable(),
  "amount_expected": z.number().nullable(),
  "status": z.string(),
  "created_at": z.string(),
  "updated_at": z.string(),
  "created_by": z.string().nullable(),
  "updated_by": z.string().nullable(),
  "created_by_id": z.string().uuid().nullable(),
  "updated_by_id": z.string().uuid().nullable(),
  "session_id": z.string().uuid().nullable(),
  "user_id": z.string().uuid().nullable(),
  "type": z.string(),
});
export type Row = z.infer<typeof Row>;
// generated:end
import * as attempts from "./attempts.js";
import * as details from "./details.js";
import * as methods from "./methods.js";
import * as addresses from "../places/addresses.js";
import * as services from "../shipping/services.js";
import * as bullion from "../products/bullion.js";
import * as users from "../auth/users.js";
import { Direction } from "../orders/enums.js";

// Stripe reports money as a number in process and as a string over its own
// wire, and the intent read passes whichever it was handed straight through.
const money = z.union([z.number(), z.string()]).nullable();

// The intent as the checkout surface reads it: the row's own columns plus the
// latest attempt and the instrument. amount_received / amount_capturable are
// the provider's, not columns.
export const Read = Row.pick({
  id: true,
  session_id: true,
  user_id: true,
  type: true,
  status: true,
  order_id: true,
  created_at: true,
  updated_at: true,
}).extend({
  type: Row.shape.type.nullable(),
  status: Row.shape.status.nullable(),
  direction: Direction.nullable(),
  amount_expected: money,
  amount_received: money,
  amount_capturable: money,
  attempt: attempts.Read,
  details: details.Read.nullable(),
});
export type Read = z.infer<typeof Read>;

// POST /payments/update_intent - the cart and the four ids that price it.
export const UpdateLine = bullion.Row.pick({ id: true })
  .extend({ quantity: z.number() })
  .strict();
export type UpdateLine = z.infer<typeof UpdateLine>;

export const UpdateBody = z.object({
  items: z.array(UpdateLine).default([]),
  address_id: addresses.Row.shape.id.optional(),
  carrier_service_id: services.Row.shape.id.optional(),
  payment_method_id: methods.Row.shape.id.optional(),
  user_id: users.Row.shape.id.optional(),
  type: Row.shape.type.optional(),
}).strict();
export type UpdateBody = z.infer<typeof UpdateBody>;

// The provider's id, not ours: a Stripe intent reference.
export const CancelBody = z.object({
  payment_intent_id: attempts.Row.shape.provider_ref,
}).strict();
export type CancelBody = z.infer<typeof CancelBody>;

