// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: payments.intents
import { z } from "zod/v4";

export const PaymentIntent = z.object({
  "id": z.string().uuid(),
  "order_id": z.string().uuid().nullable(),
  "method_id": z.string().uuid().nullable(),
  "details_id": z.string().uuid().nullable(),
  "amount_expected": z.number().nullable(),
  "status": z.string(),
  "created_at": z.string(),
  "updated_at": z.string(),
  "created_by": z.string().nullable(),
  "updated_by": z.string().nullable(),
  "created_by_id": z.string().uuid().nullable(),
  "updated_by_id": z.string().uuid().nullable(),
  "session_id": z.string().uuid().nullable(),
  "user_id": z.string().uuid().nullable(),
  "type": z.string(),
});
export type PaymentIntent = z.infer<typeof PaymentIntent>;
// generated:end
import { PaymentAttempt, IntentAttempt } from "./attempts.js";
import { IntentDetails } from "./details.js";
import { PaymentMethod } from "./methods.js";
import { Address } from "../places/addresses.js";
import { CarrierService } from "../shipping/services.js";
import { Bullion } from "../products/bullion.js";
import { User } from "../auth/users.js";
import { Direction } from "../orders/enums.js";

// Stripe reports money as a number in process and as a string over its own
// wire, and the intent read passes whichever it was handed straight through.
const money = z.union([z.number(), z.string()]).nullable();

// The intent as the checkout surface reads it: the row's own columns plus the
// latest attempt and the instrument. amount_received / amount_capturable are
// the provider's, not columns.
export const PaymentIntentView = PaymentIntent.pick({
  id: true,
  session_id: true,
  user_id: true,
  type: true,
  status: true,
  order_id: true,
  created_at: true,
  updated_at: true,
}).extend({
  type: PaymentIntent.shape.type.nullable(),
  status: PaymentIntent.shape.status.nullable(),
  direction: Direction.nullable(),
  amount_expected: money,
  amount_received: money,
  amount_capturable: money,
  attempt: IntentAttempt,
  details: IntentDetails.nullable(),
});
export type PaymentIntentView = z.infer<typeof PaymentIntentView>;

// A payments.intents WRITE - ids plus the facts, no audit or default columns.
// `id` is the caller's to supply (ruling 43) and create.sql issues one if not.
// The same patch serves create and update: NOT NULL columns and defaults are
// the database's decision, so there is no separate New shape.
export const PaymentIntentPatch = PaymentIntent.pick({
  id: true,
  session_id: true,
  user_id: true,
  type: true,
  status: true,
  amount_expected: true,
  order_id: true,
  details_id: true,
  method_id: true,
}).extend({
  type: PaymentIntent.shape.type.nullable(),
  status: PaymentIntent.shape.status.nullable(),
}).partial();
export type PaymentIntentPatch = z.infer<typeof PaymentIntentPatch>;

// POST /payments/update_intent - the cart and the four ids that price it.
export const PaymentIntentLine = Bullion.pick({ id: true })
  .extend({ quantity: z.number() })
  .strict();
export type PaymentIntentLine = z.infer<typeof PaymentIntentLine>;

export const UpdatePaymentIntentBody = z.object({
  items: z.array(PaymentIntentLine).default([]),
  address_id: Address.shape.id.optional(),
  carrier_service_id: CarrierService.shape.id.optional(),
  payment_method_id: PaymentMethod.shape.id.optional(),
  user_id: User.shape.id.optional(),
  type: PaymentIntent.shape.type.optional(),
}).strict();
export type UpdatePaymentIntentBody = z.infer<typeof UpdatePaymentIntentBody>;

// The PROVIDER's id, not ours: a Stripe intent reference, which is the same
// kind of value payments.attempts stores as provider_ref.
export const CancelPaymentIntentBody = z.object({
  payment_intent_id: PaymentAttempt.shape.provider_ref,
}).strict();
export type CancelPaymentIntentBody = z.infer<typeof CancelPaymentIntentBody>;

