// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: payments.ledger
import { z } from "zod/v4";

export const LedgerEntry = z.object({
  "id": z.string().uuid(),
  "user_id": z.string().uuid(),
  "type": z.string(),
  "order_id": z.string().uuid().nullable(),
  "amount": z.number(),
  "occurred_at": z.string(),
  "created_at": z.string(),
  "updated_at": z.string(),
});
export type LedgerEntry = z.infer<typeof LedgerEntry>;
// generated:end
import { Direction } from "../orders/enums.js";

export const LedgerEntryPatch = LedgerEntry.pick({
  user_id: true,
  order_id: true,
  type: true,
  amount: true,
}).extend({
  user_id: LedgerEntry.shape.user_id.nullable(),
  amount: LedgerEntry.shape.amount.nullable(),
});
export type LedgerEntryPatch = z.infer<typeof LedgerEntryPatch>;

export const AccountTransaction = LedgerEntry.omit({ type: true }).extend({
  transaction_type: LedgerEntry.shape.type,
  direction: Direction.nullable(),
});
export type AccountTransaction = z.infer<typeof AccountTransaction>;
