// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: payments.settlements
import { z } from "zod/v4";

export const Row = z.object({
  "id": z.string().uuid(),
  "attempt_id": z.string().uuid(),
  "settled_amount": z.number(),
  "provider": z.string().nullable(),
  "provider_ref": z.string(),
  "settled_at": z.string().nullable(),
  "created_at": z.string(),
});
export type Row = z.infer<typeof Row>;
// generated:end

// Hand-written derivations go here: New, Patch, named reads.
