// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: payments.settlements
import { z } from "zod/v4";

export const PaymentSettlement = z.object({
  "id": z.string().uuid(),
  "attempt_id": z.string().uuid(),
  "settled_amount": z.number(),
  "provider": z.string().nullable(),
  "provider_ref": z.string(),
  "settled_at": z.string().nullable(),
  "created_at": z.string(),
});
export type PaymentSettlement = z.infer<typeof PaymentSettlement>;
// generated:end

// A payments.settlements WRITE. `id` and `attempt_id` are the row's identity
// - an attempt's settlement never repoints - and created_at is the
// database's. The same patch serves create and update, which is what lets
// the repo build one document and pass it to either.
export const PaymentSettlementPatch = PaymentSettlement.omit({
  id: true, attempt_id: true, created_at: true,
}).partial();
export type PaymentSettlementPatch = z.infer<typeof PaymentSettlementPatch>;
