// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: payments.stripe_charges
import { z } from "zod/v4";

export const StripeCharge = z.object({
  "payment_intent_id": z.string(),
  "charge_id": z.string().nullable(),
  "created_at": z.string(),
  "amount": z.number(),
  "amount_refunded": z.number().nullable(),
  "fee": z.number().nullable(),
  "currency": z.string().nullable(),
  "captured": z.boolean().nullable(),
  "status": z.string(),
  "refunded_at": z.string().nullable(),
  "payment_source_type": z.string().nullable(),
  "stripe_customer_id": z.string().nullable(),
  "livemode": z.boolean().nullable(),
  "imported_at": z.string(),
});
export type StripeCharge = z.infer<typeof StripeCharge>;
// generated:end

// Hand-written derivations go here: New, Patch, named reads.
