// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: payments.transfers
import { z } from 'zod/v4'
import { Rail, TransferKind, TransferState } from './enums.js'

export const Transfer = z.object({
  'id': z.string().uuid(),
  'order_id': z.string().uuid(),
  'kind': TransferKind,
  'rail': Rail,
  'state': TransferState,
  'amount': z.number(),
  'currency': z.string(),
  'counterparty_user_id': z.string().uuid().nullable(),
  'details_id': z.string().uuid().nullable(),
  'bank_link_id': z.string().uuid().nullable(),
  'provider': z.string().nullable(),
  'provider_ref': z.string().nullable(),
  'reference': z.string().nullable(),
  'failure_reason': z.string().nullable(),
  'idempotency_key': z.string().nullable(),
  'sent_at': z.string().nullable(),
  'completed_at': z.string().nullable(),
  'created_at': z.string(),
  'updated_at': z.string(),
  'created_by_id': z.string().uuid().nullable(),
  'updated_by_id': z.string().uuid().nullable(),
})
export type Transfer = z.infer<typeof Transfer>
// generated:end

// Hand-written derivations go here: New, Patch, named reads.
import { Order } from '../orders/orders.js'
import { OrderTotals } from '../orders/transactions.js'
import { BankLink } from './bank_links.js'
import { PaymentDetails } from './details.js'

export const Payout = Transfer.extend({ kind: z.literal('payout') })
export type Payout = z.infer<typeof Payout>

export const Charge = Transfer.extend({ kind: z.literal('charge') })
export type Charge = z.infer<typeof Charge>

export const TransferWrite = Transfer.pick({
  order_id: true,
  kind: true,
  rail: true,
  state: true,
  amount: true,
  counterparty_user_id: true,
  details_id: true,
  bank_link_id: true,
  provider: true,
  provider_ref: true,
  reference: true,
  idempotency_key: true,
})
export type TransferWrite = z.infer<typeof TransferWrite>

export const TransferPatch = Transfer.pick({
  rail: true,
  state: true,
  amount: true,
  details_id: true,
  bank_link_id: true,
  provider: true,
  provider_ref: true,
  reference: true,
  failure_reason: true,
  sent_at: true,
  completed_at: true,
}).partial()
export type TransferPatch = z.infer<typeof TransferPatch>

export const TransferGuard = Transfer.pick({ state: true, kind: true }).partial()
export type TransferGuard = z.infer<typeof TransferGuard>

export const PayTo = BankLink.pick({
  id: true,
  rail: true,
  bank_name: true,
  holder_name: true,
  last_four: true,
  status: true,
  payment_method_id: true,
})
export type PayTo = z.infer<typeof PayTo>

export const PayoutAccount = PaymentDetails.pick({
  id: true,
  bank_name: true,
  account_type: true,
  last_four: true,
  email_to: true,
}).extend({ method: z.string().nullable() })
export type PayoutAccount = z.infer<typeof PayoutAccount>

export const PaymentView = z.object({
  order_id: Order.shape.id,
  number: Order.shape.number,
  direction: Order.shape.direction,
  amount_due: OrderTotals.shape.post_charges_amount,
  transfer_id: Transfer.shape.id.nullable(),
  kind: Transfer.shape.kind.nullable(),
  rail: Transfer.shape.rail.nullable(),
  state: Transfer.shape.state.nullable(),
  amount: Transfer.shape.amount.nullable(),
  reference: Transfer.shape.reference,
  failure_reason: Transfer.shape.failure_reason,
  provider: Transfer.shape.provider,
  provider_ref: Transfer.shape.provider_ref,
  sent_at: Transfer.shape.sent_at,
  completed_at: Transfer.shape.completed_at,
  pay_to: PayTo.nullable(),
  payout_account: PayoutAccount.nullable(),
})
export type PaymentView = z.infer<typeof PaymentView>
