// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: payments.transfer_events
import { z } from 'zod/v4'
import { TransferState } from './enums.js'

export const TransferEvent = z.object({
  'id': z.string().uuid(),
  'transfer_id': z.string().uuid().nullable(),
  'provider': z.string(),
  'event_id': z.string(),
  'event_type': z.string(),
  'provider_ref': z.string().nullable(),
  'reported_state': TransferState.nullable(),
  'failure_reason': z.string().nullable(),
  'occurred_at': z.string(),
  'applied': z.boolean(),
  'created_at': z.string(),
})
export type TransferEvent = z.infer<typeof TransferEvent>
// generated:end

// Hand-written derivations go here: New, Patch, named reads.
