// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: payments.transfers
import { z } from 'zod/v4'
import { Rail, TransferKind, TransferState } from './enums.js'

export const Transfer = z.object({
  'id': z.string().uuid(),
  'order_id': z.string().uuid(),
  'kind': TransferKind,
  'rail': Rail,
  'state': TransferState,
  'amount': z.number(),
  'currency': z.string(),
  'counterparty_user_id': z.string().uuid().nullable(),
  'details_id': z.string().uuid().nullable(),
  'bank_link_id': z.string().uuid().nullable(),
  'provider': z.string().nullable(),
  'provider_ref': z.string().nullable(),
  'reference': z.string().nullable(),
  'failure_reason': z.string().nullable(),
  'idempotency_key': z.string().nullable(),
  'sent_at': z.string().nullable(),
  'completed_at': z.string().nullable(),
  'created_at': z.string(),
  'updated_at': z.string(),
  'created_by_id': z.string().uuid().nullable(),
  'updated_by_id': z.string().uuid().nullable(),
})
export type Transfer = z.infer<typeof Transfer>
// generated:end

// Hand-written derivations go here: New, Patch, named reads.
