// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: lots.items
import { z } from 'zod/v4'

export const Lot = z.object({
  'id': z.string().uuid(),
  'bullion_id': z.string().uuid().nullable(),
  'metal_id': z.string(),
  'unit': z.string(),
  'quantity': z.number(),
  'pre_melt': z.number().nullable(),
  'post_melt': z.number().nullable(),
  'purity': z.number().nullable(),
  'content_snapshot': z.number().nullable(),
  'content': z.number().nullable(),
  'image_id': z.string().uuid().nullable(),
  'split_from_id': z.string().uuid().nullable(),
  'created_at': z.string(),
  'updated_at': z.string(),
  'created_by_id': z.string().uuid().nullable(),
  'updated_by_id': z.string().uuid().nullable(),
})
export type Lot = z.infer<typeof Lot>
// generated:end

import { Bullion } from '../products/bullion.js'

export const LotPatch = Lot.pick({
  metal_id: true,
  bullion_id: true,
  unit: true,
  quantity: true,
  pre_melt: true,
  post_melt: true,
  purity: true,
  image_id: true,
})
  .partial()
  .strict()
export type LotPatch = z.infer<typeof LotPatch>

export const LotSplitPart = Lot.pick({
  pre_melt: true,
  post_melt: true,
  purity: true,
  unit: true,
  quantity: true,
})
  .extend({ pre_melt: Lot.shape.pre_melt.unwrap() })
  .partial({ post_melt: true, purity: true, unit: true, quantity: true })
  .strict()
export type LotSplitPart = z.infer<typeof LotSplitPart>

export const LotSplit = z.object({ parts: z.array(LotSplitPart).min(2) }).strict()
export type LotSplit = z.infer<typeof LotSplit>

export const LotView = Lot.extend({
  product_name: Bullion.shape.name.nullable(),
  form: Bullion.shape.type.nullable(),
  reference: Lot.shape.metal_id.nullable(),
})
export type LotView = z.infer<typeof LotView>
