import "#env";
import fs from "node:fs";
import path from "node:path";
import pool from "#pool";

const TABLES = [
  ["organizations", "organizations", "type = 'DORADO'"],
  ["places", "addresses", "id IN (SELECT address_id FROM places.locations WHERE address_id IS NOT NULL)"],
  ["places", "locations", null],
  ["places", "location_hours", null],
  ["shipping", "services", null],
  ["shipping", "packages", null],
  ["fulfillments", "methods", null],
  ["payments", "methods", null],
  ["auth", "employees", null],
];

const q = async (sql, params = []) => (await pool.query(sql, params)).rows;

const RESOLVE = {
  "places.locations.organization_id": async (id) => {
    const [org] = await q(
      "SELECT type, name FROM organizations.organizations WHERE id = $1",
      [id]
    );
    if (!org) return null;
    return `(SELECT id FROM organizations.organizations WHERE type = '${org.type.replace(/'/g, "''")}' AND name = '${org.name.replace(/'/g, "''")}')`;
  },
};
const ident = (s) => (/^[a-z_][a-z0-9_]*$/.test(s) ? s : `"${s}"`);

function literal(v, type) {
  if (v === null || v === undefined) return `NULL::${type}`;
  if (typeof v === "string") return `'${v.replace(/'/g, "''")}'::${type}`;
  if (typeof v === "boolean") return v ? "true" : "false";
  if (typeof v === "number") return String(v);
  if (Array.isArray(v)) {
    const items = v.map(
      (x) => `"${String(x).replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`
    );
    const arr = `{${items.join(",")}}`;
    return `'${arr.replace(/'/g, "''")}'::${type}`;
  }
  if (typeof v === "object") {
    return `'${JSON.stringify(v).replace(/'/g, "''")}'::${type}`;
  }
  return `'${String(v).replace(/'/g, "''")}'::${type}`;
}

const out = [];
const say = (s = "") => out.push(s);

say(`-- Reference data with no source in exchange.
--
-- Everything else in the new schema is derived: the backfills read exchange and
-- reshape it. These rows cannot be, because exchange has never held them. They
-- are facts about the business that were written straight into dev in January -
-- the organization the business itself is, its locations and their opening
-- hours, the fulfillment and payment methods offered, and who is an employee.
--
-- So they are carried across as literal values, which is the only way to move
-- something that has no source. Ids are preserved: locations reference an
-- organization and hours reference a location, and the set only hangs together
-- if those survive.
--
-- Every insert is ON CONFLICT DO NOTHING. On dev this is a no-op; on an empty
-- database it is the difference between a schema that exists and a schema that
-- works, since without payment and fulfillment methods there is nothing for a
-- customer to choose at checkout.
--
-- GENERATED by scripts/dump-seed.mjs. Regenerate rather than editing by hand.
--
-- exchange is untouched - it is not read here either, because there is nothing
-- in it to read.
`);

let total = 0;

for (const [schema, table, where] of TABLES) {
  const cols = await q(
    `SELECT a.attname AS column_name, format_type(a.atttypid, a.atttypmod) AS type
     FROM pg_attribute a
     WHERE a.attrelid = $1::regclass AND a.attnum > 0 AND NOT a.attisdropped
     ORDER BY a.attnum`,
    [`${schema}.${table}`]
  );

  const rows = await q(
    `SELECT ${cols.map((c) => `${ident(c.column_name)}::text AS ${ident(c.column_name)}`).join(", ")}
     FROM ${ident(schema)}.${ident(table)} ${where ? `WHERE ${where}` : ""}
     ORDER BY id`
  );
  if (!rows.length) continue;
  total += rows.length;

  say(`-- ${schema}.${table} (${rows.length} row${rows.length === 1 ? "" : "s"})`);
  if (where) say(`-- Only ${where.replace(/'/g, "")}; the rest are derived from exchange by 029.`);
  say(`INSERT INTO ${ident(schema)}.${ident(table)} (${cols.map((c) => ident(c.column_name)).join(", ")})`);
  say("VALUES");
  const rendered = [];
  for (const r of rows) {
    const values = [];
    for (const c of cols) {
      const resolver = RESOLVE[`${schema}.${table}.${c.column_name}`];
      const v = r[c.column_name];
      if (resolver && v != null) {
        const expr = await resolver(v);
        values.push(expr ?? literal(v, c.type));
      } else {
        values.push(literal(v, c.type));
      }
    }
    rendered.push("  (" + values.join(", ") + ")");
  }
  say(rendered.join(",\n"));
  say("ON CONFLICT (id) DO NOTHING;");
  say();
}

await pool.end();

const sql = out.join("\n");
const target = path.join(import.meta.dirname, "..", "migrations", "047_seed_reference_data.sql");
fs.writeFileSync(target, sql);
console.log(`wrote ${path.relative(process.cwd(), target)} - ${total} rows across ${TABLES.length} tables`);
