import "#env";
import fs from "node:fs";
import path from "node:path";
import pool from "#pool";
import { NATIVE_SCHEMAS as SCHEMAS, assertSchemasComplete } from "./lib/schemas.ts";

const q = async (sql, params = []) => (await pool.query(sql, params)).rows;

try {
  await assertSchemasComplete(q);
} catch (e) {
  console.error(e.message);
  process.exit(1);
}

const prefixArg = process.argv.indexOf("--prefix");
const PREFIX = prefixArg === -1 ? "" : process.argv[prefixArg + 1];
const sch = (s) => PREFIX + s;

const id = (s) => (/^[a-z_][a-z0-9_]*$/.test(s) ? s : `"${s.replace(/"/g, '""')}"`);
const lit = (s) => `'${s.replace(/'/g, "''")}'`;

const qualify = (def) =>
  PREFIX
    ? SCHEMAS.reduce((acc, s) => acc.replace(new RegExp(`\\b${s}\\.`, "g"), `${PREFIX}${s}.`), def)
    : def;

const out = [];
const say = (s = "") => out.push(s);

const BASELINE = "002-133";

say(`-- baseline: ${BASELINE}
--
-- The schema itself. Creates every domain-namespaced schema from nothing.
--
-- This migration exists because the others assume it. The domain schemas were
-- built directly in dev in January and their DDL was never committed, so every
-- migration from 002 onwards - all of which ALTER those tables - could only run
-- on this one machine. Migration 002 opens with \`ALTER TABLE core.leads\`, which
-- on any other database is an immediate abort.
--
-- Numbered 000 so it sorts ahead of 001 and runs first on a database that has
-- nothing. The runner applies pending files in filename order regardless of
-- what has already been applied, so adding it after the fact is fine: on dev
-- every statement is guarded and the whole file is a no-op.
--
-- GENERATED by scripts/dump-schema.mjs from the dev catalog. Regenerate rather
-- than editing by hand, and only while dev is still the definition of correct.
--
-- The \`baseline: ${BASELINE}\` line above matters, and it says more than it used to.
-- This file is generated from DEV, which has every migration applied, so the
-- shape it creates is the shape after ALL of them - not the shape after 049.
-- It read \`002-049\` until 2026-09-06, and that understatement is the single
-- bug the UAT rehearsal met six times (F3-F6): migrations 050 onwards were
-- replayed against a database that already had their result, and each one that
-- named a column a later migration drops, or created an object this file
-- already created, aborted the chain.
--
-- So the range now runs to the last migration this file was generated behind.
-- 001 is deliberately still outside it: it indexes foreign keys on exchange,
-- which any real database still wants.
--
-- WHAT A BASELINE STAMPS IS SHAPE, NEVER ROWS. The runner splits the covered
-- set: a migration whose every statement is DDL is recorded as done, and one
-- that carries an INSERT, UPDATE or DELETE still RUNS, in its own place in the
-- order. Stamping a backfill is how the rehearsal ended with an empty product
-- catalogue, no metals and no spot prices (F7); \`scripts/lib/baseline.ts\`
-- \`isDdlOnly\` is where the split is decided and it treats anything it cannot
-- read as data, which is the safe direction.
--
-- The stamping is only sound on a database genesis builds from NOTHING, since
-- every statement here is IF NOT EXISTS and cannot repair a table that already
-- exists. The runner therefore refuses to apply this file's baseline while any
-- non-protected schema still holds a table, and points at
-- \`migrate:reset-january\` - ruling 82, Jacob 2026-09-06: drop the abandoned
-- January schemas after the dump and let genesis and the backfills rebuild
-- them. exchange is never dropped.
--
-- This file creates structure and nothing else. Populating the tables from
-- exchange is a separate migration, because it is a different kind of risk.
--
-- exchange is untouched.
`);

say("-- Schemas ------------------------------------------------------------");
say();
for (const s of SCHEMAS) say(`CREATE SCHEMA IF NOT EXISTS ${id(sch(s))};`);
say();

const enums = await q(
  `SELECT n.nspname AS schema, t.typname AS name,
          array_agg(e.enumlabel::text ORDER BY e.enumsortorder) AS labels
   FROM pg_type t
   JOIN pg_namespace n ON n.oid = t.typnamespace
   JOIN pg_enum e ON e.enumtypid = t.oid
   WHERE n.nspname = ANY($1)
   GROUP BY 1, 2 ORDER BY 1, 2`,
  [SCHEMAS]
);

if (enums.length) {
  say("-- Enum types ---------------------------------------------------------");
  say("--");
  say("-- CREATE TYPE has no IF NOT EXISTS, so each one checks pg_type first.");
  say("-- Note that orders.direction and shipping.direction are different types");
  say("-- that happen to share a name; the schema is what keeps them apart.");
  say();
  for (const e of enums) {
    const labels = e.labels.map(lit).join(", ");
    say(`DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace
    WHERE t.typname = ${lit(e.name)} AND n.nspname = ${lit(sch(e.schema))}
  ) THEN
    CREATE TYPE ${id(sch(e.schema))}.${id(e.name)} AS ENUM (${labels});
  END IF;
END $$;`);
    say();
  }
}

const tables = await q(
  `SELECT c.oid, n.nspname AS schema, c.relname AS name
   FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
   WHERE c.relkind = 'r' AND n.nspname = ANY($1)
   ORDER BY n.nspname, c.relname`,
  [SCHEMAS]
);

say("-- Tables -------------------------------------------------------------");
say("--");
say("-- Columns, types, defaults and NOT NULL only. Constraints come after, so");
say("-- that a foreign key never refers to a table that has not been made yet.");
say();

for (const t of tables) {
  const cols = await q(
    `SELECT a.attname AS name,
            format_type(a.atttypid, a.atttypmod) AS type,
            a.attnotnull AS not_null,
            a.attidentity AS identity,
            pg_get_expr(d.adbin, d.adrelid) AS default_expr
     FROM pg_attribute a
     LEFT JOIN pg_attrdef d ON d.adrelid = a.attrelid AND d.adnum = a.attnum
     WHERE a.attrelid = $1 AND a.attnum > 0 AND NOT a.attisdropped
     ORDER BY a.attnum`,
    [t.oid]
  );

  const lines = cols.map((c) => {
    let s = `  ${id(c.name)} ${qualify(c.type)}`;
    if (c.identity === "a") s += " GENERATED ALWAYS AS IDENTITY";
    else if (c.identity === "d") s += " GENERATED BY DEFAULT AS IDENTITY";
    else if (c.default_expr) s += ` DEFAULT ${qualify(c.default_expr)}`;
    if (c.not_null) s += " NOT NULL";
    return s;
  });

  say(`CREATE TABLE IF NOT EXISTS ${id(sch(t.schema))}.${id(t.name)} (`);
  say(lines.join(",\n"));
  say(`);`);

  for (const c of cols) {
    if (c.identity) continue;
    let add = `ALTER TABLE ${id(sch(t.schema))}.${id(t.name)} ` +
              `ADD COLUMN IF NOT EXISTS ${id(c.name)} ${qualify(c.type)}`;
    if (c.default_expr) add += ` DEFAULT ${qualify(c.default_expr)}`;
    say(`${add};`);
  }
  say();
}

say("-- Constraints --------------------------------------------------------");
say("--");
say("-- Primary keys, uniques and checks first, then foreign keys, so a key can");
say("-- always find the unique index it points at. ALTER TABLE ADD CONSTRAINT");
say("-- has no IF NOT EXISTS either, hence the catalog check on each.");
say();

const constraints = await q(
  `SELECT n.nspname AS schema, c.relname AS table, con.conname AS name,
          con.contype AS type, pg_get_constraintdef(con.oid) AS def
   FROM pg_constraint con
   JOIN pg_class c ON c.oid = con.conrelid
   JOIN pg_namespace n ON n.oid = c.relnamespace
   WHERE n.nspname = ANY($1)
   ORDER BY (con.contype = 'f'), n.nspname, c.relname, con.conname`,
  [SCHEMAS]
);

for (const c of constraints) {
  say(`DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint con
    JOIN pg_class c ON c.oid = con.conrelid
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE con.conname = ${lit(c.name)} AND c.relname = ${lit(c.table)} AND n.nspname = ${lit(sch(c.schema))}
  ) THEN
    ALTER TABLE ${id(sch(c.schema))}.${id(c.table)} ADD CONSTRAINT ${id(c.name)} ${qualify(c.def)};
  END IF;
END $$;`);
}
say();

const indexes = await q(
  `SELECT pg_get_indexdef(i.indexrelid) AS def
   FROM pg_index i
   JOIN pg_class c ON c.oid = i.indrelid
   JOIN pg_class ic ON ic.oid = i.indexrelid
   JOIN pg_namespace n ON n.oid = c.relnamespace
   WHERE n.nspname = ANY($1)
     AND NOT EXISTS (SELECT 1 FROM pg_constraint con WHERE con.conindid = i.indexrelid)
   ORDER BY n.nspname, c.relname, ic.relname`,
  [SCHEMAS]
);

if (indexes.length) {
  say("-- Indexes ------------------------------------------------------------");
  say("--");
  say("-- Only the ones not already created by a constraint above; a primary key");
  say("-- or unique constraint brings its own index and declaring it twice fails.");
  say();
  for (const i of indexes) {
    say(
      qualify(i.def).replace(/^CREATE (UNIQUE )?INDEX /, (m, u) => `CREATE ${u ?? ""}INDEX IF NOT EXISTS `) + ";"
    );
  }
  say();
}

const functions = await q(
  `SELECT pg_get_functiondef(p.oid) AS def
   FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
   WHERE n.nspname = ANY($1) ORDER BY p.proname`,
  [SCHEMAS]
);

if (functions.length) {
  say("-- Functions ----------------------------------------------------------");
  say();
  for (const f of functions) say(qualify(f.def.trimEnd()) + ";\n");
}

const views = await q(
  `SELECT n.nspname AS schema, c.relname AS name, pg_get_viewdef(c.oid, true) AS def
   FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
   WHERE c.relkind = 'v' AND n.nspname = ANY($1)
   ORDER BY n.nspname, c.relname`,
  [SCHEMAS]
);

if (views.length) {
  say("-- Views --------------------------------------------------------------");
  say("--");
  say("-- The compat views, which reassemble an exchange-shaped row from the");
  say("-- tables it was split across. Only the parity check reads them.");
  say();
  for (const v of views) {
    say(`CREATE OR REPLACE VIEW ${id(sch(v.schema))}.${id(v.name)} AS`);
    say(qualify(v.def.trimEnd().replace(/;$/, "")) + ";");
    say();
  }
}

await pool.end();

const sql = out.join("\n").replace(/\n{3,}/g, "\n\n");

if (process.argv.includes("--stdout")) {
  process.stdout.write(sql);
} else {
  const target = path.join(import.meta.dirname, "..", "migrations", "000_genesis_schema.sql");
  fs.writeFileSync(target, sql);
  console.log(`wrote ${path.relative(process.cwd(), target)} (${sql.split("\n").length} lines)`);
}
