// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres enum types owned by the `inventory` schema.
import { z } from 'zod/v4'

export const LockPurpose = z.enum(['Sell to refiner', 'Source a sale'])
export type LockPurpose = z.infer<typeof LockPurpose>

export const LotSourceChoice = z.enum(['inventory', 'refiner', 'pool'])
export type LotSourceChoice = z.infer<typeof LotSourceChoice>

export const LotSourceKind = z.enum(['split', 'combine', 'batch', 'sale'])
export type LotSourceKind = z.infer<typeof LotSourceKind>

export const PoolEntryKind = z.enum(['credit', 'lock'])
export type PoolEntryKind = z.infer<typeof PoolEntryKind>
