// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: inventory.lot_sources
import { z } from 'zod/v4'
import { LotSourceKind } from './enums.js'

export const LotSource = z.object({
  'id': z.string().uuid(),
  'lot_id': z.string().uuid(),
  'source_lot_id': z.string().uuid(),
  'kind': LotSourceKind,
  'created_at': z.string(),
  'updated_at': z.string(),
  'created_by_id': z.string().uuid().nullable(),
  'updated_by_id': z.string().uuid().nullable(),
})
export type LotSource = z.infer<typeof LotSource>
// generated:end

import { Lot } from './lots.js'

export const LotEdge = z
  .object({ id: LotSource.shape.lot_id, kind: LotSource.shape.kind })
  .extend({
    reference: z.string().nullable(),
    content: Lot.shape.content,
    share: Lot.shape.content,
  })
export type LotEdge = z.infer<typeof LotEdge>
