// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: inventory.lots
import { z } from 'zod/v4'
import { LotSourceChoice } from './enums.js'

export const Lot = z.object({
  'id': z.string().uuid(),
  'bullion_id': z.string().uuid().nullable(),
  'metal_id': z.string(),
  'unit': z.string(),
  'quantity': z.number(),
  'pre_melt': z.number().nullable(),
  'post_melt': z.number().nullable(),
  'purity': z.number().nullable(),
  'content_snapshot': z.number().nullable(),
  'content': z.number().nullable(),
  'image_id': z.string().uuid().nullable(),
  'created_at': z.string(),
  'updated_at': z.string(),
  'created_by_id': z.string().uuid().nullable(),
  'updated_by_id': z.string().uuid().nullable(),
  'declared_unit': z.string().nullable(),
  'declared_quantity': z.number().nullable(),
  'declared_pre_melt': z.number().nullable(),
  'declared_post_melt': z.number().nullable(),
  'declared_purity': z.number().nullable(),
  'assayed_at': z.string().nullable(),
  'declared_content': z.number().nullable(),
  'premium': z.number().nullable(),
  'sales_tax_rate': z.number().nullable(),
  'confirmed_at': z.string().nullable(),
  'settled_at': z.string().nullable(),
  'settled_spot': z.number().nullable(),
  'source': LotSourceChoice.nullable(),
  'line_reference': z.string().nullable(),
})
export type Lot = z.infer<typeof Lot>
// generated:end

import { Bullion } from '../products/bullion.js'

export const LotPatch = Lot.pick({
  metal_id: true,
  bullion_id: true,
  unit: true,
  quantity: true,
  pre_melt: true,
  post_melt: true,
  purity: true,
  image_id: true,
  premium: true,
  sales_tax_rate: true,
  confirmed_at: true,
  settled_at: true,
  settled_spot: true,
  source: true,
})
  .partial()
  .strict()
export type LotPatch = z.infer<typeof LotPatch>

export const LotSplitPart = Lot.pick({
  pre_melt: true,
  post_melt: true,
  purity: true,
  unit: true,
  quantity: true,
})
  .extend({ pre_melt: Lot.shape.pre_melt.unwrap() })
  .partial({ post_melt: true, purity: true, unit: true, quantity: true })
  .strict()
export type LotSplitPart = z.infer<typeof LotSplitPart>

export const LotSplit = z.object({ parts: z.array(LotSplitPart).min(2) }).strict()
export type LotSplit = z.infer<typeof LotSplit>

export const Position = z.enum(['incoming', 'on hand', 'at refiner', 'pooled', 'sold', 'consumed'])
export type Position = z.infer<typeof Position>

export const LotKind = z.enum(['scrap', 'bullion'])
export type LotKind = z.infer<typeof LotKind>

export const LotView = Lot.extend({
  product_name: Bullion.shape.name.nullable(),
  form: Bullion.shape.type.nullable(),
  reference: Lot.shape.metal_id.nullable(),
})
export type LotView = z.infer<typeof LotView>

export const InventoryLotView = LotView.extend({
  position: Position,
  order_id: Lot.shape.id.nullable(),
  order_number: z.number().int().nullable(),
  order_reference: z.string().nullable(),
  order_direction: z.string().nullable(),
  refining_order_id: Lot.shape.id.nullable(),
  refining_order_number: z.number().int().nullable(),
  refining_order_reference: z.string().nullable(),
  refiner_id: Lot.shape.id.nullable(),
  refiner_name: z.string().nullable(),
  variance: Lot.shape.content,
})
export type InventoryLotView = z.infer<typeof InventoryLotView>

export const LotPosition = z.object({
  id: Lot.shape.id,
  position: Position,
})
export type LotPosition = z.infer<typeof LotPosition>

export const LotFilter = z.object({}).extend({
  positions: z.array(Position).nullable(),
  metal_id: z.string().nullable(),
  kind: LotKind.nullable(),
  order_id: z.string().uuid().nullable(),
  refiner_id: z.string().uuid().nullable(),
  q: z.string().nullable(),
  unassigned: z.boolean().nullable(),
})
export type LotFilter = z.infer<typeof LotFilter>

export const LotCombine = z.object({ lot_ids: z.array(Lot.shape.id).min(2) }).strict()
export type LotCombine = z.infer<typeof LotCombine>
