// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: inventory.pool
import { z } from 'zod/v4'
import { LockPurpose, PoolEntryKind } from './enums.js'

export const PoolEntry = z.object({
  'id': z.string().uuid(),
  'refiner_id': z.string().uuid(),
  'metal_id': z.string(),
  'entry': PoolEntryKind,
  'troy_oz': z.number(),
  'lock_price': z.number().nullable(),
  'refining_order_id': z.string().uuid().nullable(),
  'occurred_at': z.string(),
  'created_at': z.string(),
  'created_by_id': z.string().uuid().nullable(),
  'purpose': LockPurpose.nullable(),
  'lot_id': z.string().uuid().nullable(),
  'spot': z.number().nullable(),
  'basis_spot': z.number().nullable(),
})
export type PoolEntry = z.infer<typeof PoolEntry>
// generated:end

export const PoolLockCreate = PoolEntry.pick({
  refiner_id: true,
  metal_id: true,
  troy_oz: true,
  lock_price: true,
  refining_order_id: true,
  purpose: true,
  lot_id: true,
})
  .extend({
    lock_price: PoolEntry.shape.lock_price.unwrap(),
    purpose: PoolEntry.shape.purpose.unwrap(),
  })
  .partial({ refining_order_id: true, lot_id: true })
  .strict()
export type PoolLockCreate = z.infer<typeof PoolLockCreate>

export const PoolBalance = PoolEntry.pick({ refiner_id: true, metal_id: true }).extend({
  troy_oz: PoolEntry.shape.troy_oz,
  balance: PoolEntry.shape.troy_oz,
  locked: PoolEntry.shape.troy_oz,
  available: PoolEntry.shape.troy_oz,
  last_lock_price: PoolEntry.shape.lock_price,
  basis: PoolEntry.shape.spot,
  realised_gain: z.number(),
  unrealised_gain: PoolEntry.shape.spot,
})
export type PoolBalance = z.infer<typeof PoolBalance>

export const PoolEntryView = PoolEntry.extend({ gain: PoolEntry.shape.spot })
export type PoolEntryView = z.infer<typeof PoolEntryView>
