// organizations.organizations, and nothing else.
//
// THE ONLY SERVICE THAT WRITES THIS TABLE. Carriers create and update an
// organization as part of creating and updating a carrier, and refiners and
// mints compose one into their own shape. Every one of those used to reach into
// this table directly - the carrier update was a statement against
// organizations that had to know about shipping.carriers to find its row.
//
// One table, one writing service: carriers' service calls this one, inside its
// own transaction, rather than writing here itself.
import query from "#shared/db/query.ts";
import { sqlFrom } from "#shared/db/sql.ts";
import type { organizations } from "@dorado/contracts";
import type { Executor } from "#shared/db/executor.ts";

const sql = sqlFrom(import.meta.dirname);

export type OrganizationRow = organizations.OrganizationsRow;

// THE CONTRACT TYPE ITSELF (Pick, not a hand-invented parallel shape) - id and
// type are not part of it: they are supplied separately (id is generated by
// the caller so both schemas can agree on it while exchange still exists;
// type is a business fact - CARRIER, REFINER, or the business itself - that
// this table does not decide). The service passes what it received straight
// through; a field this table cannot express is simply not in the type.
export type OrganizationPatch = Pick<OrganizationRow, "name" | "email" | "phone" | "enabled">;

// THE FULL ROW, NOT A SPARSE PATCH. carriers/service.ts's own header explains
// why: "Updates every field, including to null when one is absent - exactly
// what the statement it replaces did. A partial update would be a behaviour
// change, and the frontend sends the whole carrier back." COALESCE-ing these
// columns would turn an admin clearing a field back to null into a silent
// no-op, which is the opposite of what the form does. So the statement writes
// every column directly - undefined binds as NULL through the driver, which is
// exactly "absent means clear" for a full-replace write.
export async function create(
  row: Partial<OrganizationPatch> | undefined, id: string, type: string, executor?: Executor
): Promise<OrganizationRow> {
  const { rows } = await query<OrganizationRow>(
    sql("create"),
    [id, type, row?.name, row?.email, row?.phone, row?.enabled],
    executor
  );
  return rows[0];
}

export async function update(
  id: string, row: Partial<OrganizationPatch> | undefined, executor?: Executor
): Promise<boolean> {
  const r = await query(
    sql("update"),
    [row?.name, row?.email, row?.phone, row?.enabled, id],
    executor
  );
  return r.rowCount === 1;
}

export async function remove(id: string, executor?: Executor): Promise<boolean> {
  const r = await query(sql("delete"), [id], executor);
  return r.rowCount === 1;
}

export async function list(executor?: Executor): Promise<OrganizationRow[]> {
  const { rows } = await query<OrganizationRow>(sql("get_all"), [], executor);
  return rows;
}

export async function getOne(id: string, executor?: Executor): Promise<OrganizationRow | undefined> {
  const { rows } = await query<OrganizationRow>(sql("get_one"), [id], executor);
  return rows[0];
}

// By id, for the features that compose an organization into their own shape
// rather than joining to get it. A handful of rows, so one read and a Map beats
// a join on every query - and it keeps the join out of the repos that need it.
export async function byId(executor?: Executor): Promise<Map<string, OrganizationRow>> {
  const rows = await list(executor);
  return new Map(rows.map((o) => [o.id, o]));
}
