// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: crm.assignments
import { z } from 'zod/v4'

export const Assignment = z.object({
  'id': z.string().uuid(),
  'user_id': z.string().uuid().nullable(),
  'lead_id': z.string().uuid().nullable(),
  'assigned_to_id': z.string().uuid().nullable(),
  'assigned_at': z.string(),
  'created_at': z.string(),
  'updated_at': z.string(),
  'created_by_id': z.string().uuid().nullable(),
  'updated_by_id': z.string().uuid().nullable(),
})
export type Assignment = z.infer<typeof Assignment>
// generated:end

export const AssignmentPatch = Assignment.pick({
  user_id: true,
  lead_id: true,
  assigned_to_id: true,
})
export type AssignmentPatch = z.infer<typeof AssignmentPatch>
