// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: crm.calls
import { z } from 'zod/v4'
import { CallDirection, CallState } from './enums.js'

export const Call = z.object({
  'id': z.string().uuid(),
  'provider': z.string(),
  'provider_sid': z.string(),
  'direction': CallDirection,
  'from_number': z.string(),
  'to_number': z.string(),
  'user_id': z.string().uuid().nullable(),
  'employee_id': z.string().uuid().nullable(),
  'status': CallState,
  'duration_seconds': z.number().int().nullable(),
  'recording_url': z.string().nullable(),
  'started_at': z.string(),
  'ended_at': z.string().nullable(),
  'created_at': z.string(),
  'updated_at': z.string(),
  'created_by_id': z.string().uuid().nullable(),
  'updated_by_id': z.string().uuid().nullable(),
  'read_at': z.string().nullable(),
})
export type Call = z.infer<typeof Call>
// generated:end
