// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres enum types owned by the `crm` schema.
import { z } from 'zod/v4'

export const CallDirection = z.enum(['inbound', 'outbound'])
export type CallDirection = z.infer<typeof CallDirection>

export const CallState = z.enum([
  'queued',
  'ringing',
  'in-progress',
  'completed',
  'busy',
  'no-answer',
  'failed',
  'canceled',
  'voicemail',
])
export type CallState = z.infer<typeof CallState>

export const SmsDirection = z.enum(['inbound', 'outbound'])
export type SmsDirection = z.infer<typeof SmsDirection>

export const SmsDeliveryStatus = z.enum([
  'received',
  'queued',
  'sent',
  'delivered',
  'failed',
  'undelivered',
])
export type SmsDeliveryStatus = z.infer<typeof SmsDeliveryStatus>
