// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Every entity of the `crm` schema, one namespace each.
export * from './enums.js'
export * from './calls.js'
export * from './sms_messages.js'
