// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: crm.notes
import { z } from 'zod/v4'

export const Note = z.object({
  'id': z.string().uuid(),
  'user_id': z.string().uuid().nullable(),
  'lead_id': z.string().uuid().nullable(),
  'body': z.string(),
  'created_at': z.string(),
  'updated_at': z.string(),
  'created_by_id': z.string().uuid().nullable(),
  'updated_by_id': z.string().uuid().nullable(),
})
export type Note = z.infer<typeof Note>
// generated:end
import { User } from '../auth/users.js'

export const NoteCreateBody = Note.pick({ body: true })
  .extend({
    user_id: Note.shape.user_id.unwrap().optional(),
    lead_id: Note.shape.lead_id.unwrap().optional(),
  })
  .strict()
  .refine((v) => Boolean(v.user_id) !== Boolean(v.lead_id), {
    message: 'exactly one of user_id or lead_id is required',
  })
export type NoteCreateBody = z.infer<typeof NoteCreateBody>

export const NotePatch = Note.pick({ body: true }).partial().strict()
export type NotePatch = z.infer<typeof NotePatch>

export const NoteSubject = z.object({
  user_id: Note.shape.user_id,
  lead_id: Note.shape.lead_id,
})
export type NoteSubject = z.infer<typeof NoteSubject>

export const NoteView = Note.extend({ author_name: User.shape.name })
export type NoteView = z.infer<typeof NoteView>
