// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: crm.sms_messages
import { z } from 'zod/v4'
import { SmsDeliveryStatus, SmsDirection } from './enums.js'

export const SmsMessage = z.object({
  'id': z.string().uuid(),
  'direction': SmsDirection,
  'provider': z.string(),
  'provider_sid': z.string(),
  'from_number': z.string(),
  'to_number': z.string(),
  'body': z.string().nullable(),
  'media': z.unknown(),
  'status': SmsDeliveryStatus,
  'error_code': z.string().nullable(),
  'user_id': z.string().uuid().nullable(),
  'received_at': z.string().nullable(),
  'sent_at': z.string().nullable(),
  'created_at': z.string(),
  'updated_at': z.string(),
  'created_by_id': z.string().uuid().nullable(),
  'updated_by_id': z.string().uuid().nullable(),
  'read_at': z.string().nullable(),
})
export type SmsMessage = z.infer<typeof SmsMessage>
// generated:end
