// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: crm.sms_consent_events
import { z } from 'zod/v4'

export const SmsConsentEvent = z.object({
  'id': z.string().uuid(),
  'user_id': z.string().uuid().nullable(),
  'lead_id': z.string().uuid().nullable(),
  'kind_id': z.string().uuid(),
  'method': z.string().nullable(),
  'at': z.string(),
  'created_at': z.string(),
  'updated_at': z.string(),
  'created_by_id': z.string().uuid().nullable(),
  'updated_by_id': z.string().uuid().nullable(),
})
export type SmsConsentEvent = z.infer<typeof SmsConsentEvent>
// generated:end
import { SmsConsentMethod } from '../leads/leads.js'

export const SmsConsentDecision = z.enum(['opt_in', 'opt_out'])
export type SmsConsentDecision = z.infer<typeof SmsConsentDecision>

export const SmsConsentEventPatch = SmsConsentEvent.pick({
  user_id: true,
  lead_id: true,
}).extend({
  kind: SmsConsentDecision,
  method: SmsConsentMethod.nullable(),
})
export type SmsConsentEventPatch = z.infer<typeof SmsConsentEventPatch>
