// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: crm.targets
import { z } from 'zod/v4'

export const FunnelTarget = z.object({
  'id': z.string().uuid(),
  'key': z.string(),
  'label': z.string(),
  'value': z.number(),
  'created_at': z.string(),
  'updated_at': z.string(),
  'created_by_id': z.string().uuid().nullable(),
  'updated_by_id': z.string().uuid().nullable(),
})
export type FunnelTarget = z.infer<typeof FunnelTarget>
// generated:end
