// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: crm.timeline_kinds
import { z } from 'zod/v4'

export const TimelineKind = z.object({
  'id': z.string().uuid(),
  'key': z.string(),
  'label': z.string(),
  'sort_order': z.number().int(),
  'created_at': z.string(),
  'updated_at': z.string(),
  'created_by_id': z.string().uuid().nullable(),
  'updated_by_id': z.string().uuid().nullable(),
})
export type TimelineKind = z.infer<typeof TimelineKind>
// generated:end
