// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Every entity of the `rates` schema, one namespace each.
export * from "./rates.js";
