// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: rates.rates
import { z } from "zod/v4";

export const Row = z.object({
  "id": z.string().uuid(),
  "metal_id": z.string().uuid(),
  "unit": z.string(),
  "min_qty": z.number(),
  "max_qty": z.number().nullable(),
  "scrap_pct": z.number(),
  "bullion_pct": z.number(),
  "created_at": z.string(),
  "updated_at": z.string(),
  "created_by": z.string(),
  "updated_by": z.string(),
  "created_by_id": z.string().uuid().nullable(),
  "updated_by_id": z.string().uuid().nullable(),
});
export type Row = z.infer<typeof Row>;
// generated:end
import * as metals from "../metals/metals.js";

// GET /rates/get_all. The query joins metals and returns the metal's NAME in
// place of its id, and drops the audit columns.
export const Read = Row.omit({
  metal_id: true,
  created_at: true,
  updated_at: true,
  created_by: true,
  updated_by: true,
  created_by_id: true,
  updated_by_id: true,
}).extend({ metal: metals.Row.shape.name });
export type Read = z.infer<typeof Read>;

// GET /rates/get_admin, and what create/update answer with - THE SECOND SHAPE
// THIS ENDPOINT HAS ALWAYS SERVED. The frontend used to cover the gap with one
// hand-written type carrying the union of both, metal_id and unit optional, so
// the admin card read metal_id off a value whose type said it might not be
// there.
export const AdminRead = Read.extend({
  metal_id: Row.shape.metal_id,
  created_at: Row.shape.created_at,
  updated_at: Row.shape.updated_at,
  created_by: Row.shape.created_by,
  updated_by: Row.shape.updated_by,
});
export type AdminRead = z.infer<typeof AdminRead>;

// POST /rates/create and /rates/update - the six writable columns and nothing
// else. created_by/updated_by are NOT fields here: public.audit_stamp writes
// both from the connection's actor. The METAL travels as `metal_id` here and
// as `metal` on the way back, which is this feature's one asymmetry.
export const New = Row.pick({
  metal_id: true,
  unit: true,
  min_qty: true,
  max_qty: true,
  scrap_pct: true,
  bullion_pct: true,
});
export type New = z.infer<typeof New>;

export const Patch = New.partial();
export type Patch = z.infer<typeof Patch>;

