// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: rates.rate_history
import { z } from 'zod/v4'

export const RateChange = z.object({
  'id': z.string().uuid(),
  'rate_id': z.string().uuid(),
  'field': z.string(),
  'old_value': z.string().nullable(),
  'new_value': z.string().nullable(),
  'actor_id': z.string().uuid().nullable(),
  'actor_name': z.string().nullable(),
  'changed_at': z.string(),
})
export type RateChange = z.infer<typeof RateChange>
// generated:end

// Hand-written derivations go here: New, Patch, named reads.
