// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: rates.rates
import { z } from "zod/v4";

export const Rate = z.object({
  "id": z.string().uuid(),
  "metal_id": z.string().uuid(),
  "unit": z.string(),
  "min_qty": z.number(),
  "max_qty": z.number().nullable(),
  "scrap_pct": z.number(),
  "bullion_pct": z.number(),
  "created_at": z.string(),
  "updated_at": z.string(),
  "created_by": z.string(),
  "updated_by": z.string(),
  "created_by_id": z.string().uuid().nullable(),
  "updated_by_id": z.string().uuid().nullable(),
});
export type Rate = z.infer<typeof Rate>;
// generated:end
import { Metal } from "../metals/metals.js";

// GET /rates. The query joins metals and returns the metal's NAME in
// place of its id, and drops the audit columns.
export const RateRead = Rate.omit({
  metal_id: true,
  created_at: true,
  updated_at: true,
  created_by: true,
  updated_by: true,
  created_by_id: true,
  updated_by_id: true,
}).extend({ metal: Metal.shape.name });
export type RateRead = z.infer<typeof RateRead>;

// GET /rates/admin, and what create/update answer with - THE SECOND SHAPE
// THIS ENDPOINT HAS ALWAYS SERVED. The frontend used to cover the gap with one
// hand-written type carrying the union of both, metal_id and unit optional, so
// the admin card read metal_id off a value whose type said it might not be
// there.
export const AdminRate = RateRead.extend({
  metal_id: Rate.shape.metal_id,
  created_at: Rate.shape.created_at,
  updated_at: Rate.shape.updated_at,
  created_by: Rate.shape.created_by,
  updated_by: Rate.shape.updated_by,
});
export type AdminRate = z.infer<typeof AdminRate>;

// POST /rates and PATCH /rates/:id - the six writable columns and nothing
// else, all optional (a create sends the same patch). created_by/updated_by
// are NOT fields here: public.audit_stamp writes both from the connection's
// actor. The METAL travels as `metal_id` here and as `metal` on the way
// back, which is this feature's one asymmetry.
export const RatePatch = Rate.pick({
  metal_id: true,
  unit: true,
  min_qty: true,
  max_qty: true,
  scrap_pct: true,
  bullion_pct: true,
}).partial();
export type RatePatch = z.infer<typeof RatePatch>;

