// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: spots.active_sources
import { z } from 'zod/v4'

export const ActiveSpotSource = z.object({
  'metal_id': z.string(),
  'source_id': z.string(),
  'created_at': z.string(),
  'updated_at': z.string(),
  'created_by': z.string(),
  'updated_by': z.string(),
  'created_by_id': z.string().uuid().nullable(),
  'updated_by_id': z.string().uuid().nullable(),
})
export type ActiveSpotSource = z.infer<typeof ActiveSpotSource>
// generated:end

export const ActiveSpotSourcePatch = ActiveSpotSource.pick({ source_id: true })
export type ActiveSpotSourcePatch = z.infer<typeof ActiveSpotSourcePatch>
