// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: spots.adjustments
import { z } from 'zod/v4'

export const SpotAdjustment = z.object({
  'metal_id': z.string(),
  'source_id': z.string(),
  'bid_amount': z.number(),
  'ask_amount': z.number(),
  'unit': z.string(),
  'reason': z.string(),
  'expires_at': z.string().nullable(),
  'expires_at_market_open': z.boolean(),
  'enabled': z.boolean(),
  'created_at': z.string(),
  'updated_at': z.string(),
  'created_by': z.string(),
  'updated_by': z.string(),
  'created_by_id': z.string().uuid().nullable(),
  'updated_by_id': z.string().uuid().nullable(),
})
export type SpotAdjustment = z.infer<typeof SpotAdjustment>
// generated:end

export const SpotAdjustmentUnit = z.enum(['percent', 'dollars'])
export type SpotAdjustmentUnit = z.infer<typeof SpotAdjustmentUnit>

export const SpotAdjustmentScope = z.enum(['Active', 'Dormant'])
export type SpotAdjustmentScope = z.infer<typeof SpotAdjustmentScope>

export const SpotAdjustmentRead = SpotAdjustment.extend({
  unit: SpotAdjustmentUnit,
  scope: SpotAdjustmentScope,
  expires_at_resolved: SpotAdjustment.shape.expires_at,
})
export type SpotAdjustmentRead = z.infer<typeof SpotAdjustmentRead>

export const SpotAdjustmentPatch = SpotAdjustment.pick({
  bid_amount: true,
  ask_amount: true,
  reason: true,
  expires_at: true,
  expires_at_market_open: true,
  enabled: true,
})
  .extend({ unit: SpotAdjustmentUnit })
  .partial()
export type SpotAdjustmentPatch = z.infer<typeof SpotAdjustmentPatch>
