// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: spots.adjustment_history
import { z } from 'zod/v4'

export const SpotAdjustmentChange = z.object({
  'id': z.string().uuid(),
  'metal_id': z.string(),
  'source_id': z.string().nullable(),
  'field': z.string(),
  'old_value': z.string().nullable(),
  'new_value': z.string().nullable(),
  'actor_id': z.string().uuid().nullable(),
  'actor_name': z.string().nullable(),
  'changed_at': z.string(),
})
export type SpotAdjustmentChange = z.infer<typeof SpotAdjustmentChange>
// generated:end

export const SpotAdjustmentChangeRead = SpotAdjustmentChange.extend({ event: z.string() })
export type SpotAdjustmentChangeRead = z.infer<typeof SpotAdjustmentChangeRead>

export const SpotHistoryDays = z.coerce.number().int().min(1).max(3650).default(30)
export type SpotHistoryDays = z.infer<typeof SpotHistoryDays>
