// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: spots.market_sessions
import { z } from 'zod/v4'

export const MarketSession = z.object({
  'weekday': z.number().int(),
  'opens_at': z.string(),
  'closes_at': z.string(),
  'tz': z.string(),
})
export type MarketSession = z.infer<typeof MarketSession>
// generated:end
