// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: spots.market_holidays
import { z } from 'zod/v4'

export const MarketHoliday = z.object({
  'observed_on': z.string(),
  'name': z.string(),
})
export type MarketHoliday = z.infer<typeof MarketHoliday>
// generated:end
