// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: spots.overrides
import { z } from 'zod/v4'

export const SpotOverride = z.object({
  'metal_id': z.string(),
  'bid': z.number(),
  'ask': z.number(),
  'reason': z.string(),
  'expires_at': z.string().nullable(),
  'created_at': z.string(),
  'updated_at': z.string(),
  'created_by': z.string(),
  'updated_by': z.string(),
  'created_by_id': z.string().uuid().nullable(),
  'updated_by_id': z.string().uuid().nullable(),
})
export type SpotOverride = z.infer<typeof SpotOverride>
// generated:end

// Hand-written derivations go here: New, Patch, named reads.
