// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: spots.sources
import { z } from 'zod/v4'

export const SpotSource = z.object({
  'id': z.string(),
  'enabled': z.boolean(),
  'sort_order': z.number().int(),
  'last_tick_at': z.string().nullable(),
  'last_attempt_at': z.string().nullable(),
  'last_error': z.string().nullable(),
  'created_at': z.string(),
  'updated_at': z.string(),
  'created_by': z.string(),
  'updated_by': z.string(),
  'created_by_id': z.string().uuid().nullable(),
  'updated_by_id': z.string().uuid().nullable(),
})
export type SpotSource = z.infer<typeof SpotSource>
// generated:end

import { Metal } from '../metals/metals.js'

export const SpotStatus = z.enum(['Live', 'Standby', 'Off'])
export type SpotStatus = z.infer<typeof SpotStatus>

export const SpotSourceRead = SpotSource.extend({
  status: SpotStatus,
  metal_ids: z.array(Metal.shape.id),
})
export type SpotSourceRead = z.infer<typeof SpotSourceRead>

export const SpotSourcePatch = SpotSource.pick({ enabled: true, sort_order: true }).partial()
export type SpotSourcePatch = z.infer<typeof SpotSourcePatch>
