// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: spots.spots
import { z } from "zod/v4";

export const Spot = z.object({
  "id": z.string().uuid(),
  "metal_id": z.string().uuid(),
  "ask": z.number(),
  "bid": z.number().nullable(),
  "percent_change": z.number().nullable(),
  "dollar_change": z.number().nullable(),
  "updated_at": z.string(),
});
export type Spot = z.infer<typeof Spot>;
// generated:end
import { Metal } from "../metals/metals.js";

// A spot quote, flat, because it has no existence apart from the metal it
// prices - the id here IS the metal's id, and the name is the metal's name.
export const SpotPrice = Spot.pick({
  ask: true,
  bid: true,
  percent_change: true,
  dollar_change: true,
}).extend({
  id: Metal.shape.id,
  name: Metal.shape.name,
  ask: Spot.shape.ask.nullable(),
});
export type SpotPrice = z.infer<typeof SpotPrice>;

// POST-less: the feed cron is the only writer. The four quote columns and
// nothing else - `metal_id` is the WHERE key and `updated_at` is the
// database's.
export const SpotPatch = Spot.pick({
  ask: true,
  bid: true,
  percent_change: true,
  dollar_change: true,
}).partial();
export type SpotPatch = z.infer<typeof SpotPatch>;

// WHICH WAY THE METAL MOVED TODAY. `spots.spots` stores the day's move as a
// number; every ticker then asked `(dollar_change ?? 0) >= 0` for itself and
// picked a caret and a colour from the answer - which called a metal that had
// not moved an UP day, in green, on two screens. The server says which of the
// three it is, once.
export const SpotTrend = z.enum(["up", "down", "flat"]);
export type SpotTrend = z.infer<typeof SpotTrend>;

// GET /spots - the quote plus that answer.
export const SpotTicker = SpotPrice.extend({ direction: SpotTrend });
export type SpotTicker = z.infer<typeof SpotTicker>;
