// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: leads.documents
import { z } from 'zod/v4'

export const LeadDocument = z.object({
  'id': z.string().uuid(),
  'lead_id': z.string().uuid(),
  'pdf_id': z.string().uuid(),
  'created_at': z.string(),
  'updated_at': z.string(),
  'created_by_id': z.string().uuid().nullable(),
  'updated_by_id': z.string().uuid().nullable(),
})
export type LeadDocument = z.infer<typeof LeadDocument>
// generated:end
import { Pdf } from '../media/pdfs.js'

export const LeadDocumentView = LeadDocument.omit({
  created_by_id: true,
  updated_by_id: true,
  updated_at: true,
}).extend({
  kind: Pdf.shape.kind,
  path: Pdf.shape.path,
  size_bytes: Pdf.shape.size_bytes,
  checksum: Pdf.shape.checksum,
  uploaded_at: Pdf.shape.created_at,
})
export type LeadDocumentView = z.infer<typeof LeadDocumentView>
