// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: leads.estimate_items
import { z } from 'zod/v4'

export const EstimateItem = z.object({
  'id': z.string().uuid(),
  'lead_id': z.string().uuid(),
  'kind_id': z.string().uuid(),
  'metal_id': z.string(),
  'weight': z.number(),
  'unit_id': z.string().uuid(),
  'purity_id': z.string().uuid().nullable(),
  'custom_purity': z.number().nullable(),
  'created_at': z.string(),
  'updated_at': z.string(),
  'created_by_id': z.string().uuid().nullable(),
  'updated_by_id': z.string().uuid().nullable(),
})
export type EstimateItem = z.infer<typeof EstimateItem>
// generated:end

export const EstimateItemPatch = EstimateItem.pick({
  kind_id: true,
  metal_id: true,
  weight: true,
  unit_id: true,
  purity_id: true,
  custom_purity: true,
})
  .partial()
  .strict()
export type EstimateItemPatch = z.infer<typeof EstimateItemPatch>
