// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: leads.leads
import { z } from "zod/v4";

export const Row = z.object({
  "id": z.string().uuid(),
  "name": z.string(),
  "phone": z.string().nullable(),
  "email": z.string().nullable(),
  "created_at": z.string(),
  "updated_at": z.string(),
  "last_contacted": z.string().nullable(),
  "converted": z.boolean(),
  "contacted": z.boolean(),
  "responded": z.boolean(),
  "created_by": z.string().nullable(),
  "updated_by": z.string().nullable(),
  "notes": z.string().nullable(),
  "contact": z.string().nullable(),
  "priority": z.string(),
  "created_by_id": z.string().uuid().nullable(),
  "updated_by_id": z.string().uuid().nullable(),
});
export type Row = z.infer<typeof Row>;
// generated:end
// POST /leads/create - WHAT THE STATEMENT ACTUALLY TAKES.
//
// created_by/updated_by are NOT fields here: public.audit_stamp writes both
// from the connection's actor, and a body naming either is a caller claiming
// to be somebody else.
//
// PRIORITY IS PLAIN TEXT AND STAYS THAT WAY. `leads.leads.priority` is
// `text DEFAULT 'Medium'` with no constraint, so a three-value union here
// would be a constraint the database does not have. The frontend's
// High/Medium/Low list is the set its SELECTOR offers.
export const New = Row.pick({
  name: true,
  phone: true,
  email: true,
}).extend({
  priority: Row.shape.priority.optional(),
  notes: Row.shape.notes.optional(),
});
export type New = z.infer<typeof New>;

// The ten columns leads.leads actually allows to change, all optional.
export const Patch = Row.pick({
  name: true,
  phone: true,
  email: true,
  last_contacted: true,
  converted: true,
  contacted: true,
  responded: true,
  contact: true,
  notes: true,
  priority: true,
}).partial();
export type Patch = z.infer<typeof Patch>;

