// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: leads.leads
import { z } from 'zod/v4'

export const Lead = z.object({
  'id': z.string().uuid(),
  'name': z.string(),
  'phone': z.string().nullable(),
  'email': z.string().nullable(),
  'created_at': z.string(),
  'updated_at': z.string(),
  'last_contacted': z.string().nullable(),
  'converted': z.boolean(),
  'contacted': z.boolean(),
  'responded': z.boolean(),
  'created_by': z.string().nullable(),
  'updated_by': z.string().nullable(),
  'notes': z.string().nullable(),
  'contact': z.string().nullable(),
  'priority': z.string(),
  'created_by_id': z.string().uuid().nullable(),
  'updated_by_id': z.string().uuid().nullable(),
  'assigned_to_id': z.string().uuid().nullable(),
  'source': z.string().nullable(),
  'sms_consent_at': z.string().nullable(),
  'sms_consent_method': z.string().nullable(),
  'source_id': z.string().uuid().nullable(),
  'contact_preference_id': z.string().uuid().nullable(),
  'number': z.string(),
  'contacted_at': z.string().nullable(),
  'responded_at': z.string().nullable(),
  'converted_at': z.string().nullable(),
})
export type Lead = z.infer<typeof Lead>
// generated:end
import { LeadStage } from '../computed/crm.js'

export const SmsConsentMethod = z.enum(['web_form', 'verbal', 'via_text'])
export type SmsConsentMethod = z.infer<typeof SmsConsentMethod>

export const LeadPatch = Lead.pick({
  name: true,
  phone: true,
  email: true,
  last_contacted: true,
  converted: true,
  contacted: true,
  responded: true,
  contact: true,
  priority: true,
  source: true,
  source_id: true,
  contact_preference_id: true,
  assigned_to_id: true,
})
  .partial()
  .strict()
  .extend({ sms_consent_method: SmsConsentMethod.nullable().optional() })
export type LeadPatch = z.infer<typeof LeadPatch>

export const LeadView = Lead.extend({ lead_stage: LeadStage })
export type LeadView = z.infer<typeof LeadView>

export const LeadConvertBody = z
  .object({
    name: Lead.shape.name,
    phone: Lead.shape.phone,
    email: Lead.shape.email,
  })
  .partial()
  .strict()
export type LeadConvertBody = z.infer<typeof LeadConvertBody>

export const LeadFilter = z.object({}).extend({
  stage: LeadStage.nullable(),
  priority: Lead.shape.priority.nullable(),
  assigned_to: z.string().nullable(),
  source: Lead.shape.source,
  search: z.string().nullable(),
})
export type LeadFilter = z.infer<typeof LeadFilter>
