// generated:start
// GENERATED by packages/contracts/scripts/generate-entities.mjs
// Run `pnpm --filter @dorado/contracts generate` to refresh.
//
// Postgres table: leads.weight_units
import { z } from 'zod/v4'

export const EstimateUnit = z.object({
  'id': z.string().uuid(),
  'key': z.string(),
  'label': z.string(),
  'grams': z.number(),
  'sort_order': z.number().int(),
  'created_at': z.string(),
  'updated_at': z.string(),
  'created_by_id': z.string().uuid().nullable(),
  'updated_by_id': z.string().uuid().nullable(),
})
export type EstimateUnit = z.infer<typeof EstimateUnit>
// generated:end
